In [1]:
from datasets import load_dataset

/home/teoaivalis/.conda/envs/artbench_env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Load Artbench Dataset

In [2]:
import pandas as pd

df = pd.read_csv('/home/teoaivalis/.cache/kagglehub/datasets/alexanderliao/artbench10/versions/2/ArtBench-10.csv')
#df = pd.read_csv('../../../../codes/artbench/ArtBench-10.csv')
df.head()

,name,artist,url,is_public_domain,length,width,label,split,cifar_index
0,frank-omeara_towards-night-and-winter.jpg,frank-omeara,https://uploads5.wikiart.org/00316/images/fran...,True,800,657,impressionism,train,43186
1,goldstein-grigoriy_morning.jpg,goldstein-grigoriy,https://uploads5.wikiart.org/images/grigoriy-g...,True,521,499,impressionism,train,41151
2,georges-lemmen_man-reading.jpg,georges-lemmen,https://uploads6.wikiart.org/images/georges-le...,True,800,612,impressionism,train,9754
3,theodor-aman_port-of-constantza-1882.jpg,theodor-aman,https://uploads6.wikiart.org/images/theodor-am...,True,560,336,impressionism,train,44244
4,niccolo-cannicci_il-passo-della-futa-1914.jpg,niccolo-cannicci,https://uploads3.wikiart.org/images/niccolo-ca...,True,2400,2322,impressionism,train,46885

In [3]:
print(df.iloc[0][0])
print(df.iloc[0][1])
print(df.iloc[0][2])

print(df.iloc[1][0])
print(df.iloc[1][1])
print(df.iloc[1][2])

print(df.iloc[2][0])
print(df.iloc[2][1])
print(df.iloc[2][2])

print(df.iloc[3][0])
print(df.iloc[3][1])
print(df.iloc[3][2])

frank-omeara_towards-night-and-winter.jpg
frank-omeara
https://uploads5.wikiart.org/00316/images/frank-omeara/towards-night-and-winter.jpg
goldstein-grigoriy_morning.jpg
goldstein-grigoriy
https://uploads5.wikiart.org/images/grigoriy-goldstein/morning.jpg
georges-lemmen_man-reading.jpg
georges-lemmen
https://uploads6.wikiart.org/images/georges-lemmen/man-reading.jpg
theodor-aman_port-of-constantza-1882.jpg
theodor-aman
https://uploads6.wikiart.org/images/theodor-aman/port-of-constantza-1882.jpg

/tmp/ipykernel_3710156/2401613183.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.iloc[0][0])
/tmp/ipykernel_3710156/2401613183.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.iloc[0][1])
/tmp/ipykernel_3710156/2401613183.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.iloc[0][2])
/tmp/ipykernel_3710156/2401613183.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.iloc[1][0])
/tmp/ipykernel_3710156/2401613183.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.iloc[1][1])
/tmp/ipykernel_3710156/2401613183.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.iloc[1][2])
/tmp/ipykernel_3710156/2401613183.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.iloc[2][0])
/tmp/ipykernel_3710156/2401613183.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.iloc[2][1])
/tmp/ipykernel_3710156/2401613183.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.iloc[2][2])
/tmp/ipykernel_3710156/2401613183.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.iloc[3][0])
/tmp/ipykernel_3710156/2401613183.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.iloc[3][1])
/tmp/ipykernel_3710156/2401613183.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.iloc[3][2])

In [4]:
import requests
from bs4 import BeautifulSoup
import time
import pandas as pd
from tqdm.notebook import tqdm 

def scrape_wikiart_artist(artist_slug):
    # Ensure artist_slug is a string
    if not isinstance(artist_slug, str):
        return {"artist_slug": artist_slug, "status": "Invalid Name"}
        
    url = f"https://www.wikiart.org/en/{artist_slug}"
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
    
    try:
        response = requests.get(url, headers=headers, timeout=10)
        if response.status_code != 200:
            return {"artist_slug": artist_slug, "status": f"HTTP {response.status_code}"}
        
        soup = BeautifulSoup(response.text, 'html.parser')
        metadata = {"artist_slug": artist_slug, "status": "Success"}
        
        # WikiArt metadata is usually in 'p-info-list' or 'li' tags
        info_list = soup.find('ul', class_='p-info-list')
        items = info_list.find_all('li') if info_list else soup.find_all('li')
        
        for li in items:
            text = li.get_text(separator=" ").strip()
            if ":" in text and len(text) < 200:
                parts = text.split(":", 1)
                key = parts[0].strip().lower()
                val = parts[1].strip()
                metadata[key] = val
        
        return metadata
    except Exception as e:
        return {"artist_slug": artist_slug, "status": f"Error: {str(e)}"}

In [5]:
from tqdm import tqdm  # Change this from tqdm.notebook to just tqdm
# 1. Get unique artist names from your dataframe
unique_artists = df['artist'].unique()
print(f"Total unique artists found: {len(unique_artists)}")

# 2. Test with a small batch first (remove .head(20) for the full run)
test_batch = unique_artists[1000:] 

results = []
for artist in tqdm(test_batch, desc="Scraping WikiArt"):
#for artist in tqdm(unique_artists, desc="Scraping WikiArt"):
    data = scrape_wikiart_artist(artist)
    results.append(data)
    time.sleep(1.1) # polite delay

# 3. Create metadata dataframe
wiki_metadata_df2 = pd.DataFrame(results)

# 4. Display the results
print("\n--- Scraped Metadata ---")
display(wiki_metadata_df1.head())

Total unique artists found: 2126

Scraping WikiArt: 100%|██████████| 1126/1126 [42:59<00:00,  2.29s/it]

--- Scraped Metadata ---

NameError: name 'wiki_metadata_df1' is not defined

In [6]:
# 4. Display the results
print("\n--- Scraped Metadata ---")
display(wiki_metadata_df2.head())

--- Scraped Metadata ---

,artist_slug,status,born,died,nationality,art movement,painting school,field,teachers,art institution,...,san marco,piazza san marco,grand canal,untitled (from conspiracy,three beauties,shinagawa,monday,november,sino-japanese war,sixty-nine stations of the kisokaido
0,vasyl-yermylov,Success,"March 22, 1894 ; Kharkiv, Ukraine","January 6, 1968 ; Kharkiv, Ukraine",Ukrainians,"Avant-garde , \n Constructivism , \n Cubo-Futu...",ARMU (Association of Revolutionary Masters of ...,"painting , \n printmaking , \n design","Ilya Mashkov , \n Pyotr Konchalovsky","Moscow School of Painting, Sculpture and Archi...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,mario-eloy,Success,"March 15, 1900 ; Algés, Portugal","September 5, 1951 ; Lisbon, Portugal",Portuguese,Expressionism,NaN,painting,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,botong-francisco,Success,"November 4, 1912 ; Angono, Philippines","March 31, 1969 ; Angono, Philippines",Filipino,"Social Realism , \n Modernism",NaN,painting,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,max-bill,Success,"December 22, 1908 ; Winterthur, Switzerland","December 9, 1994 ; Berlin, Germany",Swiss,Concrete Art (Concretism),"Bauhaus , \n Abstraction-Création","painting , \n design , \n architecture , \n dr...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,jeanne-hebuterne,Success,"April 6, 1898 ; Paris, France","January 25, 1920 ; Paris, France",French,Expressionism,NaN,painting,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
frames = [wiki_metadata_df, wiki_metadata_df1]

result = pd.concat(frames)

In [11]:
display(result.head())

,artist_slug,status,born,died,nationality,art movement,field,influenced by,teachers,friends and co-workers,...,ivan bakmaz,musical moments,given,"study for ""given",chinese opera series,the funeral of romanticism,late afternoon,evening sun,planners,"forwards, parcifal series, group 2, section 4"
0,frank-omeara,Success,"March 30, 1853 ; Carlow, Ireland","October 15, 1888 ; Carlow, Ireland",Irish,Impressionism,painting,Diego Velazquez,Carolus-Duran,"John Singer Sargent , \n John Lavery , \n Carl...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,goldstein-grigoriy,Success,"December 28, 1878 ; Odessa, Ukraine","May 5, 1938 ; Saint Petersburg, Russian Fede...","Russian , \n Jewish",Symbolism,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,georges-lemmen,Success,"1865 ; Schaerbeek, Belgium","1916 ; Brussels, Belgium",Belgian,"Art Nouveau , \n Neo-Impressionism",painting,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,theodor-aman,Success,"March 20, 1831 ; Câmpulung-Muscel, Romania","August 19, 1891 ; Bucharest, Romania",Romanian,"Academic Art , \n Romanticism","painting , \n engraving , \n drawing",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,niccolo-cannicci,Success,"1846 ; Firenze, Italy","1906 ; Firenze, Italy",Italian,"Realism , \n Impressionism",painting,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
import json


wiki_metadata_df2.to_json('wikiart_artist_metadata1.json', orient='records', indent=4)
#result.to_json('wikiart_artist_metadata.json', orient='records', indent=4)


print("Files saved successfully:")
print("- wikiart_artist_metadata1.json")

Files saved successfully:
- wikiart_artist_metadata1.json

In [8]:
import wikipediaapi
import json
import os

wiki_wiki = wikipediaapi.Wikipedia(
    user_agent='ArtInfluenceResearch/1.0 (contact: yourname@example.com)',
    language='en',
    extract_format=wikipediaapi.ExtractFormat.WIKI
)

def fetch_and_save_artist_wiki(page_title, save_dir="./"):
    if not os.path.exists(save_dir):
        os.makedirs(save_dir)
    
    page = wiki_wiki.page(page_title)
    
    if not page.exists():
        print(f"Η σελίδα '{page_title}' δεν βρέθηκε.")
        return None
    
    def get_sections(sections):
        return {s.title: {"text": s.text, "subsections": get_sections(s.sections)} for s in sections}

    artist_data = {
        "title": page.title,
        "summary": page.summary,
        "full_text": page.text,
        "url": page.fullurl,
        "categories": [c.replace("Category:", "") for c in page.categories.keys()],
        "sections": get_sections(page.sections)
    }
    
    file_path = os.path.join(save_dir, f"{page_title.replace(' ', '_')}.json")
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(artist_data, f, ensure_ascii=False, indent=4)
    
    print(f"Wikipedia Data saved: {file_path}")
    return artist_data

In [11]:
# Εκτέλεση για τον Frank O'Meara
full_data = fetch_and_save_artist_wiki("Frank O'Meara")

if full_data:
    print("\n--- Επισκόπηση Δεδομένων ---")
    print(f"Τίτλος: {full_data['title']}")
    print(f"Σύνολο λέξεων: {len(full_data['full_text'].split())}")
    print(f"Ενότητες που βρέθηκαν: {list(full_data['sections'].keys())}")

Wikipedia Data saved: ./Frank_O'Meara.json

--- Επισκόπηση Δεδομένων ---
Τίτλος: Frank O'Meara
Σύνολο λέξεων: 761
Ενότητες που βρέθηκαν: ['Life', 'Artistic career', 'References', 'External links']

New wikifetch

In [10]:
import json
import time
from tqdm import tqdm

# 1. Load your existing WikiArt metadata
with open('wikiart_artist_metadata1.json', 'r', encoding='utf-8') as f:
    artists_list = json.load(f)

print(f"Loaded {len(artists_list)} artists from JSON.")

# 2. Define the extraction logic
def extract_wiki_title(wiki_field):
    """Extracts 'Frank O'Meara' from 'en.wikipedia.org/wiki/Frank_O'Meara'"""
    if not wiki_field or not isinstance(wiki_field, str):
        return None
    # Split by /wiki/ and take the last part
    if "/wiki/" in wiki_field:
        title = wiki_field.split("/wiki/")[-1]
        # Replace underscores with spaces and decode URL characters
        return title.replace('_', ' ')
    return None

# 3. Loop through everyone
all_wiki_data = []

for artist in tqdm(artists_list, desc="Fetching Wikipedia Data"):
    # Priority 1: Use the Wikipedia URL field if it exists
    page_title = extract_wiki_title(artist.get("wikipedia"))
    
    # Priority 2: Fallback to artist_slug if Wikipedia field is null
    if not page_title:
        # Convert slug 'goldstein-grigoriy' to 'Grigoriy Goldstein'
        slug = artist.get("artist_slug", "")
        page_title = " ".join(word.capitalize() for word in slug.split("-")[::-1])

    # Fetch data
    try:
        wiki_data = fetch_and_save_artist_wiki(page_title, save_dir="./artist_wiki_pages")
        if wiki_data:
            all_wiki_data.append(wiki_data)
        
        # Respectful delay to avoid Wikipedia rate limits
        time.sleep(0.5) 
    except Exception as e:
        print(f"Error processing {page_title}: {e}")

# 4. Final summary
print(f"\nTask Complete. Successfully fetched {len(all_wiki_data)} Wikipedia articles.")

Loaded 1126 artists from JSON.

Fetching Wikipedia Data:   0%|          | 0/1126 [00:00<?, ?it/s]

Wikipedia Data saved: ./artist_wiki_pages/Vasyl_Yermylov.json

Fetching Wikipedia Data:   0%|          | 1/1126 [00:01<34:22,  1.83s/it]

Wikipedia Data saved: ./artist_wiki_pages/Mário_Eloy.json

Fetching Wikipedia Data:   0%|          | 2/1126 [00:02<26:05,  1.39s/it]

Wikipedia Data saved: ./artist_wiki_pages/Botong_Francisco.json

Fetching Wikipedia Data:   0%|          | 3/1126 [00:04<29:00,  1.55s/it]

Wikipedia Data saved: ./artist_wiki_pages/Max_Bill.json

Fetching Wikipedia Data:   0%|          | 4/1126 [00:05<25:41,  1.37s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jeanne_Hébuterne.json

Fetching Wikipedia Data:   0%|          | 5/1126 [00:07<28:45,  1.54s/it]

Wikipedia Data saved: ./artist_wiki_pages/Alfred_Kubin.json

Fetching Wikipedia Data:   1%|          | 6/1126 [00:08<25:55,  1.39s/it]

Wikipedia Data saved: ./artist_wiki_pages/János_Mattis-Teutsch.json

Fetching Wikipedia Data:   1%|          | 7/1126 [00:09<24:03,  1.29s/it]

Wikipedia Data saved: ./artist_wiki_pages/Alberto_Burri.json

Fetching Wikipedia Data:   1%|          | 8/1126 [00:10<23:19,  1.25s/it]

Wikipedia Data saved: ./artist_wiki_pages/Max_Beckmann.json

Fetching Wikipedia Data:   1%|          | 9/1126 [00:12<22:40,  1.22s/it]

Wikipedia Data saved: ./artist_wiki_pages/Otto_Dix.json

Fetching Wikipedia Data:   1%|          | 10/1126 [00:14<28:56,  1.56s/it]

Wikipedia Data saved: ./artist_wiki_pages/Hans_Hofmann.json

Fetching Wikipedia Data:   1%|          | 11/1126 [00:15<26:39,  1.43s/it]

Wikipedia Data saved: ./artist_wiki_pages/Lajos_Vajda.json

Fetching Wikipedia Data:   1%|          | 12/1126 [00:17<28:48,  1.55s/it]

Wikipedia Data saved: ./artist_wiki_pages/James_Lesesne_Wells.json

Fetching Wikipedia Data:   1%|          | 13/1126 [00:18<26:09,  1.41s/it]

Wikipedia Data saved: ./artist_wiki_pages/Dr._Atl.json

Fetching Wikipedia Data:   1%|          | 14/1126 [00:19<24:08,  1.30s/it]

Η σελίδα 'Souto Arturo' δεν βρέθηκε.

Fetching Wikipedia Data:   1%|▏         | 15/1126 [00:20<20:52,  1.13s/it]

Η σελίδα 'Isupov Ilya' δεν βρέθηκε.

Fetching Wikipedia Data:   1%|▏         | 16/1126 [00:20<18:30,  1.00s/it]

Wikipedia Data saved: ./artist_wiki_pages/Xavier_Mellery.json

Fetching Wikipedia Data:   2%|▏         | 17/1126 [00:22<22:03,  1.19s/it]

Wikipedia Data saved: ./artist_wiki_pages/Bruno_Cassinari.json

Fetching Wikipedia Data:   2%|▏         | 18/1126 [00:24<24:30,  1.33s/it]

Wikipedia Data saved: ./artist_wiki_pages/Oswaldo_Guayasamín.json

Fetching Wikipedia Data:   2%|▏         | 19/1126 [00:25<22:56,  1.24s/it]

Wikipedia Data saved: ./artist_wiki_pages/Alberto_Magnelli.json

Fetching Wikipedia Data:   2%|▏         | 20/1126 [00:26<22:02,  1.20s/it]

Wikipedia Data saved: ./artist_wiki_pages/Franz_Sedlacek.json

Fetching Wikipedia Data:   2%|▏         | 21/1126 [00:27<21:18,  1.16s/it]

Wikipedia Data saved: ./artist_wiki_pages/Gabriele_Münter.json

Fetching Wikipedia Data:   2%|▏         | 22/1126 [00:28<21:18,  1.16s/it]

Η σελίδα 'Félix Del Marle' δεν βρέθηκε.

Fetching Wikipedia Data:   2%|▏         | 23/1126 [00:29<18:47,  1.02s/it]

Wikipedia Data saved: ./artist_wiki_pages/Joan_Ponç.json

Fetching Wikipedia Data:   2%|▏         | 24/1126 [00:31<22:37,  1.23s/it]

Η σελίδα 'Kolozyan Babken' δεν βρέθηκε.

Fetching Wikipedia Data:   2%|▏         | 25/1126 [00:31<19:41,  1.07s/it]

Wikipedia Data saved: ./artist_wiki_pages/Leo_Leuppi.json

Fetching Wikipedia Data:   2%|▏         | 26/1126 [00:33<21:57,  1.20s/it]

Wikipedia Data saved: ./artist_wiki_pages/Xul_Solar.json

Fetching Wikipedia Data:   2%|▏         | 27/1126 [00:34<24:54,  1.36s/it]

Wikipedia Data saved: ./artist_wiki_pages/Hélène_de_Beauvoir.json

Fetching Wikipedia Data:   2%|▏         | 28/1126 [00:36<23:23,  1.28s/it]

Wikipedia Data saved: ./artist_wiki_pages/Wojciech_Fangor.json

Fetching Wikipedia Data:   3%|▎         | 29/1126 [00:37<22:33,  1.23s/it]

Wikipedia Data saved: ./artist_wiki_pages/Barnett_Newman.json

Fetching Wikipedia Data:   3%|▎         | 30/1126 [00:38<21:38,  1.18s/it]

Wikipedia Data saved: ./artist_wiki_pages/Béla_Kádár.json

Fetching Wikipedia Data:   3%|▎         | 31/1126 [00:39<20:55,  1.15s/it]

Η σελίδα 'Papian Anatoli' δεν βρέθηκε.

Fetching Wikipedia Data:   3%|▎         | 32/1126 [00:39<18:25,  1.01s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jean_Cocteau.json

Fetching Wikipedia Data:   3%|▎         | 33/1126 [00:42<27:28,  1.51s/it]

Wikipedia Data saved: ./artist_wiki_pages/Filippo_De_Pisis.json

Fetching Wikipedia Data:   3%|▎         | 34/1126 [00:43<25:03,  1.38s/it]

Wikipedia Data saved: ./artist_wiki_pages/Carlos_Botelho_(painter).json

Fetching Wikipedia Data:   3%|▎         | 35/1126 [00:44<23:32,  1.29s/it]

Wikipedia Data saved: ./artist_wiki_pages/Giuseppe_Santomaso.json

Fetching Wikipedia Data:   3%|▎         | 36/1126 [00:46<25:24,  1.40s/it]

Wikipedia Data saved: ./artist_wiki_pages/Beauford_Delaney.json

Fetching Wikipedia Data:   3%|▎         | 37/1126 [00:47<24:04,  1.33s/it]

Wikipedia Data saved: ./artist_wiki_pages/Pierre_Alechinsky.json

Fetching Wikipedia Data:   3%|▎         | 38/1126 [00:49<26:46,  1.48s/it]

Wikipedia Data saved: ./artist_wiki_pages/Georg_Tappert.json

Fetching Wikipedia Data:   3%|▎         | 39/1126 [00:50<24:32,  1.35s/it]

Wikipedia Data saved: ./artist_wiki_pages/Luigi_Russolo.json

Fetching Wikipedia Data:   4%|▎         | 40/1126 [00:51<23:20,  1.29s/it]

Wikipedia Data saved: ./artist_wiki_pages/Albert_Bloch.json

Fetching Wikipedia Data:   4%|▎         | 41/1126 [00:53<25:51,  1.43s/it]

Wikipedia Data saved: ./artist_wiki_pages/Charles_Blackman.json

Fetching Wikipedia Data:   4%|▎         | 42/1126 [00:55<28:25,  1.57s/it]

Wikipedia Data saved: ./artist_wiki_pages/Gerard_Sekoto.json

Fetching Wikipedia Data:   4%|▍         | 43/1126 [00:57<29:10,  1.62s/it]

Wikipedia Data saved: ./artist_wiki_pages/Rufino_Tamayo.json

Fetching Wikipedia Data:   4%|▍         | 44/1126 [00:58<26:14,  1.46s/it]

Wikipedia Data saved: ./artist_wiki_pages/Serge_Sudeikin.json

Fetching Wikipedia Data:   4%|▍         | 45/1126 [00:59<26:01,  1.44s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jean_Hélion.json

Fetching Wikipedia Data:   4%|▍         | 46/1126 [01:00<23:59,  1.33s/it]

Wikipedia Data saved: ./artist_wiki_pages/Sá_Nogueira.json

Fetching Wikipedia Data:   4%|▍         | 47/1126 [01:02<24:33,  1.37s/it]

Η σελίδα 'Busa Peter' δεν βρέθηκε.

Fetching Wikipedia Data:   4%|▍         | 48/1126 [01:02<20:58,  1.17s/it]

Wikipedia Data saved: ./artist_wiki_pages/Paul_Guiragossian.json

Fetching Wikipedia Data:   4%|▍         | 49/1126 [01:04<22:53,  1.28s/it]

Wikipedia Data saved: ./artist_wiki_pages/Wayne_Thiebaud.json

Fetching Wikipedia Data:   4%|▍         | 50/1126 [01:05<21:51,  1.22s/it]

Η σελίδα 'Nikias Skapinakis' δεν βρέθηκε.

Fetching Wikipedia Data:   5%|▍         | 51/1126 [01:06<19:00,  1.06s/it]

Wikipedia Data saved: ./artist_wiki_pages/M._F._Husain.json

Fetching Wikipedia Data:   5%|▍         | 52/1126 [01:07<20:19,  1.14s/it]

Wikipedia Data saved: ./artist_wiki_pages/Suzanne_Duchamp.json

Fetching Wikipedia Data:   5%|▍         | 53/1126 [01:08<20:58,  1.17s/it]

Wikipedia Data saved: ./artist_wiki_pages/Neil_Welliver.json

Fetching Wikipedia Data:   5%|▍         | 54/1126 [01:10<22:20,  1.25s/it]

Wikipedia Data saved: ./artist_wiki_pages/Isamu_Noguchi.json

Fetching Wikipedia Data:   5%|▍         | 55/1126 [01:11<21:52,  1.23s/it]

Wikipedia Data saved: ./artist_wiki_pages/Paula_Rego.json

Fetching Wikipedia Data:   5%|▍         | 56/1126 [01:12<21:34,  1.21s/it]

Wikipedia Data saved: ./artist_wiki_pages/Clyfford_Still.json

Fetching Wikipedia Data:   5%|▌         | 57/1126 [01:13<21:15,  1.19s/it]

Η σελίδα 'Hanson Erin' δεν βρέθηκε.

Fetching Wikipedia Data:   5%|▌         | 58/1126 [01:14<18:35,  1.04s/it]

Η σελίδα 'Bartos Endre' δεν βρέθηκε.

Fetching Wikipedia Data:   5%|▌         | 59/1126 [01:14<16:43,  1.06it/s]

Wikipedia Data saved: ./artist_wiki_pages/Vlady_Kibalchich_Rusakov.json

Fetching Wikipedia Data:   5%|▌         | 60/1126 [01:16<18:06,  1.02s/it]

Wikipedia Data saved: ./artist_wiki_pages/Moise_Kisling.json

Fetching Wikipedia Data:   5%|▌         | 61/1126 [01:17<22:17,  1.26s/it]

Wikipedia Data saved: ./artist_wiki_pages/Paul_Klee.json

Fetching Wikipedia Data:   6%|▌         | 62/1126 [01:19<22:19,  1.26s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jacoba_van_Heemskerck.json

Fetching Wikipedia Data:   6%|▌         | 63/1126 [01:20<24:43,  1.40s/it]

Wikipedia Data saved: ./artist_wiki_pages/Edwin_Dickinson.json

Fetching Wikipedia Data:   6%|▌         | 64/1126 [01:22<23:46,  1.34s/it]

Η σελίδα 'Bailly Alice' δεν βρέθηκε.

Fetching Wikipedia Data:   6%|▌         | 65/1126 [01:22<20:18,  1.15s/it]

Wikipedia Data saved: ./artist_wiki_pages/Alexandre_Jacovleff.json

Fetching Wikipedia Data:   6%|▌         | 66/1126 [01:24<23:22,  1.32s/it]

Wikipedia Data saved: ./artist_wiki_pages/Konrad_Zuse.json

Fetching Wikipedia Data:   6%|▌         | 67/1126 [01:25<22:10,  1.26s/it]

Wikipedia Data saved: ./artist_wiki_pages/Ivan_Eyre.json

Fetching Wikipedia Data:   6%|▌         | 68/1126 [01:27<26:28,  1.50s/it]

Wikipedia Data saved: ./artist_wiki_pages/Candido_Portinari.json

Fetching Wikipedia Data:   6%|▌         | 69/1126 [01:28<24:05,  1.37s/it]

Η σελίδα 'Abeghian Mher' δεν βρέθηκε.

Fetching Wikipedia Data:   6%|▌         | 70/1126 [01:29<20:32,  1.17s/it]

Wikipedia Data saved: ./artist_wiki_pages/Ernst_Ludwig_Kirchner.json

Fetching Wikipedia Data:   6%|▋         | 71/1126 [01:31<27:18,  1.55s/it]

Wikipedia Data saved: ./artist_wiki_pages/Lyonel_Feininger.json

Fetching Wikipedia Data:   6%|▋         | 72/1126 [01:33<28:36,  1.63s/it]

Η σελίδα 'Tano Festa' δεν βρέθηκε.

Fetching Wikipedia Data:   6%|▋         | 73/1126 [01:34<23:39,  1.35s/it]

Wikipedia Data saved: ./artist_wiki_pages/Alexander_Bogen.json

Fetching Wikipedia Data:   7%|▋         | 74/1126 [01:36<27:11,  1.55s/it]

Wikipedia Data saved: ./artist_wiki_pages/David_Alfaro_Siqueiros.json

Fetching Wikipedia Data:   7%|▋         | 75/1126 [01:37<24:43,  1.41s/it]

Wikipedia Data saved: ./artist_wiki_pages/Nikolaos_Lytras.json

Fetching Wikipedia Data:   7%|▋         | 76/1126 [01:39<26:18,  1.50s/it]

Wikipedia Data saved: ./artist_wiki_pages/Alberto_Gironella.json

Fetching Wikipedia Data:   7%|▋         | 77/1126 [01:40<24:03,  1.38s/it]

Wikipedia Data saved: ./artist_wiki_pages/Elaine_de_Kooning.json

Fetching Wikipedia Data:   7%|▋         | 78/1126 [01:41<22:52,  1.31s/it]

Wikipedia Data saved: ./artist_wiki_pages/Yasuo_Kuniyoshi.json

Fetching Wikipedia Data:   7%|▋         | 79/1126 [01:43<26:24,  1.51s/it]

Wikipedia Data saved: ./artist_wiki_pages/Bernardo_Marques.json

Fetching Wikipedia Data:   7%|▋         | 80/1126 [01:44<24:00,  1.38s/it]

Η σελίδα 'Yanyong Ding' δεν βρέθηκε.

Fetching Wikipedia Data:   7%|▋         | 81/1126 [01:45<20:25,  1.17s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jacob_Lawrence.json

Fetching Wikipedia Data:   7%|▋         | 82/1126 [01:46<20:51,  1.20s/it]

Η σελίδα 'Marin Gherasim' δεν βρέθηκε.

Fetching Wikipedia Data:   7%|▋         | 83/1126 [01:47<18:10,  1.05s/it]

Η σελίδα 'Седляр, Василий Теофанович' δεν βρέθηκε.

Fetching Wikipedia Data:   7%|▋         | 84/1126 [01:47<16:22,  1.06it/s]

Wikipedia Data saved: ./artist_wiki_pages/Malcolm_Morley.json

Fetching Wikipedia Data:   8%|▊         | 85/1126 [01:49<17:03,  1.02it/s]

Wikipedia Data saved: ./artist_wiki_pages/László_Moholy-Nagy.json

Fetching Wikipedia Data:   8%|▊         | 86/1126 [01:50<17:57,  1.04s/it]

Wikipedia Data saved: ./artist_wiki_pages/Júlio_Pomar.json

Fetching Wikipedia Data:   8%|▊         | 87/1126 [01:51<18:18,  1.06s/it]

Wikipedia Data saved: ./artist_wiki_pages/Richard_Hambleton.json

Fetching Wikipedia Data:   8%|▊         | 88/1126 [01:53<23:24,  1.35s/it]

Wikipedia Data saved: ./artist_wiki_pages/Arthur_Lismer.json

Fetching Wikipedia Data:   8%|▊         | 89/1126 [01:54<21:54,  1.27s/it]

Wikipedia Data saved: ./artist_wiki_pages/Marino_Marini_(sculptor).json

Fetching Wikipedia Data:   8%|▊         | 90/1126 [01:55<20:55,  1.21s/it]

Wikipedia Data saved: ./artist_wiki_pages/Émilie_Charmy.json

Fetching Wikipedia Data:   8%|▊         | 91/1126 [01:57<25:17,  1.47s/it]

Wikipedia Data saved: ./artist_wiki_pages/Kerry_James_Marshall.json

Fetching Wikipedia Data:   8%|▊         | 92/1126 [01:58<24:16,  1.41s/it]

Wikipedia Data saved: ./artist_wiki_pages/Anton_Prinner.json

Fetching Wikipedia Data:   8%|▊         | 93/1126 [01:59<22:36,  1.31s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jacob_Epstein.json

Fetching Wikipedia Data:   8%|▊         | 94/1126 [02:01<23:12,  1.35s/it]

Η σελίδα 'Guglielmi Louis O' δεν βρέθηκε.

Fetching Wikipedia Data:   8%|▊         | 95/1126 [02:02<19:49,  1.15s/it]

Η σελίδα 'Hick Jacqueline' δεν βρέθηκε.

Fetching Wikipedia Data:   9%|▊         | 96/1126 [02:02<17:31,  1.02s/it]

Wikipedia Data saved: ./artist_wiki_pages/John_Bratby.json

Fetching Wikipedia Data:   9%|▊         | 97/1126 [02:04<21:07,  1.23s/it]

Wikipedia Data saved: ./artist_wiki_pages/José_Gutiérrez_Solana.json

Fetching Wikipedia Data:   9%|▊         | 98/1126 [02:05<20:12,  1.18s/it]

Wikipedia Data saved: ./artist_wiki_pages/Konstantinos_Parthenis.json

Fetching Wikipedia Data:   9%|▉         | 99/1126 [02:06<19:35,  1.14s/it]

Η σελίδα 'Kazar Vasile' δεν βρέθηκε.

Fetching Wikipedia Data:   9%|▉         | 100/1126 [02:07<17:17,  1.01s/it]

Wikipedia Data saved: ./artist_wiki_pages/Constantin_Brâncuși.json

Fetching Wikipedia Data:   9%|▉         | 101/1126 [02:08<18:09,  1.06s/it]

Η σελίδα 'Лобода, Владимир Викторович' δεν βρέθηκε.

Fetching Wikipedia Data:   9%|▉         | 102/1126 [02:09<16:16,  1.05it/s]

Wikipedia Data saved: ./artist_wiki_pages/Ad_Reinhardt.json

Fetching Wikipedia Data:   9%|▉         | 103/1126 [02:10<16:49,  1.01it/s]

Wikipedia Data saved: ./artist_wiki_pages/Martyl_Langsdorf.json

Fetching Wikipedia Data:   9%|▉         | 104/1126 [02:11<19:52,  1.17s/it]

Wikipedia Data saved: ./artist_wiki_pages/Marie_Vorobieff.json

Fetching Wikipedia Data:   9%|▉         | 105/1126 [02:13<24:35,  1.44s/it]

Wikipedia Data saved: ./artist_wiki_pages/Júlio_Resende.json

Fetching Wikipedia Data:   9%|▉         | 106/1126 [02:14<22:31,  1.33s/it]

Wikipedia Data saved: ./artist_wiki_pages/Constant_Permeke.json

Fetching Wikipedia Data:  10%|▉         | 107/1126 [02:16<23:47,  1.40s/it]

Η σελίδα 'Horska Alla' δεν βρέθηκε.

Fetching Wikipedia Data:  10%|▉         | 108/1126 [02:17<20:11,  1.19s/it]

Wikipedia Data saved: ./artist_wiki_pages/Henri_Michaux.json

Fetching Wikipedia Data:  10%|▉         | 109/1126 [02:19<23:47,  1.40s/it]

Wikipedia Data saved: ./artist_wiki_pages/John_Brack.json

Fetching Wikipedia Data:  10%|▉         | 110/1126 [02:20<22:07,  1.31s/it]

Wikipedia Data saved: ./artist_wiki_pages/Leon_Underwood.json

Fetching Wikipedia Data:  10%|▉         | 111/1126 [02:22<24:58,  1.48s/it]

Wikipedia Data saved: ./artist_wiki_pages/Maria_Helena_Vieira_da_Silva.json

Fetching Wikipedia Data:  10%|▉         | 112/1126 [02:23<22:53,  1.35s/it]

Wikipedia Data saved: ./artist_wiki_pages/Philip_Guston.json

Fetching Wikipedia Data:  10%|█         | 113/1126 [02:24<21:45,  1.29s/it]

Η σελίδα 'Elena Bontea' δεν βρέθηκε.

Fetching Wikipedia Data:  10%|█         | 114/1126 [02:24<18:46,  1.11s/it]

Wikipedia Data saved: ./artist_wiki_pages/Arno_Breker.json

Fetching Wikipedia Data:  10%|█         | 115/1126 [02:26<18:37,  1.11s/it]

Wikipedia Data saved: ./artist_wiki_pages/Ivan_Marchuk.json

Fetching Wikipedia Data:  10%|█         | 116/1126 [02:27<22:30,  1.34s/it]

Wikipedia Data saved: ./artist_wiki_pages/Paula_Modersohn-Becker.json

Fetching Wikipedia Data:  10%|█         | 117/1126 [02:29<21:33,  1.28s/it]

Wikipedia Data saved: ./artist_wiki_pages/Princess_Fahrelnissa_Zeid.json

Fetching Wikipedia Data:  10%|█         | 118/1126 [02:30<20:25,  1.22s/it]

Wikipedia Data saved: ./artist_wiki_pages/Max_Pechstein.json

Fetching Wikipedia Data:  11%|█         | 119/1126 [02:32<24:06,  1.44s/it]

Wikipedia Data saved: ./artist_wiki_pages/James_Brooks_(painter).json

Fetching Wikipedia Data:  11%|█         | 120/1126 [02:33<25:05,  1.50s/it]

Η σελίδα 'Clerici Fabrizio' δεν βρέθηκε.

Fetching Wikipedia Data:  11%|█         | 121/1126 [02:34<21:01,  1.26s/it]

Η σελίδα 'Jean-Claude Silbermann' δεν βρέθηκε.

Fetching Wikipedia Data:  11%|█         | 122/1126 [02:35<18:13,  1.09s/it]

Wikipedia Data saved: ./artist_wiki_pages/Gunther_Gerzso.json

Fetching Wikipedia Data:  11%|█         | 123/1126 [02:36<21:08,  1.26s/it]

Η σελίδα 'Bahtiar' δεν βρέθηκε.

Fetching Wikipedia Data:  11%|█         | 124/1126 [02:37<18:18,  1.10s/it]

Wikipedia Data saved: ./artist_wiki_pages/Philippe_Halsman.json

Fetching Wikipedia Data:  11%|█         | 125/1126 [02:38<18:07,  1.09s/it]

Wikipedia Data saved: ./artist_wiki_pages/Kay_Sage.json

Fetching Wikipedia Data:  11%|█         | 126/1126 [02:39<18:25,  1.11s/it]

Η σελίδα 'Lacombe Eric' δεν βρέθηκε.

Fetching Wikipedia Data:  11%|█▏        | 127/1126 [02:40<16:23,  1.02it/s]

Wikipedia Data saved: ./artist_wiki_pages/David_Lynch#Reviving_Twin_Peaks:_2014–present.json

Fetching Wikipedia Data:  11%|█▏        | 128/1126 [02:41<18:13,  1.10s/it]

Wikipedia Data saved: ./artist_wiki_pages/Enrico_Donati.json

Fetching Wikipedia Data:  11%|█▏        | 129/1126 [02:42<17:59,  1.08s/it]

Η σελίδα 'Dang Dinh Nguyen' δεν βρέθηκε.

Fetching Wikipedia Data:  12%|█▏        | 130/1126 [02:43<16:07,  1.03it/s]

Wikipedia Data saved: ./artist_wiki_pages/Maddox.json

Fetching Wikipedia Data:  12%|█▏        | 131/1126 [02:44<16:41,  1.01s/it]

Η σελίδα 'Kostov Krasimir' δεν βρέθηκε.

Fetching Wikipedia Data:  12%|█▏        | 132/1126 [02:45<15:06,  1.10it/s]

Wikipedia Data saved: ./artist_wiki_pages/Man_Ray.json

Fetching Wikipedia Data:  12%|█▏        | 133/1126 [02:46<16:27,  1.01it/s]

Η σελίδα 'Zademack Siegfried' δεν βρέθηκε.

Fetching Wikipedia Data:  12%|█▏        | 134/1126 [02:47<14:57,  1.10it/s]

Η σελίδα 'Jacques Le Maréchal' δεν βρέθηκε.

Fetching Wikipedia Data:  12%|█▏        | 135/1126 [02:47<13:53,  1.19it/s]

Η σελίδα 'Solis Carlos' δεν βρέθηκε.

Fetching Wikipedia Data:  12%|█▏        | 136/1126 [02:48<13:10,  1.25it/s]

Wikipedia Data saved: ./artist_wiki_pages/Simon_Hantaï.json

Fetching Wikipedia Data:  12%|█▏        | 137/1126 [02:49<14:23,  1.15it/s]

Η σελίδα 'Bott Francis' δεν βρέθηκε.

Fetching Wikipedia Data:  12%|█▏        | 138/1126 [02:50<13:30,  1.22it/s]

Wikipedia Data saved: ./artist_wiki_pages/Masson.json

Fetching Wikipedia Data:  12%|█▏        | 139/1126 [02:51<14:37,  1.12it/s]

Η σελίδα 'Massanet Joan' δεν βρέθηκε.

Fetching Wikipedia Data:  12%|█▏        | 140/1126 [02:52<13:38,  1.21it/s]

Η σελίδα 'Roswell Harvey Lee' δεν βρέθηκε.

Fetching Wikipedia Data:  13%|█▎        | 141/1126 [02:52<12:55,  1.27it/s]

Η σελίδα 'Ates Mahir' δεν βρέθηκε.

Fetching Wikipedia Data:  13%|█▎        | 142/1126 [02:53<12:30,  1.31it/s]

Η σελίδα 'Ghita Iustinian' δεν βρέθηκε.

Fetching Wikipedia Data:  13%|█▎        | 143/1126 [02:54<12:09,  1.35it/s]

Wikipedia Data saved: ./artist_wiki_pages/Arnulf_Rainer.json

Fetching Wikipedia Data:  13%|█▎        | 144/1126 [02:55<16:57,  1.04s/it]

Η σελίδα 'Huynh Duy' δεν βρέθηκε.

Fetching Wikipedia Data:  13%|█▎        | 145/1126 [02:56<15:16,  1.07it/s]

Η σελίδα 'Laviana Borisov Victor' δεν βρέθηκε.

Fetching Wikipedia Data:  13%|█▎        | 146/1126 [02:57<14:04,  1.16it/s]

Wikipedia Data saved: ./artist_wiki_pages/Zdzislaw_Beksinski.json

Fetching Wikipedia Data:  13%|█▎        | 147/1126 [02:58<15:15,  1.07it/s]

Η σελίδα 'Sven Jonson' δεν βρέθηκε.

Fetching Wikipedia Data:  13%|█▎        | 148/1126 [02:59<14:14,  1.14it/s]

Wikipedia Data saved: ./artist_wiki_pages/Freddie.json

Fetching Wikipedia Data:  13%|█▎        | 149/1126 [03:00<15:04,  1.08it/s]

Wikipedia Data saved: ./artist_wiki_pages/Lubo_Kristek.json

Fetching Wikipedia Data:  13%|█▎        | 150/1126 [03:03<26:26,  1.63s/it]

Wikipedia Data saved: ./artist_wiki_pages/Konstantin_Vasilyev.json

Fetching Wikipedia Data:  13%|█▎        | 151/1126 [03:05<26:54,  1.66s/it]

Η σελίδα 'Grie George' δεν βρέθηκε.

Fetching Wikipedia Data:  13%|█▎        | 152/1126 [03:05<22:12,  1.37s/it]

Wikipedia Data saved: ./artist_wiki_pages/Gherasim_Luca.json

Fetching Wikipedia Data:  14%|█▎        | 153/1126 [03:06<20:48,  1.28s/it]

Wikipedia Data saved: ./artist_wiki_pages/Leonora_Carrington.json

Fetching Wikipedia Data:  14%|█▎        | 154/1126 [03:08<20:27,  1.26s/it]

Wikipedia Data saved: ./artist_wiki_pages/Chavarria.json

Fetching Wikipedia Data:  14%|█▍        | 155/1126 [03:09<19:38,  1.21s/it]

Η σελίδα 'Mazuru Didier' δεν βρέθηκε.

Fetching Wikipedia Data:  14%|█▍        | 156/1126 [03:09<17:09,  1.06s/it]

Η σελίδα 'Suaznabar Marcelo' δεν βρέθηκε.

Fetching Wikipedia Data:  14%|█▍        | 157/1126 [03:10<15:26,  1.05it/s]

Η σελίδα 'Fink Vincent' δεν βρέθηκε.

Fetching Wikipedia Data:  14%|█▍        | 158/1126 [03:11<14:12,  1.14it/s]

Wikipedia Data saved: ./artist_wiki_pages/George_Papazov.json

Fetching Wikipedia Data:  14%|█▍        | 159/1126 [03:13<18:24,  1.14s/it]

Wikipedia Data saved: ./artist_wiki_pages/Kansuke_Yamamoto_(Experimental_Artist).json

Fetching Wikipedia Data:  14%|█▍        | 160/1126 [03:14<21:28,  1.33s/it]

Η σελίδα 'Petruziello Sarah' δεν βρέθηκε.

Fetching Wikipedia Data:  14%|█▍        | 161/1126 [03:15<18:23,  1.14s/it]

Η σελίδα 'Hurry Leslie' δεν βρέθηκε.

Fetching Wikipedia Data:  14%|█▍        | 162/1126 [03:16<16:14,  1.01s/it]

Wikipedia Data saved: ./artist_wiki_pages/Cukier.json

Fetching Wikipedia Data:  14%|█▍        | 163/1126 [03:17<16:35,  1.03s/it]

Wikipedia Data saved: ./artist_wiki_pages/Grace_Pailthorpe.json

Fetching Wikipedia Data:  15%|█▍        | 164/1126 [03:19<20:04,  1.25s/it]

Wikipedia Data saved: ./artist_wiki_pages/Nina_Petrovna_Valetova.json

Fetching Wikipedia Data:  15%|█▍        | 165/1126 [03:20<19:17,  1.20s/it]

Η σελίδα 'Snead Stella' δεν βρέθηκε.

Fetching Wikipedia Data:  15%|█▍        | 166/1126 [03:20<16:55,  1.06s/it]

Η σελίδα 'Proksch Peter' δεν βρέθηκε.

Fetching Wikipedia Data:  15%|█▍        | 167/1126 [03:21<15:13,  1.05it/s]

Η σελίδα 'Cusimano Joseph' δεν βρέθηκε.

Fetching Wikipedia Data:  15%|█▍        | 168/1126 [03:22<13:57,  1.14it/s]

Wikipedia Data saved: ./artist_wiki_pages/Antonio_Berni.json

Fetching Wikipedia Data:  15%|█▌        | 169/1126 [03:23<14:49,  1.08it/s]

Η σελίδα 'Gaiger Weinmuller' δεν βρέθηκε.

Fetching Wikipedia Data:  15%|█▌        | 170/1126 [03:24<13:43,  1.16it/s]

Wikipedia Data saved: ./artist_wiki_pages/Mário_Cesariny_de_Vasconcelos.json

Fetching Wikipedia Data:  15%|█▌        | 171/1126 [03:25<16:50,  1.06s/it]

Wikipedia Data saved: ./artist_wiki_pages/Louise_Bourgeois.json

Fetching Wikipedia Data:  15%|█▌        | 172/1126 [03:26<17:17,  1.09s/it]

Η σελίδα 'Naumovski Vangel' δεν βρέθηκε.

Fetching Wikipedia Data:  15%|█▌        | 173/1126 [03:27<15:25,  1.03it/s]

Η σελίδα 'Burliuk David' δεν βρέθηκε.

Fetching Wikipedia Data:  15%|█▌        | 174/1126 [03:28<14:07,  1.12it/s]

Wikipedia Data saved: ./artist_wiki_pages/Jacques_Hérold.json

Fetching Wikipedia Data:  16%|█▌        | 175/1126 [03:30<19:35,  1.24s/it]

Η σελίδα 'Capuletti Manuel Jose' δεν βρέθηκε.

Fetching Wikipedia Data:  16%|█▌        | 176/1126 [03:30<17:00,  1.07s/it]

Η σελίδα 'Schleinzer Mario' δεν βρέθηκε.

Fetching Wikipedia Data:  16%|█▌        | 177/1126 [03:31<15:10,  1.04it/s]

Wikipedia Data saved: ./artist_wiki_pages/Gene_Davis_(painter).json

Fetching Wikipedia Data:  16%|█▌        | 178/1126 [03:33<19:14,  1.22s/it]

Wikipedia Data saved: ./artist_wiki_pages/Edward_Weston.json

Fetching Wikipedia Data:  16%|█▌        | 179/1126 [03:39<40:08,  2.54s/it]

Wikipedia Data saved: ./artist_wiki_pages/Penrose.json

Fetching Wikipedia Data:  16%|█▌        | 180/1126 [03:40<33:12,  2.11s/it]

Η σελίδα 'Edonna Nome' δεν βρέθηκε.

Fetching Wikipedia Data:  16%|█▌        | 181/1126 [03:40<26:31,  1.68s/it]

Wikipedia Data saved: ./artist_wiki_pages/Fernand_Léger.json

Fetching Wikipedia Data:  16%|█▌        | 182/1126 [03:43<28:38,  1.82s/it]

Wikipedia Data saved: ./artist_wiki_pages/Luigi_Serafini_(artist).json

Fetching Wikipedia Data:  16%|█▋        | 183/1126 [03:44<25:01,  1.59s/it]

Η σελίδα 'Jaroslav Serpan' δεν βρέθηκε.

Fetching Wikipedia Data:  16%|█▋        | 184/1126 [03:44<20:49,  1.33s/it]

Η σελίδα 'Vartanov Vigen' δεν βρέθηκε.

Fetching Wikipedia Data:  16%|█▋        | 185/1126 [03:45<17:50,  1.14s/it]

Wikipedia Data saved: ./artist_wiki_pages/Reuben_Mednikoff.json

Fetching Wikipedia Data:  17%|█▋        | 186/1126 [03:46<17:33,  1.12s/it]

Η σελίδα 'Banting John' δεν βρέθηκε.

Fetching Wikipedia Data:  17%|█▋        | 187/1126 [03:47<15:36,  1.00it/s]

Η σελίδα 'Graverol' δεν βρέθηκε.

Fetching Wikipedia Data:  17%|█▋        | 188/1126 [03:47<14:14,  1.10it/s]

Wikipedia Data saved: ./artist_wiki_pages/Leonid_Šejka.json

Fetching Wikipedia Data:  17%|█▋        | 189/1126 [03:49<14:58,  1.04it/s]

Η σελίδα 'Demant Rozi' δεν βρέθηκε.

Fetching Wikipedia Data:  17%|█▋        | 190/1126 [03:49<13:42,  1.14it/s]

Η σελίδα 'Esau Gabriele' δεν βρέθηκε.

Fetching Wikipedia Data:  17%|█▋        | 191/1126 [03:50<12:49,  1.21it/s]

Η σελίδα 'Foppiani Gustavo' δεν βρέθηκε.

Fetching Wikipedia Data:  17%|█▋        | 192/1126 [03:51<12:11,  1.28it/s]

Wikipedia Data saved: ./artist_wiki_pages/Johfra.json

Fetching Wikipedia Data:  17%|█▋        | 193/1126 [03:52<15:58,  1.03s/it]

Η σελίδα 'Bruno Canova' δεν βρέθηκε.

Fetching Wikipedia Data:  17%|█▋        | 194/1126 [03:53<14:25,  1.08it/s]

Wikipedia Data saved: ./artist_wiki_pages/Karras.json

Fetching Wikipedia Data:  17%|█▋        | 195/1126 [03:54<15:02,  1.03it/s]

Wikipedia Data saved: ./artist_wiki_pages/Wols.json

Fetching Wikipedia Data:  17%|█▋        | 196/1126 [03:56<19:03,  1.23s/it]

Wikipedia Data saved: ./artist_wiki_pages/Victo_Ngai.json

Fetching Wikipedia Data:  17%|█▋        | 197/1126 [03:57<18:12,  1.18s/it]

Wikipedia Data saved: ./artist_wiki_pages/Roosevelt.json

Fetching Wikipedia Data:  18%|█▊        | 198/1126 [03:58<17:47,  1.15s/it]

Η σελίδα 'Dang Frits' δεν βρέθηκε.

Fetching Wikipedia Data:  18%|█▊        | 199/1126 [03:59<15:43,  1.02s/it]

Wikipedia Data saved: ./artist_wiki_pages/Frederick_Sommer.json

Fetching Wikipedia Data:  18%|█▊        | 200/1126 [04:00<15:55,  1.03s/it]

Η σελίδα 'Iván Tovar' δεν βρέθηκε.

Fetching Wikipedia Data:  18%|█▊        | 201/1126 [04:00<14:24,  1.07it/s]

Η σελίδα 'Strupulis Guntis' δεν βρέθηκε.

Fetching Wikipedia Data:  18%|█▊        | 202/1126 [04:01<13:18,  1.16it/s]

Η σελίδα 'Whitlam David' δεν βρέθηκε.

Fetching Wikipedia Data:  18%|█▊        | 203/1126 [04:02<12:30,  1.23it/s]

Wikipedia Data saved: ./artist_wiki_pages/Aydin_Aghdashloo.json

Fetching Wikipedia Data:  18%|█▊        | 204/1126 [04:04<18:07,  1.18s/it]

Η σελίδα 'Gibb Stephen' δεν βρέθηκε.

Fetching Wikipedia Data:  18%|█▊        | 205/1126 [04:05<15:54,  1.04s/it]

Wikipedia Data saved: ./artist_wiki_pages/Carlos_Mérida.json

Fetching Wikipedia Data:  18%|█▊        | 206/1126 [04:06<16:25,  1.07s/it]

Η σελίδα 'Kortan Frank' δεν βρέθηκε.

Fetching Wikipedia Data:  18%|█▊        | 207/1126 [04:06<14:41,  1.04it/s]

Wikipedia Data saved: ./artist_wiki_pages/Brauner.json

Fetching Wikipedia Data:  18%|█▊        | 208/1126 [04:08<15:10,  1.01it/s]

Η σελίδα 'Bogacki Mariola' δεν βρέθηκε.

Fetching Wikipedia Data:  19%|█▊        | 209/1126 [04:08<13:49,  1.11it/s]

Η σελίδα 'Rosa Dela' δεν βρέθηκε.

Fetching Wikipedia Data:  19%|█▊        | 210/1126 [04:09<12:52,  1.19it/s]

Wikipedia Data saved: ./artist_wiki_pages/Adolph_Gottlieb.json

Fetching Wikipedia Data:  19%|█▊        | 211/1126 [04:10<14:14,  1.07it/s]

Η σελίδα 'Sugawara Yu' δεν βρέθηκε.

Fetching Wikipedia Data:  19%|█▉        | 212/1126 [04:11<13:09,  1.16it/s]

Η σελίδα 'Cattiaux Louis' δεν βρέθηκε.

Fetching Wikipedia Data:  19%|█▉        | 213/1126 [04:11<12:24,  1.23it/s]

Η σελίδα 'Kochabua Prateep' δεν βρέθηκε.

Fetching Wikipedia Data:  19%|█▉        | 214/1126 [04:12<11:51,  1.28it/s]

Η σελίδα 'Velimanovic Zoran' δεν βρέθηκε.

Fetching Wikipedia Data:  19%|█▉        | 215/1126 [04:13<11:32,  1.32it/s]

Η σελίδα 'Stock Ursula' δεν βρέθηκε.

Fetching Wikipedia Data:  19%|█▉        | 216/1126 [04:14<11:12,  1.35it/s]

Wikipedia Data saved: ./artist_wiki_pages/André_Masson.json

Fetching Wikipedia Data:  19%|█▉        | 217/1126 [04:15<16:36,  1.10s/it]

Wikipedia Data saved: ./artist_wiki_pages/Dora_Maar.json

Fetching Wikipedia Data:  19%|█▉        | 218/1126 [04:18<21:28,  1.42s/it]

Wikipedia Data saved: ./artist_wiki_pages/Trouille.json

Fetching Wikipedia Data:  19%|█▉        | 219/1126 [04:19<20:00,  1.32s/it]

Wikipedia Data saved: ./artist_wiki_pages/Tichenor.json

Fetching Wikipedia Data:  20%|█▉        | 220/1126 [04:20<18:46,  1.24s/it]

Wikipedia Data saved: ./artist_wiki_pages/Brion_Gysin.json

Fetching Wikipedia Data:  20%|█▉        | 221/1126 [04:22<21:20,  1.41s/it]

Wikipedia Data saved: ./artist_wiki_pages/Ulrich.json

Fetching Wikipedia Data:  20%|█▉        | 222/1126 [04:23<19:51,  1.32s/it]

Wikipedia Data saved: ./artist_wiki_pages/Modest_Cuixart.json

Fetching Wikipedia Data:  20%|█▉        | 223/1126 [04:24<18:44,  1.25s/it]

Wikipedia Data saved: ./artist_wiki_pages/Pierre_Roy_(painter).json

Fetching Wikipedia Data:  20%|█▉        | 224/1126 [04:25<17:59,  1.20s/it]

Wikipedia Data saved: ./artist_wiki_pages/Leonor_Fini.json

Fetching Wikipedia Data:  20%|█▉        | 225/1126 [04:27<21:32,  1.43s/it]

Wikipedia Data saved: ./artist_wiki_pages/Seligmann.json

Fetching Wikipedia Data:  20%|██        | 226/1126 [04:28<19:49,  1.32s/it]

Wikipedia Data saved: ./artist_wiki_pages/António_Areal.json

Fetching Wikipedia Data:  20%|██        | 227/1126 [04:29<18:38,  1.24s/it]

Wikipedia Data saved: ./artist_wiki_pages/Francisco_Toledo.json

Fetching Wikipedia Data:  20%|██        | 228/1126 [04:30<17:46,  1.19s/it]

Wikipedia Data saved: ./artist_wiki_pages/Drago.json

Fetching Wikipedia Data:  20%|██        | 229/1126 [04:31<17:13,  1.15s/it]

Wikipedia Data saved: ./artist_wiki_pages/Dominguez.json

Fetching Wikipedia Data:  20%|██        | 230/1126 [04:32<16:50,  1.13s/it]

Η σελίδα 'Galant Jose' δεν βρέθηκε.

Fetching Wikipedia Data:  21%|██        | 231/1126 [04:33<14:52,  1.00it/s]

Η σελίδα 'Petelin Valery' δεν βρέθηκε.

Fetching Wikipedia Data:  21%|██        | 232/1126 [04:34<13:34,  1.10it/s]

Wikipedia Data saved: ./artist_wiki_pages/Agustín_Cárdenas.json

Fetching Wikipedia Data:  21%|██        | 233/1126 [04:35<14:21,  1.04it/s]

Wikipedia Data saved: ./artist_wiki_pages/Hannah_Höch.json

Fetching Wikipedia Data:  21%|██        | 234/1126 [04:37<19:31,  1.31s/it]

Wikipedia Data saved: ./artist_wiki_pages/Conroy_Maddox.json

Fetching Wikipedia Data:  21%|██        | 235/1126 [04:39<21:44,  1.46s/it]

Η σελίδα 'Criste Mihai' δεν βρέθηκε.

Fetching Wikipedia Data:  21%|██        | 236/1126 [04:39<18:19,  1.24s/it]

Η σελίδα 'Szenczi Brigitte' δεν βρέθηκε.

Fetching Wikipedia Data:  21%|██        | 237/1126 [04:40<15:59,  1.08s/it]

Η σελίδα 'Damme Van' δεν βρέθηκε.

Fetching Wikipedia Data:  21%|██        | 238/1126 [04:41<14:16,  1.04it/s]

Η σελίδα 'Marseille Of Game The' δεν βρέθηκε.

Fetching Wikipedia Data:  21%|██        | 239/1126 [04:42<13:48,  1.07it/s]

Wikipedia Data saved: ./artist_wiki_pages/Planells.json

Fetching Wikipedia Data:  21%|██▏       | 240/1126 [04:43<14:30,  1.02it/s]

Wikipedia Data saved: ./artist_wiki_pages/Herold.json

Fetching Wikipedia Data:  21%|██▏       | 241/1126 [04:44<14:47,  1.00s/it]

Wikipedia Data saved: ./artist_wiki_pages/Richard_Oelze.json

Fetching Wikipedia Data:  21%|██▏       | 242/1126 [04:45<15:08,  1.03s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jorge_Castillo_(artist).json

Fetching Wikipedia Data:  22%|██▏       | 243/1126 [04:46<15:15,  1.04s/it]

Η σελίδα 'Morski Igor' δεν βρέθηκε.

Fetching Wikipedia Data:  22%|██▏       | 244/1126 [04:47<13:42,  1.07it/s]

Wikipedia Data saved: ./artist_wiki_pages/Fornasetti.json

Fetching Wikipedia Data:  22%|██▏       | 245/1126 [04:48<16:16,  1.11s/it]

Wikipedia Data saved: ./artist_wiki_pages/Joseph_Cornell.json

Fetching Wikipedia Data:  22%|██▏       | 246/1126 [04:49<16:30,  1.13s/it]

Wikipedia Data saved: ./artist_wiki_pages/Schorr.json

Fetching Wikipedia Data:  22%|██▏       | 247/1126 [04:50<16:18,  1.11s/it]

Wikipedia Data saved: ./artist_wiki_pages/Šarūnas_Sauka.json

Fetching Wikipedia Data:  22%|██▏       | 248/1126 [04:52<19:05,  1.31s/it]

Wikipedia Data saved: ./artist_wiki_pages/Brassaï.json

Fetching Wikipedia Data:  22%|██▏       | 249/1126 [04:53<18:04,  1.24s/it]

Η σελίδα 'Hoffer Dominique' δεν βρέθηκε.

Fetching Wikipedia Data:  22%|██▏       | 250/1126 [04:54<15:44,  1.08s/it]

Η σελίδα 'Holz Werner' δεν βρέθηκε.

Fetching Wikipedia Data:  22%|██▏       | 251/1126 [04:55<14:02,  1.04it/s]

Wikipedia Data saved: ./artist_wiki_pages/Jagdish_Swaminathan.json

Fetching Wikipedia Data:  22%|██▏       | 252/1126 [04:56<17:14,  1.18s/it]

Η σελίδα 'Felly Nicolas' δεν βρέθηκε.

Fetching Wikipedia Data:  22%|██▏       | 253/1126 [04:57<15:09,  1.04s/it]

Η σελίδα 'René Bértholo' δεν βρέθηκε.

Fetching Wikipedia Data:  23%|██▎       | 254/1126 [04:58<13:36,  1.07it/s]

Η σελίδα 'Goetz Henri' δεν βρέθηκε.

Fetching Wikipedia Data:  23%|██▎       | 255/1126 [04:58<12:31,  1.16it/s]

Η σελίδα 'Gold Dave' δεν βρέθηκε.

Fetching Wikipedia Data:  23%|██▎       | 256/1126 [04:59<11:47,  1.23it/s]

Η σελίδα 'Greenwood John' δεν βρέθηκε.

Fetching Wikipedia Data:  23%|██▎       | 257/1126 [05:00<11:17,  1.28it/s]

Wikipedia Data saved: ./artist_wiki_pages/Domenico_Gnoli_(painter).json

Fetching Wikipedia Data:  23%|██▎       | 258/1126 [05:01<12:32,  1.15it/s]

Wikipedia Data saved: ./artist_wiki_pages/Albín_Brunovský.json

Fetching Wikipedia Data:  23%|██▎       | 259/1126 [05:02<13:32,  1.07it/s]

Wikipedia Data saved: ./artist_wiki_pages/Brett_Whiteley.json

Fetching Wikipedia Data:  23%|██▎       | 260/1126 [05:03<14:44,  1.02s/it]

Wikipedia Data saved: ./artist_wiki_pages/Ibrahim_el-Salahi.json

Fetching Wikipedia Data:  23%|██▎       | 261/1126 [05:05<19:12,  1.33s/it]

Η σελίδα 'Sorin Dumitrescu' δεν βρέθηκε.

Fetching Wikipedia Data:  23%|██▎       | 262/1126 [05:06<16:31,  1.15s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jean_Hugo.json

Fetching Wikipedia Data:  23%|██▎       | 263/1126 [05:07<16:23,  1.14s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jean_Benoît.json

Fetching Wikipedia Data:  23%|██▎       | 264/1126 [05:09<18:01,  1.25s/it]

Η σελίδα 'Sauber Masiero Dino' δεν βρέθηκε.

Fetching Wikipedia Data:  24%|██▎       | 265/1126 [05:09<15:35,  1.09s/it]

Η σελίδα 'Caram Marcel' δεν βρέθηκε.

Fetching Wikipedia Data:  24%|██▎       | 266/1126 [05:10<13:58,  1.03it/s]

Η σελίδα 'Reigl Judit' δεν βρέθηκε.

Fetching Wikipedia Data:  24%|██▎       | 267/1126 [05:11<12:47,  1.12it/s]

Wikipedia Data saved: ./artist_wiki_pages/Niki_de_Saint_Phalle.json

Fetching Wikipedia Data:  24%|██▍       | 268/1126 [05:12<14:21,  1.00s/it]

Η σελίδα 'Guanlao Jeffrey' δεν βρέθηκε.

Fetching Wikipedia Data:  24%|██▍       | 269/1126 [05:13<13:01,  1.10it/s]

Wikipedia Data saved: ./artist_wiki_pages/Kit_Williams.json

Fetching Wikipedia Data:  24%|██▍       | 270/1126 [05:15<17:04,  1.20s/it]

Wikipedia Data saved: ./artist_wiki_pages/Abercrombie.json

Fetching Wikipedia Data:  24%|██▍       | 271/1126 [05:16<16:35,  1.16s/it]

Η σελίδα 'Sanctis De Fabio' δεν βρέθηκε.

Fetching Wikipedia Data:  24%|██▍       | 272/1126 [05:16<14:33,  1.02s/it]

Wikipedia Data saved: ./artist_wiki_pages/Agim_Sulaj.json

Fetching Wikipedia Data:  24%|██▍       | 273/1126 [05:17<14:42,  1.03s/it]

Η σελίδα 'Resch Jacques' δεν βρέθηκε.

Fetching Wikipedia Data:  24%|██▍       | 274/1126 [05:18<13:14,  1.07it/s]

Η σελίδα 'Riccardi Fabrizio' δεν βρέθηκε.

Fetching Wikipedia Data:  24%|██▍       | 275/1126 [05:19<12:13,  1.16it/s]

Wikipedia Data saved: ./artist_wiki_pages/Roberto_Aizenberg.json

Fetching Wikipedia Data:  25%|██▍       | 276/1126 [05:20<15:05,  1.07s/it]

Wikipedia Data saved: ./artist_wiki_pages/Octavio_Ocampo.json

Fetching Wikipedia Data:  25%|██▍       | 277/1126 [05:21<15:04,  1.07s/it]

Η σελίδα 'Chirico De' δεν βρέθηκε.

Fetching Wikipedia Data:  25%|██▍       | 278/1126 [05:22<13:29,  1.05it/s]

Wikipedia Data saved: ./artist_wiki_pages/Jacqueline_Lamba.json

Fetching Wikipedia Data:  25%|██▍       | 279/1126 [05:24<17:16,  1.22s/it]

Wikipedia Data saved: ./artist_wiki_pages/Valentine_Hugo.json

Fetching Wikipedia Data:  25%|██▍       | 280/1126 [05:25<16:35,  1.18s/it]

Wikipedia Data saved: ./artist_wiki_pages/Dado_(painter).json

Fetching Wikipedia Data:  25%|██▍       | 281/1126 [05:26<16:17,  1.16s/it]

Η σελίδα 'Dzielawski Arkadiusz' δεν βρέθηκε.

Fetching Wikipedia Data:  25%|██▌       | 282/1126 [05:27<14:19,  1.02s/it]

Η σελίδα 'Adrien Dax' δεν βρέθηκε.

Fetching Wikipedia Data:  25%|██▌       | 283/1126 [05:27<12:56,  1.09it/s]

Η σελίδα 'Alvarez Katrin' δεν βρέθηκε.

Fetching Wikipedia Data:  25%|██▌       | 284/1126 [05:28<12:00,  1.17it/s]

Η σελίδα 'Mihai Raceanu' δεν βρέθηκε.

Fetching Wikipedia Data:  25%|██▌       | 285/1126 [05:29<11:18,  1.24it/s]

Η σελίδα 'Meta Agim' δεν βρέθηκε.

Fetching Wikipedia Data:  25%|██▌       | 286/1126 [05:30<10:51,  1.29it/s]

Η σελίδα 'Borodin Aleksandr' δεν βρέθηκε.

Fetching Wikipedia Data:  25%|██▌       | 287/1126 [05:30<10:29,  1.33it/s]

Η σελίδα 'Woestyne De Van Maxime' δεν βρέθηκε.

Fetching Wikipedia Data:  26%|██▌       | 288/1126 [05:31<10:17,  1.36it/s]

Wikipedia Data saved: ./artist_wiki_pages/Wojciech_Siudmak.json

Fetching Wikipedia Data:  26%|██▌       | 289/1126 [05:32<11:40,  1.19it/s]

Wikipedia Data saved: ./artist_wiki_pages/Rimmington.json

Fetching Wikipedia Data:  26%|██▌       | 290/1126 [05:33<12:38,  1.10it/s]

Wikipedia Data saved: ./artist_wiki_pages/Antonio_López_García.json

Fetching Wikipedia Data:  26%|██▌       | 291/1126 [05:34<13:16,  1.05it/s]

Wikipedia Data saved: ./artist_wiki_pages/Michael_Sowa.json

Fetching Wikipedia Data:  26%|██▌       | 292/1126 [05:35<13:41,  1.02it/s]

Η σελίδα 'Spiro Georges' δεν βρέθηκε.

Fetching Wikipedia Data:  26%|██▌       | 293/1126 [05:36<12:26,  1.12it/s]

Wikipedia Data saved: ./artist_wiki_pages/Marion_Adnams.json

Fetching Wikipedia Data:  26%|██▌       | 294/1126 [05:38<15:28,  1.12s/it]

Η σελίδα 'Olbinski' δεν βρέθηκε.

Fetching Wikipedia Data:  26%|██▌       | 295/1126 [05:38<13:44,  1.01it/s]

Wikipedia Data saved: ./artist_wiki_pages/Josef_Šíma.json

Fetching Wikipedia Data:  26%|██▋       | 296/1126 [05:39<14:03,  1.02s/it]

Η σελίδα 'Bridgwater Emmy' δεν βρέθηκε.

Fetching Wikipedia Data:  26%|██▋       | 297/1126 [05:40<12:44,  1.08it/s]

Η σελίδα 'Masskholder Erik' δεν βρέθηκε.

Fetching Wikipedia Data:  26%|██▋       | 298/1126 [05:41<11:50,  1.17it/s]

Wikipedia Data saved: ./artist_wiki_pages/Grasse.json

Fetching Wikipedia Data:  27%|██▋       | 299/1126 [05:43<18:22,  1.33s/it]

Wikipedia Data saved: ./artist_wiki_pages/Leonid_Šejka.json

Fetching Wikipedia Data:  27%|██▋       | 300/1126 [05:44<17:22,  1.26s/it]

Wikipedia Data saved: ./artist_wiki_pages/Wolfgang_Paalen.json

Fetching Wikipedia Data:  27%|██▋       | 301/1126 [05:46<21:00,  1.53s/it]

Wikipedia Data saved: ./artist_wiki_pages/Marcelino_Vespeira.json

Fetching Wikipedia Data:  27%|██▋       | 302/1126 [05:47<19:08,  1.39s/it]

Η σελίδα 'Caruso Santiago' δεν βρέθηκε.

Fetching Wikipedia Data:  27%|██▋       | 303/1126 [05:48<16:14,  1.18s/it]

Η σελίδα 'Frolakov Sergei' δεν βρέθηκε.

Fetching Wikipedia Data:  27%|██▋       | 304/1126 [05:49<14:15,  1.04s/it]

Η σελίδα 'Sheeky' δεν βρέθηκε.

Fetching Wikipedia Data:  27%|██▋       | 305/1126 [05:50<12:53,  1.06it/s]

Wikipedia Data saved: ./artist_wiki_pages/Georges_Ribemont-Dessaignes.json

Fetching Wikipedia Data:  27%|██▋       | 306/1126 [05:51<13:27,  1.02it/s]

Wikipedia Data saved: ./artist_wiki_pages/Clarence_Holbrook_Carter.json

Fetching Wikipedia Data:  27%|██▋       | 307/1126 [05:52<13:48,  1.01s/it]

Η σελίδα 'Akyavas Erol' δεν βρέθηκε.

Fetching Wikipedia Data:  27%|██▋       | 308/1126 [05:52<12:28,  1.09it/s]

Wikipedia Data saved: ./artist_wiki_pages/Enzo_Cucchi.json

Fetching Wikipedia Data:  27%|██▋       | 309/1126 [05:53<12:59,  1.05it/s]

Wikipedia Data saved: ./artist_wiki_pages/Alejandro_Obregón.json

Fetching Wikipedia Data:  28%|██▊       | 310/1126 [05:56<17:34,  1.29s/it]

Η σελίδα 'Lamolla Antoni' δεν βρέθηκε.

Fetching Wikipedia Data:  28%|██▊       | 311/1126 [05:56<15:06,  1.11s/it]

Wikipedia Data saved: ./artist_wiki_pages/Joan_Miró.json

Fetching Wikipedia Data:  28%|██▊       | 312/1126 [05:58<15:46,  1.16s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jimmy_Ernst.json

Fetching Wikipedia Data:  28%|██▊       | 313/1126 [05:59<17:54,  1.32s/it]

Η σελίδα 'Charnine Samy' δεν βρέθηκε.

Fetching Wikipedia Data:  28%|██▊       | 314/1126 [06:00<15:20,  1.13s/it]

Wikipedia Data saved: ./artist_wiki_pages/Sanches.json

Fetching Wikipedia Data:  28%|██▊       | 315/1126 [06:01<15:04,  1.11s/it]

Η σελίδα 'Baes Rachel' δεν βρέθηκε.

Fetching Wikipedia Data:  28%|██▊       | 316/1126 [06:02<13:21,  1.01it/s]

Wikipedia Data saved: ./artist_wiki_pages/Lettl.json

Fetching Wikipedia Data:  28%|██▊       | 317/1126 [06:04<16:50,  1.25s/it]

Η σελίδα 'Plumacher Helmut' δεν βρέθηκε.

Fetching Wikipedia Data:  28%|██▊       | 318/1126 [06:04<14:34,  1.08s/it]

Η σελίδα 'Dumaine Bernard' δεν βρέθηκε.

Fetching Wikipedia Data:  28%|██▊       | 319/1126 [06:05<12:59,  1.04it/s]

Wikipedia Data saved: ./artist_wiki_pages/Tetsuya_Ishida.json

Fetching Wikipedia Data:  28%|██▊       | 320/1126 [06:07<16:19,  1.22s/it]

Η σελίδα 'Alaux Pierre Jean' δεν βρέθηκε.

Fetching Wikipedia Data:  29%|██▊       | 321/1126 [06:07<14:13,  1.06s/it]

Wikipedia Data saved: ./artist_wiki_pages/Francesca_Woodman.json

Fetching Wikipedia Data:  29%|██▊       | 322/1126 [06:09<14:39,  1.09s/it]

Wikipedia Data saved: ./artist_wiki_pages/Tarō_Okamoto.json

Fetching Wikipedia Data:  29%|██▊       | 323/1126 [06:10<14:49,  1.11s/it]

Η σελίδα 'Eksioglu Dogan Gurbuz' δεν βρέθηκε.

Fetching Wikipedia Data:  29%|██▉       | 324/1126 [06:10<13:14,  1.01it/s]

Η σελίδα '1925  Ernst' δεν βρέθηκε.

Fetching Wikipedia Data:  29%|██▉       | 325/1126 [06:11<12:01,  1.11it/s]

Η σελίδα 'Kovelinas Andrius' δεν βρέθηκε.

Fetching Wikipedia Data:  29%|██▉       | 326/1126 [06:12<11:15,  1.18it/s]

Η σελίδα 'Heyder Roland' δεν βρέθηκε.

Fetching Wikipedia Data:  29%|██▉       | 327/1126 [06:13<10:41,  1.24it/s]

Wikipedia Data saved: ./artist_wiki_pages/Endre_Rozsda.json

Fetching Wikipedia Data:  29%|██▉       | 328/1126 [06:14<12:00,  1.11it/s]

Η σελίδα 'Kostuj Leszek' δεν βρέθηκε.

Fetching Wikipedia Data:  29%|██▉       | 329/1126 [06:14<11:10,  1.19it/s]

Wikipedia Data saved: ./artist_wiki_pages/Godinho.json

Fetching Wikipedia Data:  29%|██▉       | 330/1126 [06:16<14:23,  1.09s/it]

Η σελίδα 'Kazimierz Mikulski' δεν βρέθηκε.

Fetching Wikipedia Data:  29%|██▉       | 331/1126 [06:17<13:08,  1.01it/s]

Η σελίδα 'Grzanka Wojciech' δεν βρέθηκε.

Fetching Wikipedia Data:  29%|██▉       | 332/1126 [06:18<11:58,  1.11it/s]

Wikipedia Data saved: ./artist_wiki_pages/Nzante_Spee.json

Fetching Wikipedia Data:  30%|██▉       | 333/1126 [06:19<14:05,  1.07s/it]

Wikipedia Data saved: ./artist_wiki_pages/Raoul_Ubac.json

Fetching Wikipedia Data:  30%|██▉       | 334/1126 [06:20<14:11,  1.07s/it]

Wikipedia Data saved: ./artist_wiki_pages/António_Dacosta.json

Fetching Wikipedia Data:  30%|██▉       | 335/1126 [06:21<14:06,  1.07s/it]

Η σελίδα 'Schute Rene' δεν βρέθηκε.

Fetching Wikipedia Data:  30%|██▉       | 336/1126 [06:22<12:37,  1.04it/s]

Wikipedia Data saved: ./artist_wiki_pages/Mathias_Goeritz.json

Fetching Wikipedia Data:  30%|██▉       | 337/1126 [06:24<16:40,  1.27s/it]

Wikipedia Data saved: ./artist_wiki_pages/Hattori.json

Fetching Wikipedia Data:  30%|███       | 338/1126 [06:25<15:48,  1.20s/it]

Η σελίδα 'Ende Edgar' δεν βρέθηκε.

Fetching Wikipedia Data:  30%|███       | 339/1126 [06:26<13:50,  1.05s/it]

Η σελίδα 'Kazki Interesni' δεν βρέθηκε.

Fetching Wikipedia Data:  30%|███       | 340/1126 [06:26<12:26,  1.05it/s]

Η σελίδα 'Papa Ruxandra' δεν βρέθηκε.

Fetching Wikipedia Data:  30%|███       | 341/1126 [06:27<11:27,  1.14it/s]

Η σελίδα 'Rapp Otto' δεν βρέθηκε.

Fetching Wikipedia Data:  30%|███       | 342/1126 [06:28<10:45,  1.21it/s]

Wikipedia Data saved: ./artist_wiki_pages/Edward_Ruscha.json

Fetching Wikipedia Data:  30%|███       | 343/1126 [06:29<12:04,  1.08it/s]

Wikipedia Data saved: ./artist_wiki_pages/Mati_Klarwein.json

Fetching Wikipedia Data:  31%|███       | 344/1126 [06:31<15:45,  1.21s/it]

Wikipedia Data saved: ./artist_wiki_pages/Paul_Wunderlich.json

Fetching Wikipedia Data:  31%|███       | 345/1126 [06:32<17:08,  1.32s/it]

Wikipedia Data saved: ./artist_wiki_pages/Paul_Păun.json

Fetching Wikipedia Data:  31%|███       | 346/1126 [06:33<16:28,  1.27s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jindřich_Štyrský.json

Fetching Wikipedia Data:  31%|███       | 347/1126 [06:35<17:41,  1.36s/it]

Wikipedia Data saved: ./artist_wiki_pages/Mimi_Parent.json

Fetching Wikipedia Data:  31%|███       | 348/1126 [06:37<19:12,  1.48s/it]

Η σελίδα 'Cheval Michael' δεν βρέθηκε.

Fetching Wikipedia Data:  31%|███       | 349/1126 [06:38<16:09,  1.25s/it]

Wikipedia Data saved: ./artist_wiki_pages/Fuchs.json

Fetching Wikipedia Data:  31%|███       | 350/1126 [06:39<15:26,  1.19s/it]

Η σελίδα 'Joosten Jo' δεν βρέθηκε.

Fetching Wikipedia Data:  31%|███       | 351/1126 [06:39<13:32,  1.05s/it]

Η σελίδα 'Sonnenstern Schroeder' δεν βρέθηκε.

Fetching Wikipedia Data:  31%|███▏      | 352/1126 [06:40<12:08,  1.06it/s]

Wikipedia Data saved: ./artist_wiki_pages/Dorothea_Tanning.json

Fetching Wikipedia Data:  31%|███▏      | 353/1126 [06:42<16:15,  1.26s/it]

Wikipedia Data saved: ./artist_wiki_pages/Desmond_Morris.json

Fetching Wikipedia Data:  31%|███▏      | 354/1126 [06:43<15:34,  1.21s/it]

Η σελίδα 'Katouzian Morteza' δεν βρέθηκε.

Fetching Wikipedia Data:  32%|███▏      | 355/1126 [06:44<13:34,  1.06s/it]

Wikipedia Data saved: ./artist_wiki_pages/Diego_Rivera.json

Fetching Wikipedia Data:  32%|███▏      | 356/1126 [06:45<14:09,  1.10s/it]

Η σελίδα 'Gillet Hughes' δεν βρέθηκε.

Fetching Wikipedia Data:  32%|███▏      | 357/1126 [06:46<12:33,  1.02it/s]

Wikipedia Data saved: ./artist_wiki_pages/Serge_Brignoni.json

Fetching Wikipedia Data:  32%|███▏      | 358/1126 [06:47<12:52,  1.01s/it]

Wikipedia Data saved: ./artist_wiki_pages/Mikuláš_Medek.json

Fetching Wikipedia Data:  32%|███▏      | 359/1126 [06:49<17:14,  1.35s/it]

Wikipedia Data saved: ./artist_wiki_pages/Ali_Akbar_Sadeghi.json

Fetching Wikipedia Data:  32%|███▏      | 360/1126 [06:51<18:26,  1.44s/it]

Η σελίδα 'Eskandarfar Samira' δεν βρέθηκε.

Fetching Wikipedia Data:  32%|███▏      | 361/1126 [06:51<15:32,  1.22s/it]

Wikipedia Data saved: ./artist_wiki_pages/Félix_Labisse.json

Fetching Wikipedia Data:  32%|███▏      | 362/1126 [06:52<14:56,  1.17s/it]

Η σελίδα 'Ruppert Sibylle' δεν βρέθηκε.

Fetching Wikipedia Data:  32%|███▏      | 363/1126 [06:53<13:08,  1.03s/it]

Wikipedia Data saved: ./artist_wiki_pages/Stoyanov.json

Fetching Wikipedia Data:  32%|███▏      | 364/1126 [06:54<13:12,  1.04s/it]

Η σελίδα 'Tamir Ora' δεν βρέθηκε.

Fetching Wikipedia Data:  32%|███▏      | 365/1126 [06:55<11:53,  1.07it/s]

Η σελίδα 'Keese Soren' δεν βρέθηκε.

Fetching Wikipedia Data:  33%|███▎      | 366/1126 [06:55<10:59,  1.15it/s]

Wikipedia Data saved: ./artist_wiki_pages/Guillaume_Cornelis_van_Beverloo.json

Fetching Wikipedia Data:  33%|███▎      | 367/1126 [06:57<11:47,  1.07it/s]

Η σελίδα 'Slattum J' δεν βρέθηκε.

Fetching Wikipedia Data:  33%|███▎      | 368/1126 [06:57<10:53,  1.16it/s]

Wikipedia Data saved: ./artist_wiki_pages/Léon_Arthur_Tutundjian.json

Fetching Wikipedia Data:  33%|███▎      | 369/1126 [06:58<11:40,  1.08it/s]

Η σελίδα 'Moldavsky Vladimir' δεν βρέθηκε.

Fetching Wikipedia Data:  33%|███▎      | 370/1126 [06:59<10:46,  1.17it/s]

Η σελίδα 'Girometti William' δεν βρέθηκε.

Fetching Wikipedia Data:  33%|███▎      | 371/1126 [07:00<10:08,  1.24it/s]

Η σελίδα 'Barreda Andrea' δεν βρέθηκε.

Fetching Wikipedia Data:  33%|███▎      | 372/1126 [07:00<09:43,  1.29it/s]

Wikipedia Data saved: ./artist_wiki_pages/Yves_Tanguy.json

Fetching Wikipedia Data:  33%|███▎      | 373/1126 [07:02<11:18,  1.11it/s]

Wikipedia Data saved: ./artist_wiki_pages/Georges_Hugnet.json

Fetching Wikipedia Data:  33%|███▎      | 374/1126 [07:03<13:50,  1.10s/it]

Η σελίδα 'Margo Boris' δεν βρέθηκε.

Fetching Wikipedia Data:  33%|███▎      | 375/1126 [07:04<12:20,  1.01it/s]

Η σελίδα 'Struck Paul' δεν βρέθηκε.

Fetching Wikipedia Data:  33%|███▎      | 376/1126 [07:05<11:15,  1.11it/s]

Η σελίδα 'Maschka Michael' δεν βρέθηκε.

Fetching Wikipedia Data:  33%|███▎      | 377/1126 [07:05<10:29,  1.19it/s]

Η σελίδα 'Jasnikowski' δεν βρέθηκε.

Fetching Wikipedia Data:  34%|███▎      | 378/1126 [07:06<09:57,  1.25it/s]

Η σελίδα 'Nazabal Jorge' δεν βρέθηκε.

Fetching Wikipedia Data:  34%|███▎      | 379/1126 [07:07<09:35,  1.30it/s]

Η σελίδα 'Zaitsev Nikolai' δεν βρέθηκε.

Fetching Wikipedia Data:  34%|███▎      | 380/1126 [07:07<09:18,  1.34it/s]

Wikipedia Data saved: ./artist_wiki_pages/Luchita_Hurtado.json

Fetching Wikipedia Data:  34%|███▍      | 381/1126 [07:10<14:27,  1.16s/it]

Η σελίδα 'Mellor Oscar' δεν βρέθηκε.

Fetching Wikipedia Data:  34%|███▍      | 382/1126 [07:10<12:44,  1.03s/it]

Wikipedia Data saved: ./artist_wiki_pages/Ponc.json

Fetching Wikipedia Data:  34%|███▍      | 383/1126 [07:11<12:52,  1.04s/it]

Η σελίδα 'Yves Laloy' δεν βρέθηκε.

Fetching Wikipedia Data:  34%|███▍      | 384/1126 [07:12<11:37,  1.06it/s]

Η σελίδα 'Adulyasaraphan' δεν βρέθηκε.

Fetching Wikipedia Data:  34%|███▍      | 385/1126 [07:13<10:41,  1.15it/s]

Η σελίδα 'Prozorovsky Konstantin' δεν βρέθηκε.

Fetching Wikipedia Data:  34%|███▍      | 386/1126 [07:13<10:03,  1.23it/s]

Η σελίδα 'Davis Mike' δεν βρέθηκε.

Fetching Wikipedia Data:  34%|███▍      | 387/1126 [07:14<09:37,  1.28it/s]

Wikipedia Data saved: ./artist_wiki_pages/Vladimir_Kush.json

Fetching Wikipedia Data:  34%|███▍      | 388/1126 [07:15<10:42,  1.15it/s]

Wikipedia Data saved: ./artist_wiki_pages/Marcel_Mariën.json

Fetching Wikipedia Data:  35%|███▍      | 389/1126 [07:17<13:25,  1.09s/it]

Wikipedia Data saved: ./artist_wiki_pages/Dolfi_Trost.json

Fetching Wikipedia Data:  35%|███▍      | 390/1126 [07:18<13:19,  1.09s/it]

Wikipedia Data saved: ./artist_wiki_pages/Picabia.json

Fetching Wikipedia Data:  35%|███▍      | 391/1126 [07:19<13:33,  1.11s/it]

Wikipedia Data saved: ./artist_wiki_pages/Sabin_Bălaşa.json

Fetching Wikipedia Data:  35%|███▍      | 392/1126 [07:21<16:06,  1.32s/it]

Wikipedia Data saved: ./artist_wiki_pages/Esteban_Francés.json

Fetching Wikipedia Data:  35%|███▍      | 393/1126 [07:22<15:14,  1.25s/it]

Wikipedia Data saved: ./artist_wiki_pages/Angel_Planells.json

Fetching Wikipedia Data:  35%|███▍      | 394/1126 [07:23<14:36,  1.20s/it]

Wikipedia Data saved: ./artist_wiki_pages/Julio_Galán.json

Fetching Wikipedia Data:  35%|███▌      | 395/1126 [07:25<16:19,  1.34s/it]

Η σελίδα 'Liberti Carlos Juan' δεν βρέθηκε.

Fetching Wikipedia Data:  35%|███▌      | 396/1126 [07:25<13:56,  1.15s/it]

Η σελίδα 'Padilla Garza Gabriela' δεν βρέθηκε.

Fetching Wikipedia Data:  35%|███▌      | 397/1126 [07:26<12:18,  1.01s/it]

Η σελίδα 'Setowski Tomek' δεν βρέθηκε.

Fetching Wikipedia Data:  35%|███▌      | 398/1126 [07:27<11:07,  1.09it/s]

Η σελίδα 'Kukowski Jaroslaw' δεν βρέθηκε.

Fetching Wikipedia Data:  35%|███▌      | 399/1126 [07:27<10:18,  1.18it/s]

Wikipedia Data saved: ./artist_wiki_pages/Méret_Oppenheim.json

Fetching Wikipedia Data:  36%|███▌      | 400/1126 [07:29<11:23,  1.06it/s]

Η σελίδα 'Labisse' δεν βρέθηκε.

Fetching Wikipedia Data:  36%|███▌      | 401/1126 [07:29<10:33,  1.15it/s]

Wikipedia Data saved: ./artist_wiki_pages/Eileen_Agar.json

Fetching Wikipedia Data:  36%|███▌      | 402/1126 [07:31<13:46,  1.14s/it]

Η σελίδα 'Ray Lisa' δεν βρέθηκε.

Fetching Wikipedia Data:  36%|███▌      | 403/1126 [07:32<12:08,  1.01s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jean_Arp.json

Fetching Wikipedia Data:  36%|███▌      | 404/1126 [07:33<12:57,  1.08s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jacek_Yerka.json

Fetching Wikipedia Data:  36%|███▌      | 405/1126 [07:34<12:58,  1.08s/it]

Wikipedia Data saved: ./artist_wiki_pages/David_Hare_(artist).json

Fetching Wikipedia Data:  36%|███▌      | 406/1126 [07:36<15:04,  1.26s/it]

Wikipedia Data saved: ./artist_wiki_pages/Kenneth_Noland.json

Fetching Wikipedia Data:  36%|███▌      | 407/1126 [07:37<14:19,  1.19s/it]

Η σελίδα 'Kanters Hans' δεν βρέθηκε.

Fetching Wikipedia Data:  36%|███▌      | 408/1126 [07:38<12:30,  1.05s/it]

Η σελίδα 'Lopata Pavlo' δεν βρέθηκε.

Fetching Wikipedia Data:  36%|███▋      | 409/1126 [07:38<11:14,  1.06it/s]

Wikipedia Data saved: ./artist_wiki_pages/Maurice_Tabard.json

Fetching Wikipedia Data:  36%|███▋      | 410/1126 [07:40<13:47,  1.16s/it]

Η σελίδα 'Willems Jo' δεν βρέθηκε.

Fetching Wikipedia Data:  37%|███▋      | 411/1126 [07:41<12:11,  1.02s/it]

Wikipedia Data saved: ./artist_wiki_pages/Samuel_Bak.json

Fetching Wikipedia Data:  37%|███▋      | 412/1126 [07:42<14:59,  1.26s/it]

Wikipedia Data saved: ./artist_wiki_pages/Mario_Prassinos.json

Fetching Wikipedia Data:  37%|███▋      | 413/1126 [07:43<14:10,  1.19s/it]

Η σελίδα 'Privedentsev Gennady' δεν βρέθηκε.

Fetching Wikipedia Data:  37%|███▋      | 414/1126 [07:44<12:25,  1.05s/it]

Η σελίδα 'Malkine Georges' δεν βρέθηκε.

Fetching Wikipedia Data:  37%|███▋      | 415/1126 [07:45<11:10,  1.06it/s]

Η σελίδα 'Lohmuller Gyuri' δεν βρέθηκε.

Fetching Wikipedia Data:  37%|███▋      | 416/1126 [07:46<10:16,  1.15it/s]

Wikipedia Data saved: ./artist_wiki_pages/Conrad_Marca-Relli.json

Fetching Wikipedia Data:  37%|███▋      | 417/1126 [07:47<13:24,  1.13s/it]

Wikipedia Data saved: ./artist_wiki_pages/Óscar_Domínguez.json

Fetching Wikipedia Data:  37%|███▋      | 418/1126 [07:48<13:12,  1.12s/it]

Wikipedia Data saved: ./artist_wiki_pages/Ismael.json

Fetching Wikipedia Data:  37%|███▋      | 419/1126 [07:49<12:58,  1.10s/it]

Wikipedia Data saved: ./artist_wiki_pages/Lorser_Feitelson.json

Fetching Wikipedia Data:  37%|███▋      | 420/1126 [07:51<12:50,  1.09s/it]

Η σελίδα 'Ofstedahl Micah' δεν βρέθηκε.

Fetching Wikipedia Data:  37%|███▋      | 421/1126 [07:51<11:26,  1.03it/s]

Η σελίδα 'Goossens Ben' δεν βρέθηκε.

Fetching Wikipedia Data:  37%|███▋      | 422/1126 [07:52<10:27,  1.12it/s]

Η σελίδα 'Middleton Colin' δεν βρέθηκε.

Fetching Wikipedia Data:  38%|███▊      | 423/1126 [07:53<09:44,  1.20it/s]

Wikipedia Data saved: ./artist_wiki_pages/Tanguy.json

Fetching Wikipedia Data:  38%|███▊      | 424/1126 [07:54<10:32,  1.11it/s]

Η σελίδα 'Erzmoneit Eike' δεν βρέθηκε.

Fetching Wikipedia Data:  38%|███▊      | 425/1126 [07:54<09:53,  1.18it/s]

Η σελίδα 'Borda Adrian' δεν βρέθηκε.

Fetching Wikipedia Data:  38%|███▊      | 426/1126 [07:55<09:22,  1.25it/s]

Η σελίδα 'Tikal Vaclav' δεν βρέθηκε.

Fetching Wikipedia Data:  38%|███▊      | 427/1126 [07:56<08:58,  1.30it/s]

Η σελίδα 'Lamboray Olivier' δεν βρέθηκε.

Fetching Wikipedia Data:  38%|███▊      | 428/1126 [07:56<08:43,  1.33it/s]

Η σελίδα 'Tashkovski Vasko' δεν βρέθηκε.

Fetching Wikipedia Data:  38%|███▊      | 429/1126 [07:57<08:33,  1.36it/s]

Η σελίδα 'Stelmach Marianna' δεν βρέθηκε.

Fetching Wikipedia Data:  38%|███▊      | 430/1126 [07:58<08:24,  1.38it/s]

Η σελίδα 'Gil Nicolescu' δεν βρέθηκε.

Fetching Wikipedia Data:  38%|███▊      | 431/1126 [07:59<08:22,  1.38it/s]

Η σελίδα 'Christensen Jeff' δεν βρέθηκε.

Fetching Wikipedia Data:  38%|███▊      | 432/1126 [07:59<08:15,  1.40it/s]

Η σελίδα 'Guderna Ladislav' δεν βρέθηκε.

Fetching Wikipedia Data:  38%|███▊      | 433/1126 [08:00<08:11,  1.41it/s]

Η σελίδα 'Ruiz Ramos Daniel' δεν βρέθηκε.

Fetching Wikipedia Data:  39%|███▊      | 434/1126 [08:01<08:08,  1.42it/s]

Η σελίδα 'Osipoff Oleg' δεν βρέθηκε.

Fetching Wikipedia Data:  39%|███▊      | 435/1126 [08:01<08:04,  1.43it/s]

Wikipedia Data saved: ./artist_wiki_pages/Roberto_Matta.json

Fetching Wikipedia Data:  39%|███▊      | 436/1126 [08:02<09:25,  1.22it/s]

Η σελίδα 'Bregeda Victor' δεν βρέθηκε.

Fetching Wikipedia Data:  39%|███▉      | 437/1126 [08:03<09:01,  1.27it/s]

Η σελίδα 'Ferez Andrew' δεν βρέθηκε.

Fetching Wikipedia Data:  39%|███▉      | 438/1126 [08:04<08:40,  1.32it/s]

Η σελίδα 'Ogier Michel' δεν βρέθηκε.

Fetching Wikipedia Data:  39%|███▉      | 439/1126 [08:05<08:27,  1.35it/s]

Wikipedia Data saved: ./artist_wiki_pages/Pierre_Molinier.json

Fetching Wikipedia Data:  39%|███▉      | 440/1126 [08:06<12:01,  1.05s/it]

Wikipedia Data saved: ./artist_wiki_pages/Tschumi.json

Fetching Wikipedia Data:  39%|███▉      | 441/1126 [08:07<12:05,  1.06s/it]

Wikipedia Data saved: ./artist_wiki_pages/Thuong.json

Fetching Wikipedia Data:  39%|███▉      | 442/1126 [08:09<12:06,  1.06s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jorge_Camacho_(painter).json

Fetching Wikipedia Data:  39%|███▉      | 443/1126 [08:10<12:04,  1.06s/it]

Wikipedia Data saved: ./artist_wiki_pages/Alexander_Boghossian.json

Fetching Wikipedia Data:  39%|███▉      | 444/1126 [08:11<12:14,  1.08s/it]

Η σελίδα 'Gugel Von Fabius' δεν βρέθηκε.

Fetching Wikipedia Data:  40%|███▉      | 445/1126 [08:11<10:57,  1.04it/s]

Wikipedia Data saved: ./artist_wiki_pages/Dominique_Appia.json

Fetching Wikipedia Data:  40%|███▉      | 446/1126 [08:12<11:17,  1.00it/s]

Η σελίδα 'Gough David' δεν βρέθηκε.

Fetching Wikipedia Data:  40%|███▉      | 447/1126 [08:13<10:15,  1.10it/s]

Wikipedia Data saved: ./artist_wiki_pages/Max_Walter_Svanberg.json

Fetching Wikipedia Data:  40%|███▉      | 448/1126 [08:14<10:44,  1.05it/s]

Wikipedia Data saved: ./artist_wiki_pages/Claude_Cahun.json

Fetching Wikipedia Data:  40%|███▉      | 449/1126 [08:15<11:30,  1.02s/it]

Η σελίδα 'Dankh Daniel' δεν βρέθηκε.

Fetching Wikipedia Data:  40%|███▉      | 450/1126 [08:16<10:23,  1.08it/s]

Wikipedia Data saved: ./artist_wiki_pages/Glenn_Brown_(artist).json

Fetching Wikipedia Data:  40%|████      | 451/1126 [08:17<10:50,  1.04it/s]

Η σελίδα 'Hyvarinen Hannu' δεν βρέθηκε.

Fetching Wikipedia Data:  40%|████      | 452/1126 [08:18<09:55,  1.13it/s]

Wikipedia Data saved: ./artist_wiki_pages/William_Baziotes.json

Fetching Wikipedia Data:  40%|████      | 453/1126 [08:19<12:24,  1.11s/it]

Wikipedia Data saved: ./artist_wiki_pages/Wifredo_Lam.json

Fetching Wikipedia Data:  40%|████      | 454/1126 [08:21<12:33,  1.12s/it]

Wikipedia Data saved: ./artist_wiki_pages/Naumovski.json

Fetching Wikipedia Data:  40%|████      | 455/1126 [08:22<12:23,  1.11s/it]

Wikipedia Data saved: ./artist_wiki_pages/Kay_Nielsen.json

Fetching Wikipedia Data:  40%|████      | 456/1126 [08:23<14:20,  1.28s/it]

Wikipedia Data saved: ./artist_wiki_pages/Frank_Johnston_(artist).json

Fetching Wikipedia Data:  41%|████      | 457/1126 [08:25<15:50,  1.42s/it]

Η σελίδα 'Emmerico Nunes' δεν βρέθηκε.

Fetching Wikipedia Data:  41%|████      | 458/1126 [08:26<13:23,  1.20s/it]

Wikipedia Data saved: ./artist_wiki_pages/Paul_Ranson.json

Fetching Wikipedia Data:  41%|████      | 459/1126 [08:27<12:52,  1.16s/it]

Wikipedia Data saved: ./artist_wiki_pages/Konstantin_Somov.json

Fetching Wikipedia Data:  41%|████      | 460/1126 [08:28<13:03,  1.18s/it]

Wikipedia Data saved: ./artist_wiki_pages/Elisabeth_Sonrel.json

Fetching Wikipedia Data:  41%|████      | 461/1126 [08:29<12:40,  1.14s/it]

Wikipedia Data saved: ./artist_wiki_pages/Charles_Robinson_(illustrator).json

Fetching Wikipedia Data:  41%|████      | 462/1126 [08:33<23:12,  2.10s/it]

Wikipedia Data saved: ./artist_wiki_pages/Thomas_Theodor_Heine.json

Fetching Wikipedia Data:  41%|████      | 463/1126 [08:35<21:35,  1.95s/it]

Wikipedia Data saved: ./artist_wiki_pages/Nicholas_Roerich.json

Fetching Wikipedia Data:  41%|████      | 464/1126 [08:36<18:47,  1.70s/it]

Wikipedia Data saved: ./artist_wiki_pages/Louis_Wain.json

Fetching Wikipedia Data:  41%|████▏     | 465/1126 [08:37<16:46,  1.52s/it]

Wikipedia Data saved: ./artist_wiki_pages/Sergey_Solomko.json

Fetching Wikipedia Data:  41%|████▏     | 466/1126 [08:38<15:15,  1.39s/it]

Wikipedia Data saved: ./artist_wiki_pages/Leonetto_Cappiello.json

Fetching Wikipedia Data:  41%|████▏     | 467/1126 [08:40<15:44,  1.43s/it]

Wikipedia Data saved: ./artist_wiki_pages/Otto_Eckmann.json

Fetching Wikipedia Data:  42%|████▏     | 468/1126 [08:41<14:35,  1.33s/it]

Wikipedia Data saved: ./artist_wiki_pages/Lawren_Harris.json

Fetching Wikipedia Data:  42%|████▏     | 469/1126 [08:44<19:16,  1.76s/it]

Η σελίδα 'Sokolov Oleh' δεν βρέθηκε.

Fetching Wikipedia Data:  42%|████▏     | 470/1126 [08:45<15:48,  1.45s/it]

Wikipedia Data saved: ./artist_wiki_pages/Austin_Osman_Spare.json

Fetching Wikipedia Data:  42%|████▏     | 471/1126 [08:46<14:59,  1.37s/it]

Wikipedia Data saved: ./artist_wiki_pages/Carlos_Schwabe.json

Fetching Wikipedia Data:  42%|████▏     | 472/1126 [08:47<13:57,  1.28s/it]

Wikipedia Data saved: ./artist_wiki_pages/Eero_Järnefelt.json

Fetching Wikipedia Data:  42%|████▏     | 473/1126 [08:48<13:22,  1.23s/it]

Wikipedia Data saved: ./artist_wiki_pages/Koloman_Moser.json

Fetching Wikipedia Data:  42%|████▏     | 474/1126 [08:49<12:48,  1.18s/it]

Wikipedia Data saved: ./artist_wiki_pages/Aubrey_Beardsley.json

Fetching Wikipedia Data:  42%|████▏     | 475/1126 [08:51<17:03,  1.57s/it]

Wikipedia Data saved: ./artist_wiki_pages/Émile_Gallé.json

Fetching Wikipedia Data:  42%|████▏     | 476/1126 [08:53<15:48,  1.46s/it]

Wikipedia Data saved: ./artist_wiki_pages/Louis_Comfort_Tiffany.json

Fetching Wikipedia Data:  42%|████▏     | 477/1126 [08:54<14:51,  1.37s/it]

Wikipedia Data saved: ./artist_wiki_pages/Julio_Romero_de_Torres.json

Fetching Wikipedia Data:  42%|████▏     | 478/1126 [08:56<16:08,  1.49s/it]

Wikipedia Data saved: ./artist_wiki_pages/J._C._Leyendecker.json

Fetching Wikipedia Data:  43%|████▎     | 479/1126 [08:57<15:05,  1.40s/it]

Wikipedia Data saved: ./artist_wiki_pages/Edmund_Dulac.json

Fetching Wikipedia Data:  43%|████▎     | 480/1126 [08:58<14:01,  1.30s/it]

Wikipedia Data saved: ./artist_wiki_pages/Alfred_Roller.json

Fetching Wikipedia Data:  43%|████▎     | 481/1126 [08:59<13:22,  1.24s/it]

Η σελίδα 'Rehm Fritz' δεν βρέθηκε.

Fetching Wikipedia Data:  43%|████▎     | 482/1126 [09:00<11:33,  1.08s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jean-Paul_Laurens.json

Fetching Wikipedia Data:  43%|████▎     | 483/1126 [09:01<11:32,  1.08s/it]

Wikipedia Data saved: ./artist_wiki_pages/John_Bauer_(illustrator).json

Fetching Wikipedia Data:  43%|████▎     | 484/1126 [09:04<17:26,  1.63s/it]

Wikipedia Data saved: ./artist_wiki_pages/Ludwig_Manzel.json

Fetching Wikipedia Data:  43%|████▎     | 485/1126 [09:05<15:40,  1.47s/it]

Wikipedia Data saved: ./artist_wiki_pages/Maximilian_Pirner.json

Fetching Wikipedia Data:  43%|████▎     | 486/1126 [09:06<16:27,  1.54s/it]

Wikipedia Data saved: ./artist_wiki_pages/A._Y._Jackson.json

Fetching Wikipedia Data:  43%|████▎     | 487/1126 [09:08<15:26,  1.45s/it]

Wikipedia Data saved: ./artist_wiki_pages/Dorothy_P._Lathrop.json

Fetching Wikipedia Data:  43%|████▎     | 488/1126 [09:09<16:31,  1.55s/it]

Wikipedia Data saved: ./artist_wiki_pages/József_Rippl-Rónai.json

Fetching Wikipedia Data:  43%|████▎     | 489/1126 [09:11<15:00,  1.41s/it]

Wikipedia Data saved: ./artist_wiki_pages/Léon_Bakst.json

Fetching Wikipedia Data:  44%|████▎     | 490/1126 [09:12<13:50,  1.31s/it]

Wikipedia Data saved: ./artist_wiki_pages/Léo_Schnug.json

Fetching Wikipedia Data:  44%|████▎     | 491/1126 [09:13<13:01,  1.23s/it]

Wikipedia Data saved: ./artist_wiki_pages/Otto_Gustaf_Carlsund.json

Fetching Wikipedia Data:  44%|████▎     | 492/1126 [09:14<13:53,  1.32s/it]

Wikipedia Data saved: ./artist_wiki_pages/Virginia_Frances_Sterrett.json

Fetching Wikipedia Data:  44%|████▍     | 493/1126 [09:16<14:54,  1.41s/it]

Wikipedia Data saved: ./artist_wiki_pages/Anna_Boberg.json

Fetching Wikipedia Data:  44%|████▍     | 494/1126 [09:18<16:03,  1.52s/it]

Wikipedia Data saved: ./artist_wiki_pages/Wilhelm_Trübner.json

Fetching Wikipedia Data:  44%|████▍     | 495/1126 [09:19<16:23,  1.56s/it]

Wikipedia Data saved: ./artist_wiki_pages/Frank_Xavier_Leyendecker.json

Fetching Wikipedia Data:  44%|████▍     | 496/1126 [09:21<16:38,  1.58s/it]

Wikipedia Data saved: ./artist_wiki_pages/Gerda_Wegener.json

Fetching Wikipedia Data:  44%|████▍     | 497/1126 [09:23<17:50,  1.70s/it]

Wikipedia Data saved: ./artist_wiki_pages/Petre_Otskheli.json

Fetching Wikipedia Data:  44%|████▍     | 498/1126 [09:24<15:48,  1.51s/it]

Wikipedia Data saved: ./artist_wiki_pages/Franz_Stuck.json

Fetching Wikipedia Data:  44%|████▍     | 499/1126 [09:25<14:24,  1.38s/it]

Wikipedia Data saved: ./artist_wiki_pages/Heinrich_Lefler.json

Fetching Wikipedia Data:  44%|████▍     | 500/1126 [09:26<14:37,  1.40s/it]

Η σελίδα 'Kent Rockwell' δεν βρέθηκε.

Fetching Wikipedia Data:  44%|████▍     | 501/1126 [09:27<12:24,  1.19s/it]

Η σελίδα 'Назарук, Вячеслав Михайлович' δεν βρέθηκε.

Fetching Wikipedia Data:  45%|████▍     | 502/1126 [09:28<10:52,  1.05s/it]

Η σελίδα 'Maksymovych Vsevolod' δεν βρέθηκε.

Fetching Wikipedia Data:  45%|████▍     | 503/1126 [09:29<09:46,  1.06it/s]

Wikipedia Data saved: ./artist_wiki_pages/Frances_MacDonald.json

Fetching Wikipedia Data:  45%|████▍     | 504/1126 [09:31<13:05,  1.26s/it]

Wikipedia Data saved: ./artist_wiki_pages/Margaret_Macdonald_Mackintosh.json

Fetching Wikipedia Data:  45%|████▍     | 505/1126 [09:32<12:29,  1.21s/it]

Wikipedia Data saved: ./artist_wiki_pages/Heorhiy_Narbut.json

Fetching Wikipedia Data:  45%|████▍     | 506/1126 [09:33<14:07,  1.37s/it]

Wikipedia Data saved: ./artist_wiki_pages/Albert_Anker.json

Fetching Wikipedia Data:  45%|████▌     | 507/1126 [09:34<13:08,  1.27s/it]

Wikipedia Data saved: ./artist_wiki_pages/Fernand_Khnopff.json

Fetching Wikipedia Data:  45%|████▌     | 508/1126 [09:36<12:36,  1.22s/it]

Wikipedia Data saved: ./artist_wiki_pages/Arthur_Beecher_Carles.json

Fetching Wikipedia Data:  45%|████▌     | 509/1126 [09:37<13:53,  1.35s/it]

Wikipedia Data saved: ./artist_wiki_pages/Théophile_Steinlen.json

Fetching Wikipedia Data:  45%|████▌     | 510/1126 [09:38<12:56,  1.26s/it]

Wikipedia Data saved: ./artist_wiki_pages/J._E._H._MacDonald.json

Fetching Wikipedia Data:  45%|████▌     | 511/1126 [09:40<15:35,  1.52s/it]

Wikipedia Data saved: ./artist_wiki_pages/Owen_Jones_(architect).json

Fetching Wikipedia Data:  45%|████▌     | 512/1126 [09:43<17:42,  1.73s/it]

Η σελίδα 'Brendekilde Andersen Hans' δεν βρέθηκε.

Fetching Wikipedia Data:  46%|████▌     | 513/1126 [09:43<14:30,  1.42s/it]

Wikipedia Data saved: ./artist_wiki_pages/Ethel_Reed.json

Fetching Wikipedia Data:  46%|████▌     | 514/1126 [09:44<13:29,  1.32s/it]

Η σελίδα 'Харалампи Тачев' δεν βρέθηκε.

Fetching Wikipedia Data:  46%|████▌     | 515/1126 [09:45<11:34,  1.14s/it]

Wikipedia Data saved: ./artist_wiki_pages/Eugène_Grasset.json

Fetching Wikipedia Data:  46%|████▌     | 516/1126 [09:46<11:24,  1.12s/it]

Wikipedia Data saved: ./artist_wiki_pages/Ivan_Bilibin.json

Fetching Wikipedia Data:  46%|████▌     | 517/1126 [09:48<14:55,  1.47s/it]

Wikipedia Data saved: ./artist_wiki_pages/Joan_Brull.json

Fetching Wikipedia Data:  46%|████▌     | 518/1126 [09:50<13:40,  1.35s/it]

Wikipedia Data saved: ./artist_wiki_pages/Theodor_Kittelsen.json

Fetching Wikipedia Data:  46%|████▌     | 519/1126 [09:51<12:51,  1.27s/it]

Wikipedia Data saved: ./artist_wiki_pages/Artuš_Scheiner.json

Fetching Wikipedia Data:  46%|████▌     | 520/1126 [09:52<12:14,  1.21s/it]

Wikipedia Data saved: ./artist_wiki_pages/Achille_Beltrame.json

Fetching Wikipedia Data:  46%|████▋     | 521/1126 [09:53<13:52,  1.38s/it]

Wikipedia Data saved: ./artist_wiki_pages/Rose_O'Neill.json

Fetching Wikipedia Data:  46%|████▋     | 522/1126 [09:55<13:13,  1.31s/it]

Wikipedia Data saved: ./artist_wiki_pages/Alexandre_Benois.json

Fetching Wikipedia Data:  46%|████▋     | 523/1126 [09:56<12:34,  1.25s/it]

Wikipedia Data saved: ./artist_wiki_pages/Oleksa_Novakivskyi.json

Fetching Wikipedia Data:  47%|████▋     | 524/1126 [09:57<12:01,  1.20s/it]

Wikipedia Data saved: ./artist_wiki_pages/Albert_Lynch.json

Fetching Wikipedia Data:  47%|████▋     | 525/1126 [09:59<13:49,  1.38s/it]

Wikipedia Data saved: ./artist_wiki_pages/Tom_Thomson.json

Fetching Wikipedia Data:  47%|████▋     | 526/1126 [10:00<14:08,  1.41s/it]

Wikipedia Data saved: ./artist_wiki_pages/Arthur_Rackham.json

Fetching Wikipedia Data:  47%|████▋     | 527/1126 [10:01<13:23,  1.34s/it]

Wikipedia Data saved: ./artist_wiki_pages/Pavel_Filonov.json

Fetching Wikipedia Data:  47%|████▋     | 528/1126 [10:03<15:00,  1.51s/it]

Wikipedia Data saved: ./artist_wiki_pages/Harry_Clarke.json

Fetching Wikipedia Data:  47%|████▋     | 529/1126 [10:04<13:43,  1.38s/it]

Wikipedia Data saved: ./artist_wiki_pages/Beatrix_Potter.json

Fetching Wikipedia Data:  47%|████▋     | 530/1126 [10:05<13:15,  1.33s/it]

Wikipedia Data saved: ./artist_wiki_pages/Henry_van_de_Velde.json

Fetching Wikipedia Data:  47%|████▋     | 531/1126 [10:07<15:14,  1.54s/it]

Wikipedia Data saved: ./artist_wiki_pages/Georges_Claude.json

Fetching Wikipedia Data:  47%|████▋     | 532/1126 [10:09<13:47,  1.39s/it]

Wikipedia Data saved: ./artist_wiki_pages/Anna_Ostroumova-Lebedeva.json

Fetching Wikipedia Data:  47%|████▋     | 533/1126 [10:10<12:46,  1.29s/it]

Wikipedia Data saved: ./artist_wiki_pages/John_French_Sloan.json

Fetching Wikipedia Data:  47%|████▋     | 534/1126 [10:11<12:15,  1.24s/it]

Wikipedia Data saved: ./artist_wiki_pages/Francesc_Masriera.json

Fetching Wikipedia Data:  48%|████▊     | 535/1126 [10:12<13:30,  1.37s/it]

Wikipedia Data saved: ./artist_wiki_pages/Azim_Azimzade.json

Fetching Wikipedia Data:  48%|████▊     | 536/1126 [10:14<14:44,  1.50s/it]

Wikipedia Data saved: ./artist_wiki_pages/Charles_Rennie_Mackintosh.json

Fetching Wikipedia Data:  48%|████▊     | 537/1126 [10:15<13:43,  1.40s/it]

Wikipedia Data saved: ./artist_wiki_pages/George_Barbier_(illustrator).json

Fetching Wikipedia Data:  48%|████▊     | 538/1126 [10:17<14:47,  1.51s/it]

Wikipedia Data saved: ./artist_wiki_pages/Vasyl_Krychevsky.json

Fetching Wikipedia Data:  48%|████▊     | 539/1126 [10:18<13:29,  1.38s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jules_Chéret.json

Fetching Wikipedia Data:  48%|████▊     | 540/1126 [10:19<12:34,  1.29s/it]

Wikipedia Data saved: ./artist_wiki_pages/Aleksandra_Ekster.json

Fetching Wikipedia Data:  48%|████▊     | 541/1126 [10:20<11:52,  1.22s/it]

Wikipedia Data saved: ./artist_wiki_pages/Franklin_Carmichael.json

Fetching Wikipedia Data:  48%|████▊     | 542/1126 [10:23<16:40,  1.71s/it]

Η σελίδα 'Metlicovitz Leopoldo' δεν βρέθηκε.

Fetching Wikipedia Data:  48%|████▊     | 543/1126 [10:24<13:42,  1.41s/it]

Wikipedia Data saved: ./artist_wiki_pages/Eugene_Lanceray.json

Fetching Wikipedia Data:  48%|████▊     | 544/1126 [10:26<14:44,  1.52s/it]

Wikipedia Data saved: ./artist_wiki_pages/Raphael_Kirchner.json

Fetching Wikipedia Data:  48%|████▊     | 545/1126 [10:27<15:03,  1.55s/it]

Wikipedia Data saved: ./artist_wiki_pages/Bertold_Löffler.json

Fetching Wikipedia Data:  48%|████▊     | 546/1126 [10:28<13:41,  1.42s/it]

Wikipedia Data saved: ./artist_wiki_pages/Paolo_Veronese.json

Fetching Wikipedia Data:  49%|████▊     | 547/1126 [10:31<16:18,  1.69s/it]

Wikipedia Data saved: ./artist_wiki_pages/Master_of_the_Small_Landscapes.json

Fetching Wikipedia Data:  49%|████▊     | 548/1126 [10:32<14:31,  1.51s/it]

Wikipedia Data saved: ./artist_wiki_pages/Pinturicchio.json

Fetching Wikipedia Data:  49%|████▉     | 549/1126 [10:33<13:17,  1.38s/it]

Wikipedia Data saved: ./artist_wiki_pages/Giorgione.json

Fetching Wikipedia Data:  49%|████▉     | 550/1126 [10:35<15:48,  1.65s/it]

Wikipedia Data saved: ./artist_wiki_pages/Giovanni_Antonio_Boltraffio.json

Fetching Wikipedia Data:  49%|████▉     | 551/1126 [10:36<14:13,  1.49s/it]

Wikipedia Data saved: ./artist_wiki_pages/Maerten_de_Vos.json

Fetching Wikipedia Data:  49%|████▉     | 552/1126 [10:37<13:02,  1.36s/it]

Wikipedia Data saved: ./artist_wiki_pages/Mariotto_Albertinelli.json

Fetching Wikipedia Data:  49%|████▉     | 553/1126 [10:38<12:05,  1.27s/it]

Wikipedia Data saved: ./artist_wiki_pages/Martin_Kober.json

Fetching Wikipedia Data:  49%|████▉     | 554/1126 [10:39<11:33,  1.21s/it]

Wikipedia Data saved: ./artist_wiki_pages/Leonardo_da_Vinci.json

Fetching Wikipedia Data:  49%|████▉     | 555/1126 [10:41<12:48,  1.35s/it]

Wikipedia Data saved: ./artist_wiki_pages/Palma_Vecchio.json

Fetching Wikipedia Data:  49%|████▉     | 556/1126 [10:43<14:21,  1.51s/it]

Wikipedia Data saved: ./artist_wiki_pages/Defendente_Ferrari.json

Fetching Wikipedia Data:  49%|████▉     | 557/1126 [10:44<13:02,  1.38s/it]

Wikipedia Data saved: ./artist_wiki_pages/Pontormo.json

Fetching Wikipedia Data:  50%|████▉     | 558/1126 [10:45<12:24,  1.31s/it]

Wikipedia Data saved: ./artist_wiki_pages/Barbara_Longhi.json

Fetching Wikipedia Data:  50%|████▉     | 559/1126 [10:47<14:13,  1.51s/it]

Wikipedia Data saved: ./artist_wiki_pages/Rogier_van_der_Weyden.json

Fetching Wikipedia Data:  50%|████▉     | 560/1126 [10:48<13:24,  1.42s/it]

Wikipedia Data saved: ./artist_wiki_pages/Hans_von_Aachen.json

Fetching Wikipedia Data:  50%|████▉     | 561/1126 [10:50<12:25,  1.32s/it]

Wikipedia Data saved: ./artist_wiki_pages/Dosso_Dossi.json

Fetching Wikipedia Data:  50%|████▉     | 562/1126 [10:51<13:24,  1.43s/it]

Wikipedia Data saved: ./artist_wiki_pages/Benvenuto_Cellini.json

Fetching Wikipedia Data:  50%|█████     | 563/1126 [10:52<12:41,  1.35s/it]

Wikipedia Data saved: ./artist_wiki_pages/Domenico_di_Pace_Beccafumi.json

Fetching Wikipedia Data:  50%|█████     | 564/1126 [10:54<12:18,  1.31s/it]

Wikipedia Data saved: ./artist_wiki_pages/Lucas_Cranach_the_Elder.json

Fetching Wikipedia Data:  50%|█████     | 565/1126 [10:55<11:55,  1.27s/it]

Wikipedia Data saved: ./artist_wiki_pages/Pieter_Brueghel_the_Younger.json

Fetching Wikipedia Data:  50%|█████     | 566/1126 [10:56<11:34,  1.24s/it]

Wikipedia Data saved: ./artist_wiki_pages/Donato_Bramante.json

Fetching Wikipedia Data:  50%|█████     | 567/1126 [10:57<11:07,  1.19s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jean_Hey.json

Fetching Wikipedia Data:  50%|█████     | 568/1126 [10:58<10:47,  1.16s/it]

Wikipedia Data saved: ./artist_wiki_pages/Konrad_Witz.json

Fetching Wikipedia Data:  51%|█████     | 569/1126 [10:59<10:34,  1.14s/it]

Wikipedia Data saved: ./artist_wiki_pages/Cristóvão_de_Figueiredo.json

Fetching Wikipedia Data:  51%|█████     | 570/1126 [11:00<10:49,  1.17s/it]

Wikipedia Data saved: ./artist_wiki_pages/Matthias_Grünewald.json

Fetching Wikipedia Data:  51%|█████     | 571/1126 [11:02<10:33,  1.14s/it]

Wikipedia Data saved: ./artist_wiki_pages/Sofonisba_Anguissola.json

Fetching Wikipedia Data:  51%|█████     | 572/1126 [11:03<10:50,  1.17s/it]

Η σελίδα 'Giovane Il Palma' δεν βρέθηκε.

Fetching Wikipedia Data:  51%|█████     | 573/1126 [11:03<09:31,  1.03s/it]

Wikipedia Data saved: ./artist_wiki_pages/Michelangelo.json

Fetching Wikipedia Data:  51%|█████     | 574/1126 [11:05<10:31,  1.14s/it]

Wikipedia Data saved: ./artist_wiki_pages/Cima_da_Conegliano.json

Fetching Wikipedia Data:  51%|█████     | 575/1126 [11:06<10:22,  1.13s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jan_Provoost.json

Fetching Wikipedia Data:  51%|█████     | 576/1126 [11:07<10:11,  1.11s/it]

Wikipedia Data saved: ./artist_wiki_pages/Giulio_Romano.json

Fetching Wikipedia Data:  51%|█████     | 577/1126 [11:09<12:40,  1.38s/it]

Wikipedia Data saved: ./artist_wiki_pages/Lorenzo_Lotto.json

Fetching Wikipedia Data:  51%|█████▏    | 578/1126 [11:10<12:00,  1.32s/it]

Wikipedia Data saved: ./artist_wiki_pages/Hugo_van_der_Goes.json

Fetching Wikipedia Data:  51%|█████▏    | 579/1126 [11:11<11:29,  1.26s/it]

Wikipedia Data saved: ./artist_wiki_pages/Titian.json

Fetching Wikipedia Data:  52%|█████▏    | 580/1126 [11:13<11:34,  1.27s/it]

Wikipedia Data saved: ./artist_wiki_pages/Gentile_Bellini.json

Fetching Wikipedia Data:  52%|█████▏    | 581/1126 [11:14<11:02,  1.22s/it]

Wikipedia Data saved: ./artist_wiki_pages/Parmigianino.json

Fetching Wikipedia Data:  52%|█████▏    | 582/1126 [11:16<12:59,  1.43s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jan_Sanders_van_Hemessen.json

Fetching Wikipedia Data:  52%|█████▏    | 583/1126 [11:17<12:01,  1.33s/it]

Wikipedia Data saved: ./artist_wiki_pages/Pietro_Perugino.json

Fetching Wikipedia Data:  52%|█████▏    | 584/1126 [11:18<11:26,  1.27s/it]

Wikipedia Data saved: ./artist_wiki_pages/Bronzino.json

Fetching Wikipedia Data:  52%|█████▏    | 585/1126 [11:19<11:08,  1.24s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jerg_Ratgeb.json

Fetching Wikipedia Data:  52%|█████▏    | 586/1126 [11:20<10:41,  1.19s/it]

Wikipedia Data saved: ./artist_wiki_pages/Dieric_Bouts.json

Fetching Wikipedia Data:  52%|█████▏    | 587/1126 [11:21<10:26,  1.16s/it]

Wikipedia Data saved: ./artist_wiki_pages/Giovanni_Bellini.json

Fetching Wikipedia Data:  52%|█████▏    | 588/1126 [11:22<10:14,  1.14s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jean_Fouquet.json

Fetching Wikipedia Data:  52%|█████▏    | 589/1126 [11:23<10:02,  1.12s/it]

Wikipedia Data saved: ./artist_wiki_pages/Vittore_Carpaccio.json

Fetching Wikipedia Data:  52%|█████▏    | 590/1126 [11:26<14:07,  1.58s/it]

Wikipedia Data saved: ./artist_wiki_pages/Gregório_Lopes.json

Fetching Wikipedia Data:  52%|█████▏    | 591/1126 [11:27<12:43,  1.43s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jacques_Daret.json

Fetching Wikipedia Data:  53%|█████▎    | 592/1126 [11:28<11:45,  1.32s/it]

Wikipedia Data saved: ./artist_wiki_pages/Hieronymus_Bosch.json

Fetching Wikipedia Data:  53%|█████▎    | 593/1126 [11:29<11:17,  1.27s/it]

Wikipedia Data saved: ./artist_wiki_pages/Tintoretto.json

Fetching Wikipedia Data:  53%|█████▎    | 594/1126 [11:31<11:00,  1.24s/it]

Wikipedia Data saved: ./artist_wiki_pages/Giambologna.json

Fetching Wikipedia Data:  53%|█████▎    | 595/1126 [11:32<10:30,  1.19s/it]

Wikipedia Data saved: ./artist_wiki_pages/Nicholas_Hilliard.json

Fetching Wikipedia Data:  53%|█████▎    | 596/1126 [11:33<10:24,  1.18s/it]

Wikipedia Data saved: ./artist_wiki_pages/Hans_Memling.json

Fetching Wikipedia Data:  53%|█████▎    | 597/1126 [11:34<10:08,  1.15s/it]

Wikipedia Data saved: ./artist_wiki_pages/El_Greco.json

Fetching Wikipedia Data:  53%|█████▎    | 598/1126 [11:37<16:14,  1.85s/it]

Wikipedia Data saved: ./artist_wiki_pages/Raphael.json

Fetching Wikipedia Data:  53%|█████▎    | 599/1126 [11:39<14:48,  1.69s/it]

Wikipedia Data saved: ./artist_wiki_pages/Adam_van_Noort.json

Fetching Wikipedia Data:  53%|█████▎    | 600/1126 [11:40<14:35,  1.66s/it]

Wikipedia Data saved: ./artist_wiki_pages/Martin_Schongauer.json

Fetching Wikipedia Data:  53%|█████▎    | 601/1126 [11:41<13:19,  1.52s/it]

Wikipedia Data saved: ./artist_wiki_pages/Hans_Hoffmann_(painter).json

Fetching Wikipedia Data:  53%|█████▎    | 602/1126 [11:42<12:07,  1.39s/it]

Wikipedia Data saved: ./artist_wiki_pages/Andrea_Mantegna.json

Fetching Wikipedia Data:  54%|█████▎    | 603/1126 [11:45<14:47,  1.70s/it]

Wikipedia Data saved: ./artist_wiki_pages/Bartolomeo_Passarotti.json

Fetching Wikipedia Data:  54%|█████▎    | 604/1126 [11:46<13:11,  1.52s/it]

Wikipedia Data saved: ./artist_wiki_pages/Joachim_Wtewael.json

Fetching Wikipedia Data:  54%|█████▎    | 605/1126 [11:48<14:19,  1.65s/it]

Wikipedia Data saved: ./artist_wiki_pages/Plautilla_Nelli.json

Fetching Wikipedia Data:  54%|█████▍    | 606/1126 [11:50<14:44,  1.70s/it]

Wikipedia Data saved: ./artist_wiki_pages/Gerard_David.json

Fetching Wikipedia Data:  54%|█████▍    | 607/1126 [11:51<13:03,  1.51s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jan_van_Eyck.json

Fetching Wikipedia Data:  54%|█████▍    | 608/1126 [11:52<12:10,  1.41s/it]

Wikipedia Data saved: ./artist_wiki_pages/Benvenuto_Tisi.json

Fetching Wikipedia Data:  54%|█████▍    | 609/1126 [11:54<12:46,  1.48s/it]

Wikipedia Data saved: ./artist_wiki_pages/Francisco_Pacheco.json

Fetching Wikipedia Data:  54%|█████▍    | 610/1126 [11:55<11:46,  1.37s/it]

Wikipedia Data saved: ./artist_wiki_pages/Robert_Campin.json

Fetching Wikipedia Data:  54%|█████▍    | 611/1126 [11:56<11:03,  1.29s/it]

Wikipedia Data saved: ./artist_wiki_pages/Il_Sodoma.json

Fetching Wikipedia Data:  54%|█████▍    | 612/1126 [11:57<10:27,  1.22s/it]

Wikipedia Data saved: ./artist_wiki_pages/Piero_di_Cosimo.json

Fetching Wikipedia Data:  54%|█████▍    | 613/1126 [11:59<12:24,  1.45s/it]

Η σελίδα 'Bergognone Ambrogio' δεν βρέθηκε.

Fetching Wikipedia Data:  55%|█████▍    | 614/1126 [12:00<10:28,  1.23s/it]

Wikipedia Data saved: ./artist_wiki_pages/Bernhard_Strigel.json

Fetching Wikipedia Data:  55%|█████▍    | 615/1126 [12:03<16:53,  1.98s/it]

Wikipedia Data saved: ./artist_wiki_pages/Rosso_Fiorentino.json

Fetching Wikipedia Data:  55%|█████▍    | 616/1126 [12:05<16:12,  1.91s/it]

Η σελίδα 'Reymerswaele Van Marinus' δεν βρέθηκε.

Fetching Wikipedia Data:  55%|█████▍    | 617/1126 [12:06<13:04,  1.54s/it]

Wikipedia Data saved: ./artist_wiki_pages/Fede_Galizia.json

Fetching Wikipedia Data:  55%|█████▍    | 618/1126 [12:07<11:47,  1.39s/it]

Η σελίδα 'Salviati Francesco Rossi De Francesco' δεν βρέθηκε.

Fetching Wikipedia Data:  55%|█████▍    | 619/1126 [12:08<10:01,  1.19s/it]

Wikipedia Data saved: ./artist_wiki_pages/Hans_Holbein_the_Elder.json

Fetching Wikipedia Data:  55%|█████▌    | 620/1126 [12:09<11:47,  1.40s/it]

Wikipedia Data saved: ./artist_wiki_pages/Justus_van_Gent.json

Fetching Wikipedia Data:  55%|█████▌    | 621/1126 [12:11<10:55,  1.30s/it]

Wikipedia Data saved: ./artist_wiki_pages/Francesco_Melzi.json

Fetching Wikipedia Data:  55%|█████▌    | 622/1126 [12:12<10:29,  1.25s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jacopo_Bassano.json

Fetching Wikipedia Data:  55%|█████▌    | 623/1126 [12:13<10:00,  1.19s/it]

Wikipedia Data saved: ./artist_wiki_pages/Albrecht_Altdorfer.json

Fetching Wikipedia Data:  55%|█████▌    | 624/1126 [12:14<09:38,  1.15s/it]

Wikipedia Data saved: ./artist_wiki_pages/Giulio_Clovio.json

Fetching Wikipedia Data:  56%|█████▌    | 625/1126 [12:15<09:27,  1.13s/it]

Wikipedia Data saved: ./artist_wiki_pages/Quentin_Matsys.json

Fetching Wikipedia Data:  56%|█████▌    | 626/1126 [12:16<09:22,  1.12s/it]

Wikipedia Data saved: ./artist_wiki_pages/Alessandro_Allori.json

Fetching Wikipedia Data:  56%|█████▌    | 627/1126 [12:17<09:18,  1.12s/it]

Wikipedia Data saved: ./artist_wiki_pages/Pieter_Aertsen.json

Fetching Wikipedia Data:  56%|█████▌    | 628/1126 [12:18<09:06,  1.10s/it]

Wikipedia Data saved: ./artist_wiki_pages/Bernardino_Luini.json

Fetching Wikipedia Data:  56%|█████▌    | 629/1126 [12:20<11:12,  1.35s/it]

Wikipedia Data saved: ./artist_wiki_pages/Antonio_del_Pollaiolo.json

Fetching Wikipedia Data:  56%|█████▌    | 630/1126 [12:21<10:39,  1.29s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jan_Joest.json

Fetching Wikipedia Data:  56%|█████▌    | 631/1126 [12:22<10:03,  1.22s/it]

Wikipedia Data saved: ./artist_wiki_pages/Vicente_Juan_Masip.json

Fetching Wikipedia Data:  56%|█████▌    | 632/1126 [12:23<09:40,  1.18s/it]

Wikipedia Data saved: ./artist_wiki_pages/Petrus_Christus.json

Fetching Wikipedia Data:  56%|█████▌    | 633/1126 [12:24<09:29,  1.15s/it]

Wikipedia Data saved: ./artist_wiki_pages/Maarten_van_Heemskerck.json

Fetching Wikipedia Data:  56%|█████▋    | 634/1126 [12:26<09:30,  1.16s/it]

Wikipedia Data saved: ./artist_wiki_pages/Geertgen_tot_Sint_Jans.json

Fetching Wikipedia Data:  56%|█████▋    | 635/1126 [12:27<09:19,  1.14s/it]

Wikipedia Data saved: ./artist_wiki_pages/Carlo_Urbino.json

Fetching Wikipedia Data:  56%|█████▋    | 636/1126 [12:28<09:08,  1.12s/it]

Wikipedia Data saved: ./artist_wiki_pages/Marietta_Robusti.json

Fetching Wikipedia Data:  57%|█████▋    | 637/1126 [12:29<09:05,  1.11s/it]

Wikipedia Data saved: ./artist_wiki_pages/Giorgio_Vasari.json

Fetching Wikipedia Data:  57%|█████▋    | 638/1126 [12:30<09:09,  1.13s/it]

Wikipedia Data saved: ./artist_wiki_pages/Luca_Signorelli.json

Fetching Wikipedia Data:  57%|█████▋    | 639/1126 [12:31<09:09,  1.13s/it]

Wikipedia Data saved: ./artist_wiki_pages/Bartolomeo_Veneto.json

Fetching Wikipedia Data:  57%|█████▋    | 640/1126 [12:32<09:01,  1.11s/it]

Wikipedia Data saved: ./artist_wiki_pages/Fra_Bartolomeo.json

Fetching Wikipedia Data:  57%|█████▋    | 641/1126 [12:33<09:18,  1.15s/it]

Wikipedia Data saved: ./artist_wiki_pages/Domenico_Tintoretto.json

Fetching Wikipedia Data:  57%|█████▋    | 642/1126 [12:35<09:03,  1.12s/it]

Wikipedia Data saved: ./artist_wiki_pages/Lavinia_Fontana.json

Fetching Wikipedia Data:  57%|█████▋    | 643/1126 [12:36<09:05,  1.13s/it]

Wikipedia Data saved: ./artist_wiki_pages/Tobias_Verhaecht.json

Fetching Wikipedia Data:  57%|█████▋    | 644/1126 [12:37<09:04,  1.13s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jan_Mabuse.json

Fetching Wikipedia Data:  57%|█████▋    | 645/1126 [12:39<10:35,  1.32s/it]

Wikipedia Data saved: ./artist_wiki_pages/Bernard_van_Orley.json

Fetching Wikipedia Data:  57%|█████▋    | 646/1126 [12:41<12:36,  1.58s/it]

Wikipedia Data saved: ./artist_wiki_pages/Andrea_del_Sarto.json

Fetching Wikipedia Data:  57%|█████▋    | 647/1126 [12:43<14:12,  1.78s/it]

Wikipedia Data saved: ./artist_wiki_pages/Albrecht_Dürer.json

Fetching Wikipedia Data:  58%|█████▊    | 648/1126 [12:44<12:51,  1.61s/it]

Wikipedia Data saved: ./artist_wiki_pages/Andrea_Solari.json

Fetching Wikipedia Data:  58%|█████▊    | 649/1126 [12:45<11:35,  1.46s/it]

Wikipedia Data saved: ./artist_wiki_pages/Filippino_Lippi.json

Fetching Wikipedia Data:  58%|█████▊    | 650/1126 [12:47<12:36,  1.59s/it]

Wikipedia Data saved: ./artist_wiki_pages/Hans_Baldung.json

Fetching Wikipedia Data:  58%|█████▊    | 651/1126 [12:49<13:56,  1.76s/it]

Wikipedia Data saved: ./artist_wiki_pages/Daniele_da_Volterra.json

Fetching Wikipedia Data:  58%|█████▊    | 652/1126 [12:51<14:10,  1.79s/it]

Wikipedia Data saved: ./artist_wiki_pages/Hendrik_Goltzius.json

Fetching Wikipedia Data:  58%|█████▊    | 653/1126 [12:52<12:24,  1.57s/it]

Wikipedia Data saved: ./artist_wiki_pages/Otto_van_Veen.json

Fetching Wikipedia Data:  58%|█████▊    | 654/1126 [12:54<12:54,  1.64s/it]

Wikipedia Data saved: ./artist_wiki_pages/Hans_Holbein_the_Younger.json

Fetching Wikipedia Data:  58%|█████▊    | 655/1126 [12:56<12:19,  1.57s/it]

Wikipedia Data saved: ./artist_wiki_pages/Alessandro_Vittoria.json

Fetching Wikipedia Data:  58%|█████▊    | 656/1126 [12:57<11:05,  1.42s/it]

Wikipedia Data saved: ./artist_wiki_pages/Bartholomeus_Spranger.json

Fetching Wikipedia Data:  58%|█████▊    | 657/1126 [12:58<10:19,  1.32s/it]

Wikipedia Data saved: ./artist_wiki_pages/Joachim_Patinir.json

Fetching Wikipedia Data:  58%|█████▊    | 658/1126 [12:59<09:42,  1.24s/it]

Wikipedia Data saved: ./artist_wiki_pages/Orazio_Gentileschi.json

Fetching Wikipedia Data:  59%|█████▊    | 659/1126 [13:01<11:53,  1.53s/it]

Wikipedia Data saved: ./artist_wiki_pages/Antonio_da_Correggio.json

Fetching Wikipedia Data:  59%|█████▊    | 660/1126 [13:02<10:52,  1.40s/it]

Wikipedia Data saved: ./artist_wiki_pages/Giuseppe_Arcimboldo.json

Fetching Wikipedia Data:  59%|█████▊    | 661/1126 [13:03<10:20,  1.33s/it]

Η σελίδα 'Piombo Del Sebastiano' δεν βρέθηκε.

Fetching Wikipedia Data:  59%|█████▉    | 662/1126 [13:04<08:50,  1.14s/it]

Wikipedia Data saved: ./artist_wiki_pages/Pieter_Bruegel_the_Elder.json

Fetching Wikipedia Data:  59%|█████▉    | 663/1126 [13:05<08:59,  1.16s/it]

Wikipedia Data saved: ./artist_wiki_pages/Henri_Fantin-Latour.json

Fetching Wikipedia Data:  59%|█████▉    | 664/1126 [13:06<08:44,  1.14s/it]

Η σελίδα 'Lifij Avni Huseyin' δεν βρέθηκε.

Fetching Wikipedia Data:  59%|█████▉    | 665/1126 [13:07<07:44,  1.01s/it]

Wikipedia Data saved: ./artist_wiki_pages/Ludwig_Knaus.json

Fetching Wikipedia Data:  59%|█████▉    | 666/1126 [13:08<07:59,  1.04s/it]

Wikipedia Data saved: ./artist_wiki_pages/Ralph_Hedley.json

Fetching Wikipedia Data:  59%|█████▉    | 667/1126 [13:10<09:37,  1.26s/it]

Wikipedia Data saved: ./artist_wiki_pages/Albert_Edelfelt.json

Fetching Wikipedia Data:  59%|█████▉    | 668/1126 [13:11<09:19,  1.22s/it]

Η σελίδα 'Добри Добрев (художник)' δεν βρέθηκε.

Fetching Wikipedia Data:  59%|█████▉    | 669/1126 [13:12<08:06,  1.06s/it]

Wikipedia Data saved: ./artist_wiki_pages/William_Sidney_Cooper.json

Fetching Wikipedia Data:  60%|█████▉    | 670/1126 [13:13<08:05,  1.07s/it]

Wikipedia Data saved: ./artist_wiki_pages/Joseph_Urbania.json

Fetching Wikipedia Data:  60%|█████▉    | 671/1126 [13:14<09:25,  1.24s/it]

Wikipedia Data saved: ./artist_wiki_pages/Abbott_Handerson_Thayer.json

Fetching Wikipedia Data:  60%|█████▉    | 672/1126 [13:15<09:11,  1.21s/it]

Wikipedia Data saved: ./artist_wiki_pages/Christian_Wilhelm_Allers.json

Fetching Wikipedia Data:  60%|█████▉    | 673/1126 [13:17<08:53,  1.18s/it]

Wikipedia Data saved: ./artist_wiki_pages/Winslow_Homer.json

Fetching Wikipedia Data:  60%|█████▉    | 674/1126 [13:18<08:53,  1.18s/it]

Wikipedia Data saved: ./artist_wiki_pages/Mykola_Samokysh.json

Fetching Wikipedia Data:  60%|█████▉    | 675/1126 [13:19<08:39,  1.15s/it]

Wikipedia Data saved: ./artist_wiki_pages/Henry_Moore_(painter).json

Fetching Wikipedia Data:  60%|██████    | 676/1126 [13:21<09:57,  1.33s/it]

Wikipedia Data saved: ./artist_wiki_pages/Charles_Sheeler.json

Fetching Wikipedia Data:  60%|██████    | 677/1126 [13:22<09:20,  1.25s/it]

Wikipedia Data saved: ./artist_wiki_pages/Constantin_Daniel_Stahi.json

Fetching Wikipedia Data:  60%|██████    | 678/1126 [13:23<10:19,  1.38s/it]

Wikipedia Data saved: ./artist_wiki_pages/Elin_Danielson-Gambogi.json

Fetching Wikipedia Data:  60%|██████    | 679/1126 [13:25<11:26,  1.54s/it]

Wikipedia Data saved: ./artist_wiki_pages/Ludwig_Passini.json

Fetching Wikipedia Data:  60%|██████    | 680/1126 [13:27<11:40,  1.57s/it]

Η σελίδα 'Leo Steel' δεν βρέθηκε.

Fetching Wikipedia Data:  60%|██████    | 681/1126 [13:28<09:41,  1.31s/it]

Wikipedia Data saved: ./artist_wiki_pages/Ivan_Tvorozhnikov.json

Fetching Wikipedia Data:  61%|██████    | 682/1126 [13:29<10:57,  1.48s/it]

Wikipedia Data saved: ./artist_wiki_pages/Giuseppe_Pellizza_da_Volpedo.json

Fetching Wikipedia Data:  61%|██████    | 683/1126 [13:31<10:00,  1.36s/it]

Wikipedia Data saved: ./artist_wiki_pages/Anton_Ažbe.json

Fetching Wikipedia Data:  61%|██████    | 684/1126 [13:32<09:27,  1.28s/it]

Wikipedia Data saved: ./artist_wiki_pages/Pavel_Fedotov.json

Fetching Wikipedia Data:  61%|██████    | 685/1126 [13:33<08:58,  1.22s/it]

Wikipedia Data saved: ./artist_wiki_pages/Eugène_Burnand.json

Fetching Wikipedia Data:  61%|██████    | 686/1126 [13:34<08:55,  1.22s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jean-François_Millet.json

Fetching Wikipedia Data:  61%|██████    | 687/1126 [13:35<08:44,  1.20s/it]

Wikipedia Data saved: ./artist_wiki_pages/Gustave-Claude-Etienne_Courtois.json

Fetching Wikipedia Data:  61%|██████    | 688/1126 [13:36<08:28,  1.16s/it]

Wikipedia Data saved: ./artist_wiki_pages/Vasily_Sadovnikov.json

Fetching Wikipedia Data:  61%|██████    | 689/1126 [13:37<08:15,  1.13s/it]

Wikipedia Data saved: ./artist_wiki_pages/Volodymyr_Orlovsky.json

Fetching Wikipedia Data:  61%|██████▏   | 690/1126 [13:39<09:16,  1.28s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jean-Louis-Ernest_Meissonier.json

Fetching Wikipedia Data:  61%|██████▏   | 691/1126 [13:40<08:57,  1.24s/it]

Wikipedia Data saved: ./artist_wiki_pages/Anton_Romako.json

Fetching Wikipedia Data:  61%|██████▏   | 692/1126 [13:41<09:28,  1.31s/it]

Wikipedia Data saved: ./artist_wiki_pages/Marie_Bashkirtseff.json

Fetching Wikipedia Data:  62%|██████▏   | 693/1126 [13:43<08:59,  1.25s/it]

Wikipedia Data saved: ./artist_wiki_pages/Hans_Heysen.json

Fetching Wikipedia Data:  62%|██████▏   | 694/1126 [13:44<09:59,  1.39s/it]

Wikipedia Data saved: ./artist_wiki_pages/Léon_Bonnat.json

Fetching Wikipedia Data:  62%|██████▏   | 695/1126 [13:46<10:48,  1.50s/it]

Wikipedia Data saved: ./artist_wiki_pages/Frank_Holl.json

Fetching Wikipedia Data:  62%|██████▏   | 696/1126 [13:47<09:55,  1.39s/it]

Η σελίδα 'Zinovevich Mikhail Olennikov' δεν βρέθηκε.

Fetching Wikipedia Data:  62%|██████▏   | 697/1126 [13:48<08:26,  1.18s/it]

Wikipedia Data saved: ./artist_wiki_pages/George_Catlin.json

Fetching Wikipedia Data:  62%|██████▏   | 698/1126 [13:49<08:24,  1.18s/it]

Wikipedia Data saved: ./artist_wiki_pages/Antonietta_Brandeis.json

Fetching Wikipedia Data:  62%|██████▏   | 699/1126 [13:51<09:14,  1.30s/it]

Wikipedia Data saved: ./artist_wiki_pages/Antonio_Jacobsen.json

Fetching Wikipedia Data:  62%|██████▏   | 700/1126 [13:52<08:43,  1.23s/it]

Wikipedia Data saved: ./artist_wiki_pages/Émile_Prisse_d'Avennes.json

Fetching Wikipedia Data:  62%|██████▏   | 701/1126 [13:53<08:29,  1.20s/it]

Wikipedia Data saved: ./artist_wiki_pages/Eugène_Jansson.json

Fetching Wikipedia Data:  62%|██████▏   | 702/1126 [13:54<08:13,  1.16s/it]

Wikipedia Data saved: ./artist_wiki_pages/Adolph_Menzel.json

Fetching Wikipedia Data:  62%|██████▏   | 703/1126 [13:55<08:08,  1.16s/it]

Wikipedia Data saved: ./artist_wiki_pages/Émile_Friant.json

Fetching Wikipedia Data:  63%|██████▎   | 704/1126 [13:57<09:11,  1.31s/it]

Wikipedia Data saved: ./artist_wiki_pages/Adolf_Hirémy-Hirschl.json

Fetching Wikipedia Data:  63%|██████▎   | 705/1126 [13:58<08:41,  1.24s/it]

Wikipedia Data saved: ./artist_wiki_pages/Anton_Mitov.json

Fetching Wikipedia Data:  63%|██████▎   | 706/1126 [13:59<08:16,  1.18s/it]

Wikipedia Data saved: ./artist_wiki_pages/Ivan_Kramskoi.json

Fetching Wikipedia Data:  63%|██████▎   | 707/1126 [14:00<08:05,  1.16s/it]

Wikipedia Data saved: ./artist_wiki_pages/Aristarkh_Lentulov.json

Fetching Wikipedia Data:  63%|██████▎   | 708/1126 [14:01<08:06,  1.16s/it]

Wikipedia Data saved: ./artist_wiki_pages/André_Gill.json

Fetching Wikipedia Data:  63%|██████▎   | 709/1126 [14:02<07:57,  1.15s/it]

Wikipedia Data saved: ./artist_wiki_pages/Eastman_Johnson.json

Fetching Wikipedia Data:  63%|██████▎   | 710/1126 [14:03<07:47,  1.12s/it]

Wikipedia Data saved: ./artist_wiki_pages/Carl_Bloch.json

Fetching Wikipedia Data:  63%|██████▎   | 711/1126 [14:04<07:40,  1.11s/it]

Wikipedia Data saved: ./artist_wiki_pages/Noè_Bordignon.json

Fetching Wikipedia Data:  63%|██████▎   | 712/1126 [14:05<07:32,  1.09s/it]

Wikipedia Data saved: ./artist_wiki_pages/Hugo_Simberg.json

Fetching Wikipedia Data:  63%|██████▎   | 713/1126 [14:06<07:30,  1.09s/it]

Wikipedia Data saved: ./artist_wiki_pages/Gevorg_Bashinjaghian#cite_note-armsite-2.json

Fetching Wikipedia Data:  63%|██████▎   | 714/1126 [14:08<08:47,  1.28s/it]

Wikipedia Data saved: ./artist_wiki_pages/Mykola_Murashko.json

Fetching Wikipedia Data:  63%|██████▎   | 715/1126 [14:09<08:43,  1.27s/it]

Η σελίδα 'Mironov Gennady' δεν βρέθηκε.

Fetching Wikipedia Data:  64%|██████▎   | 716/1126 [14:10<07:30,  1.10s/it]

Wikipedia Data saved: ./artist_wiki_pages/Augusta_Savage.json

Fetching Wikipedia Data:  64%|██████▎   | 717/1126 [14:11<07:34,  1.11s/it]

Η σελίδα 'Andrey Shishkin' δεν βρέθηκε.

Fetching Wikipedia Data:  64%|██████▍   | 718/1126 [14:12<06:43,  1.01it/s]

Η σελίδα 'Velkov Simeon' δεν βρέθηκε.

Fetching Wikipedia Data:  64%|██████▍   | 719/1126 [14:13<06:06,  1.11it/s]

Wikipedia Data saved: ./artist_wiki_pages/Fyodor_Vasilyev.json

Fetching Wikipedia Data:  64%|██████▍   | 720/1126 [14:15<08:10,  1.21s/it]

Η σελίδα 'Musfik Mihri' δεν βρέθηκε.

Fetching Wikipedia Data:  64%|██████▍   | 721/1126 [14:15<07:06,  1.05s/it]

Wikipedia Data saved: ./artist_wiki_pages/Vincenzo_Migliaro.json

Fetching Wikipedia Data:  64%|██████▍   | 722/1126 [14:16<07:08,  1.06s/it]

Wikipedia Data saved: ./artist_wiki_pages/Samuel_Peploe.json

Fetching Wikipedia Data:  64%|██████▍   | 723/1126 [14:18<08:30,  1.27s/it]

Wikipedia Data saved: ./artist_wiki_pages/Walter_Gay.json

Fetching Wikipedia Data:  64%|██████▍   | 724/1126 [14:20<09:32,  1.42s/it]

Wikipedia Data saved: ./artist_wiki_pages/Frank_Herbert_Mason.json

Fetching Wikipedia Data:  64%|██████▍   | 725/1126 [14:21<08:46,  1.31s/it]

Wikipedia Data saved: ./artist_wiki_pages/Constantin_Guys.json

Fetching Wikipedia Data:  64%|██████▍   | 726/1126 [14:22<08:16,  1.24s/it]

Wikipedia Data saved: ./artist_wiki_pages/Augustus_John.json

Fetching Wikipedia Data:  65%|██████▍   | 727/1126 [14:23<08:05,  1.22s/it]

Η σελίδα 'Ryabchenko Sergey' δεν βρέθηκε.

Fetching Wikipedia Data:  65%|██████▍   | 728/1126 [14:24<07:02,  1.06s/it]

Wikipedia Data saved: ./artist_wiki_pages/Anton_Mauve.json

Fetching Wikipedia Data:  65%|██████▍   | 729/1126 [14:25<07:01,  1.06s/it]

Wikipedia Data saved: ./artist_wiki_pages/Alfred_Parsons_(artist).json

Fetching Wikipedia Data:  65%|██████▍   | 730/1126 [14:26<07:07,  1.08s/it]

Wikipedia Data saved: ./artist_wiki_pages/John_Henderson_(1860–1924).json

Fetching Wikipedia Data:  65%|██████▍   | 731/1126 [14:27<07:06,  1.08s/it]

Wikipedia Data saved: ./artist_wiki_pages/Théodore_Rousseau.json

Fetching Wikipedia Data:  65%|██████▌   | 732/1126 [14:29<08:59,  1.37s/it]

Η σελίδα 'Георги Машев' δεν βρέθηκε.

Fetching Wikipedia Data:  65%|██████▌   | 733/1126 [14:30<07:39,  1.17s/it]

Wikipedia Data saved: ./artist_wiki_pages/David_James_(painter).json

Fetching Wikipedia Data:  65%|██████▌   | 734/1126 [14:31<07:26,  1.14s/it]

Wikipedia Data saved: ./artist_wiki_pages/Ettore_Tito.json

Fetching Wikipedia Data:  65%|██████▌   | 735/1126 [14:32<07:32,  1.16s/it]

Wikipedia Data saved: ./artist_wiki_pages/Maxime_Lalanne.json

Fetching Wikipedia Data:  65%|██████▌   | 736/1126 [14:33<07:32,  1.16s/it]

Wikipedia Data saved: ./artist_wiki_pages/Craig_Mullins.json

Fetching Wikipedia Data:  65%|██████▌   | 737/1126 [14:35<08:13,  1.27s/it]

Wikipedia Data saved: ./artist_wiki_pages/Daniel_Ridgway_Knight.json

Fetching Wikipedia Data:  66%|██████▌   | 738/1126 [14:36<07:50,  1.21s/it]

Wikipedia Data saved: ./artist_wiki_pages/Emile_Claus.json

Fetching Wikipedia Data:  66%|██████▌   | 739/1126 [14:38<09:30,  1.48s/it]

Wikipedia Data saved: ./artist_wiki_pages/Vartan_Mahokian.json

Fetching Wikipedia Data:  66%|██████▌   | 740/1126 [14:40<10:05,  1.57s/it]

Wikipedia Data saved: ./artist_wiki_pages/Paul_Sérusier.json

Fetching Wikipedia Data:  66%|██████▌   | 741/1126 [14:42<10:44,  1.67s/it]

Wikipedia Data saved: ./artist_wiki_pages/Alexei_Harlamoff.json

Fetching Wikipedia Data:  66%|██████▌   | 742/1126 [14:43<10:29,  1.64s/it]

Wikipedia Data saved: ./artist_wiki_pages/Charles_Méryon.json

Fetching Wikipedia Data:  66%|██████▌   | 743/1126 [14:44<09:32,  1.50s/it]

Wikipedia Data saved: ./artist_wiki_pages/Yuriy_Khimich.json

Fetching Wikipedia Data:  66%|██████▌   | 744/1126 [14:46<08:43,  1.37s/it]

Wikipedia Data saved: ./artist_wiki_pages/Adolf_Eberle.json

Fetching Wikipedia Data:  66%|██████▌   | 745/1126 [14:47<08:05,  1.27s/it]

Wikipedia Data saved: ./artist_wiki_pages/Josef_Kriehuber.json

Fetching Wikipedia Data:  66%|██████▋   | 746/1126 [14:48<08:53,  1.40s/it]

Η σελίδα 'Abdullah Suriosubroto' δεν βρέθηκε.

Fetching Wikipedia Data:  66%|██████▋   | 747/1126 [14:49<07:31,  1.19s/it]

Wikipedia Data saved: ./artist_wiki_pages/Théodule_Ribot.json

Fetching Wikipedia Data:  66%|██████▋   | 748/1126 [14:50<07:19,  1.16s/it]

Wikipedia Data saved: ./artist_wiki_pages/Klavdy_Lebedev.json

Fetching Wikipedia Data:  67%|██████▋   | 749/1126 [14:52<08:48,  1.40s/it]

Wikipedia Data saved: ./artist_wiki_pages/Konstantin_Bogaevsky.json

Fetching Wikipedia Data:  67%|██████▋   | 750/1126 [14:54<09:23,  1.50s/it]

Η σελίδα 'Celommi Pasquale' δεν βρέθηκε.

Fetching Wikipedia Data:  67%|██████▋   | 751/1126 [14:55<07:53,  1.26s/it]

Wikipedia Data saved: ./artist_wiki_pages/Pekka_Halonen.json

Fetching Wikipedia Data:  67%|██████▋   | 752/1126 [14:56<08:50,  1.42s/it]

Wikipedia Data saved: ./artist_wiki_pages/Arthur_Pan.json

Fetching Wikipedia Data:  67%|██████▋   | 753/1126 [14:58<08:39,  1.39s/it]

Wikipedia Data saved: ./artist_wiki_pages/Alexandre_Antigna.json

Fetching Wikipedia Data:  67%|██████▋   | 754/1126 [14:59<08:02,  1.30s/it]

Wikipedia Data saved: ./artist_wiki_pages/Johan_Hendrik_Weissenbruch.json

Fetching Wikipedia Data:  67%|██████▋   | 755/1126 [15:00<07:37,  1.23s/it]

Wikipedia Data saved: ./artist_wiki_pages/William_Simpson_(artist).json

Fetching Wikipedia Data:  67%|██████▋   | 756/1126 [15:01<07:33,  1.23s/it]

Wikipedia Data saved: ./artist_wiki_pages/Panos_Terlemezian.json

Fetching Wikipedia Data:  67%|██████▋   | 757/1126 [15:03<08:45,  1.42s/it]

Wikipedia Data saved: ./artist_wiki_pages/Alexei_Savrasov.json

Fetching Wikipedia Data:  67%|██████▋   | 758/1126 [15:05<09:23,  1.53s/it]

Η σελίδα 'Bekaryan Ara' δεν βρέθηκε.

Fetching Wikipedia Data:  67%|██████▋   | 759/1126 [15:05<07:50,  1.28s/it]

Wikipedia Data saved: ./artist_wiki_pages/William_Harnett.json

Fetching Wikipedia Data:  67%|██████▋   | 760/1126 [15:06<07:29,  1.23s/it]

Η σελίδα 'Nardi Enrico' δεν βρέθηκε.

Fetching Wikipedia Data:  68%|██████▊   | 761/1126 [15:07<06:29,  1.07s/it]

Wikipedia Data saved: ./artist_wiki_pages/Telemaco_Signorini.json

Fetching Wikipedia Data:  68%|██████▊   | 762/1126 [15:08<06:32,  1.08s/it]

Wikipedia Data saved: ./artist_wiki_pages/Charles_Hermans.json

Fetching Wikipedia Data:  68%|██████▊   | 763/1126 [15:09<06:32,  1.08s/it]

Η σελίδα 'Arakelyan Sedrak' δεν βρέθηκε.

Fetching Wikipedia Data:  68%|██████▊   | 764/1126 [15:10<05:51,  1.03it/s]

Wikipedia Data saved: ./artist_wiki_pages/Vardges_Sureniants.json

Fetching Wikipedia Data:  68%|██████▊   | 765/1126 [15:11<06:07,  1.02s/it]

Wikipedia Data saved: ./artist_wiki_pages/Yefim_Volkov.json

Fetching Wikipedia Data:  68%|██████▊   | 766/1126 [15:13<08:01,  1.34s/it]

Η σελίδα 'Higuera Jose' δεν βρέθηκε.

Fetching Wikipedia Data:  68%|██████▊   | 767/1126 [15:14<06:50,  1.14s/it]

Wikipedia Data saved: ./artist_wiki_pages/Alexei_Korzukhin.json

Fetching Wikipedia Data:  68%|██████▊   | 768/1126 [15:16<07:39,  1.28s/it]

Wikipedia Data saved: ./artist_wiki_pages/Ippolito_Caffi.json

Fetching Wikipedia Data:  68%|██████▊   | 769/1126 [15:17<08:29,  1.43s/it]

Η σελίδα 'Andres Serra Francisco' δεν βρέθηκε.

Fetching Wikipedia Data:  68%|██████▊   | 770/1126 [15:18<07:09,  1.21s/it]

Wikipedia Data saved: ./artist_wiki_pages/Aleksandr_Deyneka.json

Fetching Wikipedia Data:  68%|██████▊   | 771/1126 [15:19<07:10,  1.21s/it]

Wikipedia Data saved: ./artist_wiki_pages/Józef_Chełmoński.json

Fetching Wikipedia Data:  69%|██████▊   | 772/1126 [15:21<08:01,  1.36s/it]

Wikipedia Data saved: ./artist_wiki_pages/Joseph_Farquharson.json

Fetching Wikipedia Data:  69%|██████▊   | 773/1126 [15:22<07:29,  1.27s/it]

Wikipedia Data saved: ./artist_wiki_pages/Kitty_Lange_Kielland.json

Fetching Wikipedia Data:  69%|██████▊   | 774/1126 [15:24<08:20,  1.42s/it]

Η σελίδα 'Ladell Edward' δεν βρέθηκε.

Fetching Wikipedia Data:  69%|██████▉   | 775/1126 [15:25<07:05,  1.21s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jules_Breton.json

Fetching Wikipedia Data:  69%|██████▉   | 776/1126 [15:26<06:48,  1.17s/it]

Wikipedia Data saved: ./artist_wiki_pages/José_Ferraz_de_Almeida_Júnior.json

Fetching Wikipedia Data:  69%|██████▉   | 777/1126 [15:27<06:38,  1.14s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jules_Bastien-Lepage.json

Fetching Wikipedia Data:  69%|██████▉   | 778/1126 [15:28<06:30,  1.12s/it]

Wikipedia Data saved: ./artist_wiki_pages/Nikolai_Dmitriyevich_Kuznetsov_(painter).json

Fetching Wikipedia Data:  69%|██████▉   | 779/1126 [15:30<07:39,  1.33s/it]

Wikipedia Data saved: ./artist_wiki_pages/Achille_D'Orsi.json

Fetching Wikipedia Data:  69%|██████▉   | 780/1126 [15:31<07:12,  1.25s/it]

Wikipedia Data saved: ./artist_wiki_pages/Joaquín_Agrasot.json

Fetching Wikipedia Data:  69%|██████▉   | 781/1126 [15:32<06:52,  1.20s/it]

Wikipedia Data saved: ./artist_wiki_pages/Zakar_Zakarian.json

Fetching Wikipedia Data:  69%|██████▉   | 782/1126 [15:33<06:37,  1.16s/it]

Wikipedia Data saved: ./artist_wiki_pages/Vasily_Perov.json

Fetching Wikipedia Data:  70%|██████▉   | 783/1126 [15:34<06:29,  1.13s/it]

Wikipedia Data saved: ./artist_wiki_pages/David_Bates_(artist).json

Fetching Wikipedia Data:  70%|██████▉   | 784/1126 [15:35<06:55,  1.21s/it]

Wikipedia Data saved: ./artist_wiki_pages/August_von_Pettenkofen.json

Fetching Wikipedia Data:  70%|██████▉   | 785/1126 [15:36<06:42,  1.18s/it]

Wikipedia Data saved: ./artist_wiki_pages/Charles-François_Daubigny.json

Fetching Wikipedia Data:  70%|██████▉   | 786/1126 [15:37<06:32,  1.16s/it]

Wikipedia Data saved: ./artist_wiki_pages/Giuseppe_Abbati.json

Fetching Wikipedia Data:  70%|██████▉   | 787/1126 [15:39<06:23,  1.13s/it]

Wikipedia Data saved: ./artist_wiki_pages/Charles_Garabed_Atamian.json

Fetching Wikipedia Data:  70%|██████▉   | 788/1126 [15:40<07:05,  1.26s/it]

Η σελίδα 'Consuelo Hernández (pintora)' δεν βρέθηκε.

Fetching Wikipedia Data:  70%|███████   | 789/1126 [15:41<06:07,  1.09s/it]

Wikipedia Data saved: ./artist_wiki_pages/Mikhail_Lebedev.json

Fetching Wikipedia Data:  70%|███████   | 790/1126 [15:43<07:27,  1.33s/it]

Wikipedia Data saved: ./artist_wiki_pages/Nikolai_Yaroshenko.json

Fetching Wikipedia Data:  70%|███████   | 791/1126 [15:44<07:13,  1.29s/it]

Wikipedia Data saved: ./artist_wiki_pages/Meijer_de_Haan.json

Fetching Wikipedia Data:  70%|███████   | 792/1126 [15:45<06:50,  1.23s/it]

Η σελίδα 'Kremer Veniamin' δεν βρέθηκε.

Fetching Wikipedia Data:  70%|███████   | 793/1126 [15:46<05:56,  1.07s/it]

Wikipedia Data saved: ./artist_wiki_pages/Constant_Troyon.json

Fetching Wikipedia Data:  71%|███████   | 794/1126 [15:47<05:55,  1.07s/it]

Wikipedia Data saved: ./artist_wiki_pages/John_O'Connor_(painter).json

Fetching Wikipedia Data:  71%|███████   | 795/1126 [15:48<06:43,  1.22s/it]

Wikipedia Data saved: ./artist_wiki_pages/Ivan_Shishkin.json

Fetching Wikipedia Data:  71%|███████   | 796/1126 [15:49<06:29,  1.18s/it]

Wikipedia Data saved: ./artist_wiki_pages/Grigoriy_Myasoyedov.json

Fetching Wikipedia Data:  71%|███████   | 797/1126 [15:50<06:18,  1.15s/it]

Wikipedia Data saved: ./artist_wiki_pages/Charles_Jacque.json

Fetching Wikipedia Data:  71%|███████   | 798/1126 [15:52<07:21,  1.34s/it]

Wikipedia Data saved: ./artist_wiki_pages/Vladimir_Makovsky.json

Fetching Wikipedia Data:  71%|███████   | 799/1126 [15:54<07:48,  1.43s/it]

Wikipedia Data saved: ./artist_wiki_pages/Briton_Rivière.json

Fetching Wikipedia Data:  71%|███████   | 800/1126 [15:56<08:15,  1.52s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jean-Baptiste-Siméon_Chardin.json

Fetching Wikipedia Data:  71%|███████   | 801/1126 [15:57<07:28,  1.38s/it]

Wikipedia Data saved: ./artist_wiki_pages/Arshak_Fetvadjian.json

Fetching Wikipedia Data:  71%|███████   | 802/1126 [15:59<08:12,  1.52s/it]

Wikipedia Data saved: ./artist_wiki_pages/Louis_Hayet.json

Fetching Wikipedia Data:  71%|███████▏  | 803/1126 [16:00<07:26,  1.38s/it]

Wikipedia Data saved: ./artist_wiki_pages/Le_Pho.json

Fetching Wikipedia Data:  71%|███████▏  | 804/1126 [16:01<06:54,  1.29s/it]

Wikipedia Data saved: ./artist_wiki_pages/Gustave_Loiseau.json

Fetching Wikipedia Data:  71%|███████▏  | 805/1126 [16:02<06:45,  1.26s/it]

Wikipedia Data saved: ./artist_wiki_pages/Edvard_Weie.json

Fetching Wikipedia Data:  72%|███████▏  | 806/1126 [16:03<06:23,  1.20s/it]

Η σελίδα 'Constantin Piliuță' δεν βρέθηκε.

Fetching Wikipedia Data:  72%|███████▏  | 807/1126 [16:04<05:34,  1.05s/it]

Η σελίδα 'Gaifedjyan Vahram' δεν βρέθηκε.

Fetching Wikipedia Data:  72%|███████▏  | 808/1126 [16:04<05:00,  1.06it/s]

Wikipedia Data saved: ./artist_wiki_pages/George_Washington_Lambert.json

Fetching Wikipedia Data:  72%|███████▏  | 809/1126 [16:07<07:45,  1.47s/it]

Wikipedia Data saved: ./artist_wiki_pages/Grace_Cossington_Smith.json

Fetching Wikipedia Data:  72%|███████▏  | 810/1126 [16:08<07:12,  1.37s/it]

Wikipedia Data saved: ./artist_wiki_pages/Kuzma_Petrov-Vodkin.json

Fetching Wikipedia Data:  72%|███████▏  | 811/1126 [16:10<08:03,  1.53s/it]

Wikipedia Data saved: ./artist_wiki_pages/Medardo_Rosso.json

Fetching Wikipedia Data:  72%|███████▏  | 812/1126 [16:12<08:29,  1.62s/it]

Η σελίδα 'Lerman Zoe' δεν βρέθηκε.

Fetching Wikipedia Data:  72%|███████▏  | 813/1126 [16:13<07:00,  1.34s/it]

Wikipedia Data saved: ./artist_wiki_pages/Henri_Manguin.json

Fetching Wikipedia Data:  72%|███████▏  | 814/1126 [16:14<06:32,  1.26s/it]

Wikipedia Data saved: ./artist_wiki_pages/Albert_Gleizes.json

Fetching Wikipedia Data:  72%|███████▏  | 815/1126 [16:15<06:29,  1.25s/it]

Wikipedia Data saved: ./artist_wiki_pages/Henri_Rousseau.json

Fetching Wikipedia Data:  72%|███████▏  | 816/1126 [16:16<06:22,  1.23s/it]

Wikipedia Data saved: ./artist_wiki_pages/Maurice_de_Vlaminck.json

Fetching Wikipedia Data:  73%|███████▎  | 817/1126 [16:17<06:05,  1.18s/it]

Wikipedia Data saved: ./artist_wiki_pages/Aldemir_Martins.json

Fetching Wikipedia Data:  73%|███████▎  | 818/1126 [16:19<06:48,  1.33s/it]

Wikipedia Data saved: ./artist_wiki_pages/Bice_Lazzari.json

Fetching Wikipedia Data:  73%|███████▎  | 819/1126 [16:20<07:16,  1.42s/it]

Wikipedia Data saved: ./artist_wiki_pages/Maurice_Denis.json

Fetching Wikipedia Data:  73%|███████▎  | 820/1126 [16:22<06:52,  1.35s/it]

Wikipedia Data saved: ./artist_wiki_pages/Émile_Bernard.json

Fetching Wikipedia Data:  73%|███████▎  | 821/1126 [16:23<06:24,  1.26s/it]

Wikipedia Data saved: ./artist_wiki_pages/Dumitru_Ghiaţă.json

Fetching Wikipedia Data:  73%|███████▎  | 822/1126 [16:24<06:04,  1.20s/it]

Wikipedia Data saved: ./artist_wiki_pages/Édouard_Vuillard.json

Fetching Wikipedia Data:  73%|███████▎  | 823/1126 [16:25<05:59,  1.19s/it]

Wikipedia Data saved: ./artist_wiki_pages/Frances_Hodgkins.json

Fetching Wikipedia Data:  73%|███████▎  | 824/1126 [16:26<05:47,  1.15s/it]

Wikipedia Data saved: ./artist_wiki_pages/Henri_Le_Fauconnier.json

Fetching Wikipedia Data:  73%|███████▎  | 825/1126 [16:28<06:47,  1.35s/it]

Wikipedia Data saved: ./artist_wiki_pages/Georges_Vantongerloo.json

Fetching Wikipedia Data:  73%|███████▎  | 826/1126 [16:29<06:21,  1.27s/it]

Η σελίδα 'Fermanyan Gohar' δεν βρέθηκε.

Fetching Wikipedia Data:  73%|███████▎  | 827/1126 [16:30<05:28,  1.10s/it]

Wikipedia Data saved: ./artist_wiki_pages/Trần_Văn_Cẩn.json

Fetching Wikipedia Data:  74%|███████▎  | 828/1126 [16:31<06:06,  1.23s/it]

Wikipedia Data saved: ./artist_wiki_pages/Edgar_Chahine.json

Fetching Wikipedia Data:  74%|███████▎  | 829/1126 [16:33<06:43,  1.36s/it]

Wikipedia Data saved: ./artist_wiki_pages/Christopher_Wood_(English_painter).json

Fetching Wikipedia Data:  74%|███████▎  | 830/1126 [16:35<07:19,  1.48s/it]

Wikipedia Data saved: ./artist_wiki_pages/Rik_Wouters.json

Fetching Wikipedia Data:  74%|███████▍  | 831/1126 [16:37<08:04,  1.64s/it]

Wikipedia Data saved: ./artist_wiki_pages/Vladimir_Dimitrov.json

Fetching Wikipedia Data:  74%|███████▍  | 832/1126 [16:38<08:07,  1.66s/it]

Wikipedia Data saved: ./artist_wiki_pages/Phelan_Gibb.json

Fetching Wikipedia Data:  74%|███████▍  | 833/1126 [16:39<07:13,  1.48s/it]

Wikipedia Data saved: ./artist_wiki_pages/Roderic_O'Conor.json

Fetching Wikipedia Data:  74%|███████▍  | 834/1126 [16:41<07:34,  1.56s/it]

Wikipedia Data saved: ./artist_wiki_pages/Agnes_Lawrence_Pelton.json

Fetching Wikipedia Data:  74%|███████▍  | 835/1126 [16:43<07:55,  1.63s/it]

Wikipedia Data saved: ./artist_wiki_pages/Eduardo_Viana.json

Fetching Wikipedia Data:  74%|███████▍  | 836/1126 [16:44<07:05,  1.47s/it]

Wikipedia Data saved: ./artist_wiki_pages/Maria_Lai.json

Fetching Wikipedia Data:  74%|███████▍  | 837/1126 [16:46<07:34,  1.57s/it]

Wikipedia Data saved: ./artist_wiki_pages/Nikola_Martinoski.json

Fetching Wikipedia Data:  74%|███████▍  | 838/1126 [16:47<06:55,  1.44s/it]

Η σελίδα 'Tanev Nikola' δεν βρέθηκε.

Fetching Wikipedia Data:  75%|███████▍  | 839/1126 [16:48<05:50,  1.22s/it]

Wikipedia Data saved: ./artist_wiki_pages/Nina_Arbore.json

Fetching Wikipedia Data:  75%|███████▍  | 840/1126 [16:49<06:24,  1.34s/it]

Wikipedia Data saved: ./artist_wiki_pages/Roger_Bissière.json

Fetching Wikipedia Data:  75%|███████▍  | 841/1126 [16:51<06:57,  1.46s/it]

Wikipedia Data saved: ./artist_wiki_pages/Bertalan_Pór.json

Fetching Wikipedia Data:  75%|███████▍  | 842/1126 [16:52<06:57,  1.47s/it]

Η σελίδα 'Hidalgo Oses Carmen' δεν βρέθηκε.

Fetching Wikipedia Data:  75%|███████▍  | 843/1126 [16:53<05:50,  1.24s/it]

Η σελίδα 'Balacescu Demetriade Lucia' δεν βρέθηκε.

Fetching Wikipedia Data:  75%|███████▍  | 844/1126 [16:54<05:03,  1.08s/it]

Wikipedia Data saved: ./artist_wiki_pages/Vanessa_Bell.json

Fetching Wikipedia Data:  75%|███████▌  | 845/1126 [16:55<05:03,  1.08s/it]

Wikipedia Data saved: ./artist_wiki_pages/William_Orpen.json

Fetching Wikipedia Data:  75%|███████▌  | 846/1126 [16:56<05:09,  1.10s/it]

Wikipedia Data saved: ./artist_wiki_pages/Eugeniusz_Zak.json

Fetching Wikipedia Data:  75%|███████▌  | 847/1126 [16:57<05:06,  1.10s/it]

Wikipedia Data saved: ./artist_wiki_pages/Suzanne_Valadon.json

Fetching Wikipedia Data:  75%|███████▌  | 848/1126 [16:58<05:11,  1.12s/it]

Wikipedia Data saved: ./artist_wiki_pages/Ronnie_Landfield.json

Fetching Wikipedia Data:  75%|███████▌  | 849/1126 [17:00<06:25,  1.39s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jules-Alexandre_Grün.json

Fetching Wikipedia Data:  75%|███████▌  | 850/1126 [17:02<06:41,  1.46s/it]

Wikipedia Data saved: ./artist_wiki_pages/Paul_Henry_(painter).json

Fetching Wikipedia Data:  76%|███████▌  | 851/1126 [17:03<06:08,  1.34s/it]

Wikipedia Data saved: ./artist_wiki_pages/Konstantin_Gorbatov.json

Fetching Wikipedia Data:  76%|███████▌  | 852/1126 [17:05<06:36,  1.45s/it]

Wikipedia Data saved: ./artist_wiki_pages/Antonio_Sicurezza.json

Fetching Wikipedia Data:  76%|███████▌  | 853/1126 [17:06<06:51,  1.51s/it]

Wikipedia Data saved: ./artist_wiki_pages/Agnes_Goodsir.json

Fetching Wikipedia Data:  76%|███████▌  | 854/1126 [17:08<07:09,  1.58s/it]

Wikipedia Data saved: ./artist_wiki_pages/Victor_Pasmore.json

Fetching Wikipedia Data:  76%|███████▌  | 855/1126 [17:10<07:23,  1.64s/it]

Wikipedia Data saved: ./artist_wiki_pages/Édouard_Cortès.json

Fetching Wikipedia Data:  76%|███████▌  | 856/1126 [17:11<06:36,  1.47s/it]

Wikipedia Data saved: ./artist_wiki_pages/Albert_Marquet.json

Fetching Wikipedia Data:  76%|███████▌  | 857/1126 [17:13<07:09,  1.60s/it]

Wikipedia Data saved: ./artist_wiki_pages/Nadežda_Petrović.json

Fetching Wikipedia Data:  76%|███████▌  | 858/1126 [17:14<06:25,  1.44s/it]

Wikipedia Data saved: ./artist_wiki_pages/Emily_Carr.json

Fetching Wikipedia Data:  76%|███████▋  | 859/1126 [17:15<06:02,  1.36s/it]

Η σελίδα 'Bissier Julius' δεν βρέθηκε.

Fetching Wikipedia Data:  76%|███████▋  | 860/1126 [17:16<05:08,  1.16s/it]

Wikipedia Data saved: ./artist_wiki_pages/Tarsila_do_Amaral.json

Fetching Wikipedia Data:  76%|███████▋  | 861/1126 [17:17<05:06,  1.16s/it]

Wikipedia Data saved: ./artist_wiki_pages/Fernando_Garcia_Ponce.json

Fetching Wikipedia Data:  77%|███████▋  | 862/1126 [17:19<05:48,  1.32s/it]

Wikipedia Data saved: ./artist_wiki_pages/Maurice_Utrillo.json

Fetching Wikipedia Data:  77%|███████▋  | 863/1126 [17:20<05:27,  1.24s/it]

Wikipedia Data saved: ./artist_wiki_pages/Gwen_John.json

Fetching Wikipedia Data:  77%|███████▋  | 864/1126 [17:21<05:17,  1.21s/it]

Wikipedia Data saved: ./artist_wiki_pages/Giorgio_Morandi.json

Fetching Wikipedia Data:  77%|███████▋  | 865/1126 [17:23<06:19,  1.45s/it]

Wikipedia Data saved: ./artist_wiki_pages/Roger_Fry.json

Fetching Wikipedia Data:  77%|███████▋  | 866/1126 [17:24<05:55,  1.37s/it]

Wikipedia Data saved: ./artist_wiki_pages/Winifred_Nicholson.json

Fetching Wikipedia Data:  77%|███████▋  | 867/1126 [17:25<05:33,  1.29s/it]

Wikipedia Data saved: ./artist_wiki_pages/Lili_Elbe.json

Fetching Wikipedia Data:  77%|███████▋  | 868/1126 [17:28<07:24,  1.72s/it]

Wikipedia Data saved: ./artist_wiki_pages/Pierre_Bonnard.json

Fetching Wikipedia Data:  77%|███████▋  | 869/1126 [17:29<06:38,  1.55s/it]

Wikipedia Data saved: ./artist_wiki_pages/André_Lhote.json

Fetching Wikipedia Data:  77%|███████▋  | 870/1126 [17:31<07:03,  1.65s/it]

Wikipedia Data saved: ./artist_wiki_pages/Leon_Kroll.json

Fetching Wikipedia Data:  77%|███████▋  | 871/1126 [17:33<07:12,  1.70s/it]

Wikipedia Data saved: ./artist_wiki_pages/Emilio_Pettoruti.json

Fetching Wikipedia Data:  77%|███████▋  | 872/1126 [17:35<07:18,  1.73s/it]

Wikipedia Data saved: ./artist_wiki_pages/Ryuzaburo_Umehara.json

Fetching Wikipedia Data:  78%|███████▊  | 873/1126 [17:36<07:29,  1.78s/it]

Wikipedia Data saved: ./artist_wiki_pages/Josefa_de_Óbidos.json

Fetching Wikipedia Data:  78%|███████▊  | 874/1126 [17:37<06:35,  1.57s/it]

Wikipedia Data saved: ./artist_wiki_pages/Luca_Giordano.json

Fetching Wikipedia Data:  78%|███████▊  | 875/1126 [17:39<05:56,  1.42s/it]

Wikipedia Data saved: ./artist_wiki_pages/Willem_Cornelisz_Duyster.json

Fetching Wikipedia Data:  78%|███████▊  | 876/1126 [17:40<05:28,  1.31s/it]

Wikipedia Data saved: ./artist_wiki_pages/Francesco_Solimena.json

Fetching Wikipedia Data:  78%|███████▊  | 877/1126 [17:42<06:11,  1.49s/it]

Wikipedia Data saved: ./artist_wiki_pages/Georges_Lallemand.json

Fetching Wikipedia Data:  78%|███████▊  | 878/1126 [17:43<05:40,  1.37s/it]

Wikipedia Data saved: ./artist_wiki_pages/Anthony_van_Dyck.json

Fetching Wikipedia Data:  78%|███████▊  | 879/1126 [17:44<05:25,  1.32s/it]

Wikipedia Data saved: ./artist_wiki_pages/Theodoor_van_Thulden.json

Fetching Wikipedia Data:  78%|███████▊  | 880/1126 [17:45<05:04,  1.24s/it]

Wikipedia Data saved: ./artist_wiki_pages/Adriaen_van_de_Velde.json

Fetching Wikipedia Data:  78%|███████▊  | 881/1126 [17:46<04:51,  1.19s/it]

Wikipedia Data saved: ./artist_wiki_pages/Giuseppe_Crespi.json

Fetching Wikipedia Data:  78%|███████▊  | 882/1126 [17:48<05:34,  1.37s/it]

Wikipedia Data saved: ./artist_wiki_pages/Eustache_Le_Sueur.json

Fetching Wikipedia Data:  78%|███████▊  | 883/1126 [17:49<05:12,  1.28s/it]

Wikipedia Data saved: ./artist_wiki_pages/Richard_Anuszkiewicz.json

Fetching Wikipedia Data:  79%|███████▊  | 884/1126 [17:50<04:54,  1.22s/it]

Wikipedia Data saved: ./artist_wiki_pages/Francisco_Herrera_the_Elder.json

Fetching Wikipedia Data:  79%|███████▊  | 885/1126 [17:51<04:42,  1.17s/it]

Wikipedia Data saved: ./artist_wiki_pages/Joshua_Reynolds.json

Fetching Wikipedia Data:  79%|███████▊  | 886/1126 [17:54<06:26,  1.61s/it]

Wikipedia Data saved: ./artist_wiki_pages/Juriaen_van_Streeck.json

Fetching Wikipedia Data:  79%|███████▉  | 887/1126 [17:55<05:47,  1.45s/it]

Wikipedia Data saved: ./artist_wiki_pages/Mario_Nuzzi.json

Fetching Wikipedia Data:  79%|███████▉  | 888/1126 [17:56<05:21,  1.35s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jan_Dirksz_Both.json

Fetching Wikipedia Data:  79%|███████▉  | 889/1126 [17:57<04:59,  1.27s/it]

Wikipedia Data saved: ./artist_wiki_pages/Gerard_van_Honthorst.json

Fetching Wikipedia Data:  79%|███████▉  | 890/1126 [17:58<04:47,  1.22s/it]

Wikipedia Data saved: ./artist_wiki_pages/Charles_Le_Brun.json

Fetching Wikipedia Data:  79%|███████▉  | 891/1126 [17:59<04:41,  1.20s/it]

Wikipedia Data saved: ./artist_wiki_pages/Thomas_Hardy_(English_painter).json

Fetching Wikipedia Data:  79%|███████▉  | 892/1126 [18:01<05:11,  1.33s/it]

Wikipedia Data saved: ./artist_wiki_pages/Wenceslaus_Hollar.json

Fetching Wikipedia Data:  79%|███████▉  | 893/1126 [18:02<04:52,  1.25s/it]

Wikipedia Data saved: ./artist_wiki_pages/Juriaen_Pool.json

Fetching Wikipedia Data:  79%|███████▉  | 894/1126 [18:03<04:36,  1.19s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jan_Brueghel_the_Elder.json

Fetching Wikipedia Data:  79%|███████▉  | 895/1126 [18:04<04:43,  1.23s/it]

Wikipedia Data saved: ./artist_wiki_pages/Nicolas_Tournier.json

Fetching Wikipedia Data:  80%|███████▉  | 896/1126 [18:06<05:23,  1.41s/it]

Wikipedia Data saved: ./artist_wiki_pages/Agostino_Tassi.json

Fetching Wikipedia Data:  80%|███████▉  | 897/1126 [18:08<05:32,  1.45s/it]

Wikipedia Data saved: ./artist_wiki_pages/Judith_Leyster.json

Fetching Wikipedia Data:  80%|███████▉  | 898/1126 [18:09<05:06,  1.34s/it]

Η σελίδα 'Kondzelevych Yov' δεν βρέθηκε.

Fetching Wikipedia Data:  80%|███████▉  | 899/1126 [18:09<04:20,  1.15s/it]

Wikipedia Data saved: ./artist_wiki_pages/Osias_Beert.json

Fetching Wikipedia Data:  80%|███████▉  | 900/1126 [18:10<04:15,  1.13s/it]

Wikipedia Data saved: ./artist_wiki_pages/Cornelis_de_Vos.json

Fetching Wikipedia Data:  80%|████████  | 901/1126 [18:12<05:00,  1.34s/it]

Wikipedia Data saved: ./artist_wiki_pages/Sebastiano_Conca.json

Fetching Wikipedia Data:  80%|████████  | 902/1126 [18:13<04:44,  1.27s/it]

Wikipedia Data saved: ./artist_wiki_pages/Adriaen_van_de_Venne.json

Fetching Wikipedia Data:  80%|████████  | 903/1126 [18:15<04:59,  1.34s/it]

Wikipedia Data saved: ./artist_wiki_pages/Melchior_d'Hondecoeter.json

Fetching Wikipedia Data:  80%|████████  | 904/1126 [18:16<04:41,  1.27s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jan_Steen.json

Fetching Wikipedia Data:  80%|████████  | 905/1126 [18:17<04:27,  1.21s/it]

Wikipedia Data saved: ./artist_wiki_pages/Adam_Frans_van_der_Meulen.json

Fetching Wikipedia Data:  80%|████████  | 906/1126 [18:18<04:17,  1.17s/it]

Wikipedia Data saved: ./artist_wiki_pages/Michiel_van_Musscher.json

Fetching Wikipedia Data:  81%|████████  | 907/1126 [18:20<04:50,  1.32s/it]

Wikipedia Data saved: ./artist_wiki_pages/Esaias_van_de_Velde.json

Fetching Wikipedia Data:  81%|████████  | 908/1126 [18:21<04:32,  1.25s/it]

Wikipedia Data saved: ./artist_wiki_pages/Pieter_Codde.json

Fetching Wikipedia Data:  81%|████████  | 909/1126 [18:22<04:26,  1.23s/it]

Wikipedia Data saved: ./artist_wiki_pages/Gerrit_Dou.json

Fetching Wikipedia Data:  81%|████████  | 910/1126 [18:23<04:22,  1.21s/it]

Wikipedia Data saved: ./artist_wiki_pages/Peter_Paul_Rubens.json

Fetching Wikipedia Data:  81%|████████  | 911/1126 [18:24<04:20,  1.21s/it]

Wikipedia Data saved: ./artist_wiki_pages/Rembrandt.json

Fetching Wikipedia Data:  81%|████████  | 912/1126 [18:26<04:27,  1.25s/it]

Wikipedia Data saved: ./artist_wiki_pages/Frans_Snyders.json

Fetching Wikipedia Data:  81%|████████  | 913/1126 [18:28<05:01,  1.41s/it]

Wikipedia Data saved: ./artist_wiki_pages/Simon_de_Vlieger.json

Fetching Wikipedia Data:  81%|████████  | 914/1126 [18:29<04:38,  1.32s/it]

Wikipedia Data saved: ./artist_wiki_pages/Bernardo_Strozzi.json

Fetching Wikipedia Data:  81%|████████▏ | 915/1126 [18:30<05:08,  1.46s/it]

Wikipedia Data saved: ./artist_wiki_pages/Pieter_Claesz.json

Fetching Wikipedia Data:  81%|████████▏ | 916/1126 [18:32<04:42,  1.35s/it]

Wikipedia Data saved: ./artist_wiki_pages/Aleksey_Antropov.json

Fetching Wikipedia Data:  81%|████████▏ | 917/1126 [18:33<04:23,  1.26s/it]

Wikipedia Data saved: ./artist_wiki_pages/Francisco_Zurbarán.json

Fetching Wikipedia Data:  82%|████████▏ | 918/1126 [18:34<04:15,  1.23s/it]

Wikipedia Data saved: ./artist_wiki_pages/Giovanni_Paolo_Pannini.json

Fetching Wikipedia Data:  82%|████████▏ | 919/1126 [18:35<04:04,  1.18s/it]

Wikipedia Data saved: ./artist_wiki_pages/Alonzo_Cano.json

Fetching Wikipedia Data:  82%|████████▏ | 920/1126 [18:36<03:57,  1.15s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jacob_Jordaens.json

Fetching Wikipedia Data:  82%|████████▏ | 921/1126 [18:37<03:56,  1.16s/it]

Wikipedia Data saved: ./artist_wiki_pages/Hercules_Seghers.json

Fetching Wikipedia Data:  82%|████████▏ | 922/1126 [18:38<03:49,  1.12s/it]

Wikipedia Data saved: ./artist_wiki_pages/Alexey_Zubov.json

Fetching Wikipedia Data:  82%|████████▏ | 923/1126 [18:39<03:44,  1.11s/it]

Wikipedia Data saved: ./artist_wiki_pages/David_Bailly.json

Fetching Wikipedia Data:  82%|████████▏ | 924/1126 [18:40<03:41,  1.10s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jan_Miense_Molenaer.json

Fetching Wikipedia Data:  82%|████████▏ | 925/1126 [18:41<03:40,  1.10s/it]

Wikipedia Data saved: ./artist_wiki_pages/Clara_Peeters.json

Fetching Wikipedia Data:  82%|████████▏ | 926/1126 [18:42<03:39,  1.10s/it]

Wikipedia Data saved: ./artist_wiki_pages/Marcos_Zapata.json

Fetching Wikipedia Data:  82%|████████▏ | 927/1126 [18:44<03:38,  1.10s/it]

Wikipedia Data saved: ./artist_wiki_pages/Claudio_Coello.json

Fetching Wikipedia Data:  82%|████████▏ | 928/1126 [18:45<03:35,  1.09s/it]

Wikipedia Data saved: ./artist_wiki_pages/Joseph-Marie_Vien.json

Fetching Wikipedia Data:  83%|████████▎ | 929/1126 [18:46<04:16,  1.30s/it]

Wikipedia Data saved: ./artist_wiki_pages/Giovanni_Battista_Salvi_da_Sassoferrato.json

Fetching Wikipedia Data:  83%|████████▎ | 930/1126 [18:48<04:44,  1.45s/it]

Η σελίδα 'Luzan Jose' δεν βρέθηκε.

Fetching Wikipedia Data:  83%|████████▎ | 931/1126 [18:49<03:59,  1.23s/it]

Wikipedia Data saved: ./artist_wiki_pages/Willem_Isaacsz._van_Swanenburg.json

Fetching Wikipedia Data:  83%|████████▎ | 932/1126 [18:50<03:48,  1.18s/it]

Wikipedia Data saved: ./artist_wiki_pages/Isaac_van_Ostade.json

Fetching Wikipedia Data:  83%|████████▎ | 933/1126 [18:51<03:39,  1.14s/it]

Wikipedia Data saved: ./artist_wiki_pages/David_Teniers_the_Younger.json

Fetching Wikipedia Data:  83%|████████▎ | 934/1126 [18:52<03:50,  1.20s/it]

Wikipedia Data saved: ./artist_wiki_pages/Willem_Kalf.json

Fetching Wikipedia Data:  83%|████████▎ | 935/1126 [18:54<04:16,  1.34s/it]

Wikipedia Data saved: ./artist_wiki_pages/Francesc_Ribalta.json

Fetching Wikipedia Data:  83%|████████▎ | 936/1126 [18:55<04:00,  1.26s/it]

Wikipedia Data saved: ./artist_wiki_pages/Otto_Marseus_van_Schrieck.json

Fetching Wikipedia Data:  83%|████████▎ | 937/1126 [18:56<03:47,  1.20s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jan_Luyken.json

Fetching Wikipedia Data:  83%|████████▎ | 938/1126 [18:57<03:38,  1.16s/it]

Wikipedia Data saved: ./artist_wiki_pages/Rachel_Ruysch.json

Fetching Wikipedia Data:  83%|████████▎ | 939/1126 [18:59<04:14,  1.36s/it]

Wikipedia Data saved: ./artist_wiki_pages/Samuel_Dirksz_van_Hoogstraten.json

Fetching Wikipedia Data:  83%|████████▎ | 940/1126 [19:00<03:55,  1.27s/it]

Wikipedia Data saved: ./artist_wiki_pages/Hyacinthe_Rigaud.json

Fetching Wikipedia Data:  84%|████████▎ | 941/1126 [19:03<04:59,  1.62s/it]

Wikipedia Data saved: ./artist_wiki_pages/Bartolomé_Esteban_Murillo.json

Fetching Wikipedia Data:  84%|████████▎ | 942/1126 [19:04<04:26,  1.45s/it]

Η σελίδα 'Elsheimer Adam' δεν βρέθηκε.

Fetching Wikipedia Data:  84%|████████▎ | 943/1126 [19:04<03:45,  1.23s/it]

Wikipedia Data saved: ./artist_wiki_pages/Adriaen_van_Ostade.json

Fetching Wikipedia Data:  84%|████████▍ | 944/1126 [19:05<03:37,  1.19s/it]

Wikipedia Data saved: ./artist_wiki_pages/Sébastien_Bourdon.json

Fetching Wikipedia Data:  84%|████████▍ | 945/1126 [19:07<03:29,  1.16s/it]

Wikipedia Data saved: ./artist_wiki_pages/Frans_Hals.json

Fetching Wikipedia Data:  84%|████████▍ | 946/1126 [19:08<03:29,  1.16s/it]

Wikipedia Data saved: ./artist_wiki_pages/Mattia_Preti.json

Fetching Wikipedia Data:  84%|████████▍ | 947/1126 [19:09<03:25,  1.15s/it]

Wikipedia Data saved: ./artist_wiki_pages/Placido_Costanzi.json

Fetching Wikipedia Data:  84%|████████▍ | 948/1126 [19:10<03:21,  1.13s/it]

Wikipedia Data saved: ./artist_wiki_pages/Miguel_Cabrera_(painter).json

Fetching Wikipedia Data:  84%|████████▍ | 949/1126 [19:11<03:41,  1.25s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jacques_Stella.json

Fetching Wikipedia Data:  84%|████████▍ | 950/1126 [19:13<04:05,  1.40s/it]

Wikipedia Data saved: ./artist_wiki_pages/Gerard_ter_Borch.json

Fetching Wikipedia Data:  84%|████████▍ | 951/1126 [19:14<03:48,  1.31s/it]

Wikipedia Data saved: ./artist_wiki_pages/Joan_Blaeu.json

Fetching Wikipedia Data:  85%|████████▍ | 952/1126 [19:16<04:17,  1.48s/it]

Wikipedia Data saved: ./artist_wiki_pages/Carel_Fabritius.json

Fetching Wikipedia Data:  85%|████████▍ | 953/1126 [19:18<04:55,  1.71s/it]

Wikipedia Data saved: ./artist_wiki_pages/Nicolaes_Maes.json

Fetching Wikipedia Data:  85%|████████▍ | 954/1126 [19:19<04:21,  1.52s/it]

Wikipedia Data saved: ./artist_wiki_pages/Juan_Bautista_Maíno.json

Fetching Wikipedia Data:  85%|████████▍ | 955/1126 [19:21<03:57,  1.39s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jacob_Isaakszoon_van_Ruysdael.json

Fetching Wikipedia Data:  85%|████████▍ | 956/1126 [19:22<03:52,  1.37s/it]

Wikipedia Data saved: ./artist_wiki_pages/Simon_Ushakov.json

Fetching Wikipedia Data:  85%|████████▍ | 957/1126 [19:23<03:36,  1.28s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jan_Cossiers.json

Fetching Wikipedia Data:  85%|████████▌ | 958/1126 [19:25<03:58,  1.42s/it]

Wikipedia Data saved: ./artist_wiki_pages/Agostino_Carracci.json

Fetching Wikipedia Data:  85%|████████▌ | 959/1126 [19:26<03:38,  1.31s/it]

Wikipedia Data saved: ./artist_wiki_pages/Giovanni_Battista_Gaulli.json

Fetching Wikipedia Data:  85%|████████▌ | 960/1126 [19:27<03:25,  1.24s/it]

Wikipedia Data saved: ./artist_wiki_pages/Nikolaus_Knüpfer.json

Fetching Wikipedia Data:  85%|████████▌ | 961/1126 [19:28<03:17,  1.19s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jan_Lievens.json

Fetching Wikipedia Data:  85%|████████▌ | 962/1126 [19:29<03:11,  1.16s/it]

Wikipedia Data saved: ./artist_wiki_pages/Paul_and_Mattheus_Brill.json

Fetching Wikipedia Data:  86%|████████▌ | 963/1126 [19:31<03:36,  1.33s/it]

Wikipedia Data saved: ./artist_wiki_pages/Gian_Lorenzo_Bernini.json

Fetching Wikipedia Data:  86%|████████▌ | 964/1126 [19:34<04:54,  1.82s/it]

Wikipedia Data saved: ./artist_wiki_pages/Juan_de_Valdés_Leal.json

Fetching Wikipedia Data:  86%|████████▌ | 965/1126 [19:35<04:47,  1.79s/it]

Wikipedia Data saved: ./artist_wiki_pages/Caravaggio.json

Fetching Wikipedia Data:  86%|████████▌ | 966/1126 [19:38<05:37,  2.11s/it]

Wikipedia Data saved: ./artist_wiki_pages/Guercino.json

Fetching Wikipedia Data:  86%|████████▌ | 967/1126 [19:39<04:46,  1.80s/it]

Wikipedia Data saved: ./artist_wiki_pages/Abraham_Storck.json

Fetching Wikipedia Data:  86%|████████▌ | 968/1126 [19:40<04:09,  1.58s/it]

Η σελίδα 'Artemisia Gentileschi,' δεν βρέθηκε.

Fetching Wikipedia Data:  86%|████████▌ | 969/1126 [19:41<03:26,  1.32s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jusepe_de_Ribera.json

Fetching Wikipedia Data:  86%|████████▌ | 970/1126 [19:42<03:21,  1.29s/it]

Η σελίδα 'Procaccini Cesare Giulio' δεν βρέθηκε.

Fetching Wikipedia Data:  86%|████████▌ | 971/1126 [19:43<02:52,  1.11s/it]

Η σελίδα 'Goyen Van Jan' δεν βρέθηκε.

Fetching Wikipedia Data:  86%|████████▋ | 972/1126 [19:44<02:32,  1.01it/s]

Wikipedia Data saved: ./artist_wiki_pages/Hendrick_Cornelisz_Vroom.json

Fetching Wikipedia Data:  86%|████████▋ | 973/1126 [19:45<02:34,  1.01s/it]

Wikipedia Data saved: ./artist_wiki_pages/Francesco_Guardi.json

Fetching Wikipedia Data:  87%|████████▋ | 974/1126 [19:46<02:37,  1.04s/it]

Wikipedia Data saved: ./artist_wiki_pages/William_Hogarth.json

Fetching Wikipedia Data:  87%|████████▋ | 975/1126 [19:47<02:44,  1.09s/it]

Wikipedia Data saved: ./artist_wiki_pages/Pieter_de_Hooch.json

Fetching Wikipedia Data:  87%|████████▋ | 976/1126 [19:48<02:49,  1.13s/it]

Wikipedia Data saved: ./artist_wiki_pages/Marcello_Bacciarelli.json

Fetching Wikipedia Data:  87%|████████▋ | 977/1126 [19:50<03:21,  1.35s/it]

Wikipedia Data saved: ./artist_wiki_pages/Simon_Vouet.json

Fetching Wikipedia Data:  87%|████████▋ | 978/1126 [19:51<03:15,  1.32s/it]

Wikipedia Data saved: ./artist_wiki_pages/Pietro_da_Cortona.json

Fetching Wikipedia Data:  87%|████████▋ | 979/1126 [19:53<03:03,  1.25s/it]

Wikipedia Data saved: ./artist_wiki_pages/Isaac_Fuller.json

Fetching Wikipedia Data:  87%|████████▋ | 980/1126 [19:54<02:55,  1.20s/it]

Wikipedia Data saved: ./artist_wiki_pages/Cornelis_van_Noorde.json

Fetching Wikipedia Data:  87%|████████▋ | 981/1126 [19:55<03:18,  1.37s/it]

Wikipedia Data saved: ./artist_wiki_pages/Ferdinand_Bol.json

Fetching Wikipedia Data:  87%|████████▋ | 982/1126 [19:57<03:29,  1.45s/it]

Wikipedia Data saved: ./artist_wiki_pages/Juan_Carreño_de_Miranda.json

Fetching Wikipedia Data:  87%|████████▋ | 983/1126 [19:59<03:35,  1.51s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jacob_Peter_Gowy.json

Fetching Wikipedia Data:  87%|████████▋ | 984/1126 [20:00<03:16,  1.38s/it]

Wikipedia Data saved: ./artist_wiki_pages/Juan_van_der_Hamen.json

Fetching Wikipedia Data:  87%|████████▋ | 985/1126 [20:02<03:32,  1.50s/it]

Wikipedia Data saved: ./artist_wiki_pages/Adriaen_Brouwer.json

Fetching Wikipedia Data:  88%|████████▊ | 986/1126 [20:03<03:15,  1.39s/it]

Wikipedia Data saved: ./artist_wiki_pages/Salomon_Koninck.json

Fetching Wikipedia Data:  88%|████████▊ | 987/1126 [20:04<03:00,  1.30s/it]

Wikipedia Data saved: ./artist_wiki_pages/Aelbert_Cuyp.json

Fetching Wikipedia Data:  88%|████████▊ | 988/1126 [20:05<02:52,  1.25s/it]

Wikipedia Data saved: ./artist_wiki_pages/Thomas_Smith_(American_painter).json

Fetching Wikipedia Data:  88%|████████▊ | 989/1126 [20:06<02:45,  1.21s/it]

Wikipedia Data saved: ./artist_wiki_pages/Hendrick_Avercamp.json

Fetching Wikipedia Data:  88%|████████▊ | 990/1126 [20:08<03:06,  1.37s/it]

Wikipedia Data saved: ./artist_wiki_pages/Hendrick_ter_Brugghen.json

Fetching Wikipedia Data:  88%|████████▊ | 991/1126 [20:09<02:53,  1.29s/it]

Wikipedia Data saved: ./artist_wiki_pages/Manoel_da_Costa_Ataíde.json

Fetching Wikipedia Data:  88%|████████▊ | 992/1126 [20:10<02:58,  1.33s/it]

Wikipedia Data saved: ./artist_wiki_pages/Louise_Moillon.json

Fetching Wikipedia Data:  88%|████████▊ | 993/1126 [20:11<02:47,  1.26s/it]

Wikipedia Data saved: ./artist_wiki_pages/Claude_Deruet.json

Fetching Wikipedia Data:  88%|████████▊ | 994/1126 [20:12<02:39,  1.21s/it]

Wikipedia Data saved: ./artist_wiki_pages/Antoine_Pesne.json

Fetching Wikipedia Data:  88%|████████▊ | 995/1126 [20:14<02:32,  1.17s/it]

Wikipedia Data saved: ./artist_wiki_pages/Guido_Reni.json

Fetching Wikipedia Data:  88%|████████▊ | 996/1126 [20:16<03:14,  1.49s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jean_Baptiste_Vanmour.json

Fetching Wikipedia Data:  89%|████████▊ | 997/1126 [20:17<02:56,  1.37s/it]

Wikipedia Data saved: ./artist_wiki_pages/Karel_Škréta.json

Fetching Wikipedia Data:  89%|████████▊ | 998/1126 [20:19<03:07,  1.47s/it]

Wikipedia Data saved: ./artist_wiki_pages/Ivan_Nikitich_Nikitin.json

Fetching Wikipedia Data:  89%|████████▊ | 999/1126 [20:20<02:51,  1.35s/it]

Wikipedia Data saved: ./artist_wiki_pages/Giulia_Lama.json

Fetching Wikipedia Data:  89%|████████▉ | 1000/1126 [20:21<03:03,  1.46s/it]

Wikipedia Data saved: ./artist_wiki_pages/Tobias_Stranover.json

Fetching Wikipedia Data:  89%|████████▉ | 1001/1126 [20:22<02:48,  1.34s/it]

Wikipedia Data saved: ./artist_wiki_pages/Pieter_Jansz._Saenredam.json

Fetching Wikipedia Data:  89%|████████▉ | 1002/1126 [20:24<02:53,  1.40s/it]

Wikipedia Data saved: ./artist_wiki_pages/Johannes_Moreelse.json

Fetching Wikipedia Data:  89%|████████▉ | 1003/1126 [20:25<02:39,  1.30s/it]

Wikipedia Data saved: ./artist_wiki_pages/Cornelis_Norbertus_Gysbrechts.json

Fetching Wikipedia Data:  89%|████████▉ | 1004/1126 [20:27<02:56,  1.45s/it]

Wikipedia Data saved: ./artist_wiki_pages/Frans_van_Mieris_the_Elder.json

Fetching Wikipedia Data:  89%|████████▉ | 1005/1126 [20:29<03:09,  1.56s/it]

Wikipedia Data saved: ./artist_wiki_pages/John_Riley_(painter).json

Fetching Wikipedia Data:  89%|████████▉ | 1006/1126 [20:30<02:50,  1.42s/it]

Wikipedia Data saved: ./artist_wiki_pages/Canaletto.json

Fetching Wikipedia Data:  89%|████████▉ | 1007/1126 [20:31<02:37,  1.32s/it]

Wikipedia Data saved: ./artist_wiki_pages/Ivan_Rutkovych.json

Fetching Wikipedia Data:  90%|████████▉ | 1008/1126 [20:32<02:26,  1.24s/it]

Wikipedia Data saved: ./artist_wiki_pages/Le_Nain.json

Fetching Wikipedia Data:  90%|████████▉ | 1009/1126 [20:33<02:19,  1.19s/it]

Wikipedia Data saved: ./artist_wiki_pages/Claude_Lorrain.json

Fetching Wikipedia Data:  90%|████████▉ | 1010/1126 [20:35<02:54,  1.50s/it]

Wikipedia Data saved: ./artist_wiki_pages/Salvator_Rosa.json

Fetching Wikipedia Data:  90%|████████▉ | 1011/1126 [20:36<02:42,  1.41s/it]

Wikipedia Data saved: ./artist_wiki_pages/Johannes_Vermeer.json

Fetching Wikipedia Data:  90%|████████▉ | 1012/1126 [20:38<02:34,  1.35s/it]

Wikipedia Data saved: ./artist_wiki_pages/Anton_Raphael_Mengs.json

Fetching Wikipedia Data:  90%|████████▉ | 1013/1126 [20:39<02:24,  1.28s/it]

Wikipedia Data saved: ./artist_wiki_pages/Matthias_Stom.json

Fetching Wikipedia Data:  90%|█████████ | 1014/1126 [20:40<02:15,  1.21s/it]

Wikipedia Data saved: ./artist_wiki_pages/Gabriël_Metsu.json

Fetching Wikipedia Data:  90%|█████████ | 1015/1126 [20:42<02:34,  1.40s/it]

Wikipedia Data saved: ./artist_wiki_pages/Nicolas_Poussin.json

Fetching Wikipedia Data:  90%|█████████ | 1016/1126 [20:44<03:20,  1.82s/it]

Wikipedia Data saved: ./artist_wiki_pages/William_Dobson.json

Fetching Wikipedia Data:  90%|█████████ | 1017/1126 [20:45<02:54,  1.60s/it]

Wikipedia Data saved: ./artist_wiki_pages/Willem_van_Aelst.json

Fetching Wikipedia Data:  90%|█████████ | 1018/1126 [20:47<02:35,  1.44s/it]

Wikipedia Data saved: ./artist_wiki_pages/Johann_Heinrich_Schönfeld.json

Fetching Wikipedia Data:  90%|█████████ | 1019/1126 [20:48<02:42,  1.52s/it]

Wikipedia Data saved: ./artist_wiki_pages/Mary_Beale.json

Fetching Wikipedia Data:  91%|█████████ | 1020/1126 [20:49<02:29,  1.41s/it]

Wikipedia Data saved: ./artist_wiki_pages/Larry_Poons.json

Fetching Wikipedia Data:  91%|█████████ | 1021/1126 [20:51<02:34,  1.47s/it]

Wikipedia Data saved: ./artist_wiki_pages/Annibale_Carracci.json

Fetching Wikipedia Data:  91%|█████████ | 1022/1126 [20:52<02:24,  1.39s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jacob_Ochtervelt.json

Fetching Wikipedia Data:  91%|█████████ | 1023/1126 [20:53<02:13,  1.29s/it]

Wikipedia Data saved: ./artist_wiki_pages/Diego_Velázquez.json

Fetching Wikipedia Data:  91%|█████████ | 1024/1126 [20:55<02:11,  1.29s/it]

Wikipedia Data saved: ./artist_wiki_pages/Dirck_van_Baburen.json

Fetching Wikipedia Data:  91%|█████████ | 1025/1126 [20:56<02:05,  1.24s/it]

Wikipedia Data saved: ./artist_wiki_pages/Domenico_Fiasella.json

Fetching Wikipedia Data:  91%|█████████ | 1026/1126 [20:57<02:17,  1.38s/it]

Wikipedia Data saved: ./artist_wiki_pages/Salomon_van_Ruysdael.json

Fetching Wikipedia Data:  91%|█████████ | 1027/1126 [20:58<02:07,  1.29s/it]

Wikipedia Data saved: ./artist_wiki_pages/Jan_Siberechts.json

Fetching Wikipedia Data:  91%|█████████▏| 1028/1126 [21:00<01:59,  1.22s/it]

Η σελίδα 'Iii Kunisada Utagawa' δεν βρέθηκε.

Fetching Wikipedia Data:  91%|█████████▏| 1029/1126 [21:00<01:43,  1.07s/it]

Wikipedia Data saved: ./artist_wiki_pages/Toshihide_Migita.json

Fetching Wikipedia Data:  91%|█████████▏| 1030/1126 [21:01<01:42,  1.07s/it]

Wikipedia Data saved: ./artist_wiki_pages/Utagawa_Toyokuni.json

Fetching Wikipedia Data:  92%|█████████▏| 1031/1126 [21:02<01:41,  1.07s/it]

Η σελίδα 'Yoshiiku Ochiai' δεν βρέθηκε.

Fetching Wikipedia Data:  92%|█████████▏| 1032/1126 [21:03<01:30,  1.04it/s]

Η σελίδα 'Ginko Adachi' δεν βρέθηκε.

Fetching Wikipedia Data:  92%|█████████▏| 1033/1126 [21:04<01:21,  1.14it/s]

Η σελίδα 'Kiyosada Torii' δεν βρέθηκε.

Fetching Wikipedia Data:  92%|█████████▏| 1034/1126 [21:04<01:15,  1.21it/s]

Η σελίδα 'Shigemasa Kitao' δεν βρέθηκε.

Fetching Wikipedia Data:  92%|█████████▏| 1035/1126 [21:05<01:11,  1.27it/s]

Η σελίδα 'Shigenaga Nishimura' δεν βρέθηκε.

Fetching Wikipedia Data:  92%|█████████▏| 1036/1126 [21:06<01:08,  1.31it/s]

Η σελίδα 'Eizan Kikugawa' δεν βρέθηκε.

Fetching Wikipedia Data:  92%|█████████▏| 1037/1126 [21:07<01:06,  1.34it/s]

Wikipedia Data saved: ./artist_wiki_pages/Utamaro.json

Fetching Wikipedia Data:  92%|█████████▏| 1038/1126 [21:08<01:18,  1.12it/s]

Η σελίδα 'Yoshitoyo Utagawa' δεν βρέθηκε.

Fetching Wikipedia Data:  92%|█████████▏| 1039/1126 [21:09<01:13,  1.19it/s]

Wikipedia Data saved: ./artist_wiki_pages/Hokusai.json

Fetching Wikipedia Data:  92%|█████████▏| 1040/1126 [21:10<01:19,  1.09it/s]

Η σελίδα 'Yoshifuji' δεν βρέθηκε.

Fetching Wikipedia Data:  92%|█████████▏| 1041/1126 [21:10<01:12,  1.17it/s]

Η σελίδα 'Masayoshi Kitao' δεν βρέθηκε.

Fetching Wikipedia Data:  93%|█████████▎| 1042/1126 [21:11<01:07,  1.24it/s]

Η σελίδα 'Toyoharu Utagawa' δεν βρέθηκε.

Fetching Wikipedia Data:  93%|█████████▎| 1043/1126 [21:12<01:04,  1.28it/s]

Η σελίδα 'Hokushu Shunkosai' δεν βρέθηκε.

Fetching Wikipedia Data:  93%|█████████▎| 1044/1126 [21:12<01:01,  1.33it/s]

Η σελίδα 'I Kiyomasu Torii' δεν βρέθηκε.

Fetching Wikipedia Data:  93%|█████████▎| 1045/1126 [21:13<01:00,  1.35it/s]

Η σελίδα 'Buncho Ippitsusai' δεν βρέθηκε.

Fetching Wikipedia Data:  93%|█████████▎| 1046/1126 [21:14<00:58,  1.37it/s]

Η σελίδα 'Kunikazu Utagawa' δεν βρέθηκε.

Fetching Wikipedia Data:  93%|█████████▎| 1047/1126 [21:15<00:56,  1.39it/s]

Η σελίδα 'Kuniteru Utagawa' δεν βρέθηκε.

Fetching Wikipedia Data:  93%|█████████▎| 1048/1126 [21:15<00:55,  1.41it/s]

Η σελίδα 'Toshikata Mizuno' δεν βρέθηκε.

Fetching Wikipedia Data:  93%|█████████▎| 1049/1126 [21:16<00:54,  1.42it/s]

Η σελίδα 'Shigenobu Yanagawa' δεν βρέθηκε.

Fetching Wikipedia Data:  93%|█████████▎| 1050/1126 [21:17<00:53,  1.42it/s]

Wikipedia Data saved: ./artist_wiki_pages/Itō_Jakuchū.json

Fetching Wikipedia Data:  93%|█████████▎| 1051/1126 [21:19<01:25,  1.13s/it]

Η σελίδα 'I Toyokuni Utagawa' δεν βρέθηκε.

Fetching Wikipedia Data:  93%|█████████▎| 1052/1126 [21:20<01:14,  1.00s/it]

Η σελίδα 'Hokkei Totoya' δεν βρέθηκε.

Fetching Wikipedia Data:  94%|█████████▎| 1053/1126 [21:20<01:06,  1.10it/s]

Wikipedia Data saved: ./artist_wiki_pages/Sharaku.json

Fetching Wikipedia Data:  94%|█████████▎| 1054/1126 [21:21<01:13,  1.02s/it]

Η σελίδα 'Sadahide Utagawa' δεν βρέθηκε.

Fetching Wikipedia Data:  94%|█████████▎| 1055/1126 [21:22<01:05,  1.08it/s]

Η σελίδα 'Sukenobu Nishikawa' δεν βρέθηκε.

Fetching Wikipedia Data:  94%|█████████▍| 1056/1126 [21:23<01:00,  1.17it/s]

Η σελίδα 'Yoshitsuya Utagawa' δεν βρέθηκε.

Fetching Wikipedia Data:  94%|█████████▍| 1057/1126 [21:24<00:55,  1.24it/s]

Η σελίδα 'Eisui Ichirakutei' δεν βρέθηκε.

Fetching Wikipedia Data:  94%|█████████▍| 1058/1126 [21:24<00:52,  1.29it/s]

Η σελίδα 'Shuntei Katsukawa' δεν βρέθηκε.

Fetching Wikipedia Data:  94%|█████████▍| 1059/1126 [21:25<00:50,  1.33it/s]

Η σελίδα 'I Sadanobu Hasegawa' δεν βρέθηκε.

Fetching Wikipedia Data:  94%|█████████▍| 1060/1126 [21:26<00:48,  1.36it/s]

Η σελίδα 'Shunko Katsukawa' δεν βρέθηκε.

Fetching Wikipedia Data:  94%|█████████▍| 1061/1126 [21:26<00:47,  1.38it/s]

Η σελίδα 'Fusatane Utagawa' δεν βρέθηκε.

Fetching Wikipedia Data:  94%|█████████▍| 1062/1126 [21:27<00:45,  1.39it/s]

Wikipedia Data saved: ./artist_wiki_pages/Shunsho_Katsukawa.json

Fetching Wikipedia Data:  94%|█████████▍| 1063/1126 [21:28<00:52,  1.21it/s]

Wikipedia Data saved: ./artist_wiki_pages/Moronobu_Hishikawa.json

Fetching Wikipedia Data:  94%|█████████▍| 1064/1126 [21:29<00:55,  1.12it/s]

Η σελίδα 'Hirosada Utagawa' δεν βρέθηκε.

Fetching Wikipedia Data:  95%|█████████▍| 1065/1126 [21:30<00:51,  1.20it/s]

Wikipedia Data saved: ./artist_wiki_pages/Itō_Shinsui.json

Fetching Wikipedia Data:  95%|█████████▍| 1066/1126 [21:32<01:07,  1.13s/it]

Η σελίδα 'I Kiyotada Torii' δεν βρέθηκε.

Fetching Wikipedia Data:  95%|█████████▍| 1067/1126 [21:32<00:59,  1.00s/it]

Wikipedia Data saved: ./artist_wiki_pages/Kiyochika_Kobayashi.json

Fetching Wikipedia Data:  95%|█████████▍| 1068/1126 [21:33<00:59,  1.02s/it]

Wikipedia Data saved: ./artist_wiki_pages/Harunobu_Suzuki.json

Fetching Wikipedia Data:  95%|█████████▍| 1069/1126 [21:35<00:59,  1.04s/it]

Wikipedia Data saved: ./artist_wiki_pages/Kunichika_Toyohara.json

Fetching Wikipedia Data:  95%|█████████▌| 1070/1126 [21:37<01:15,  1.35s/it]

Wikipedia Data saved: ./artist_wiki_pages/Utagawa_Kunisada_II.json

Fetching Wikipedia Data:  95%|█████████▌| 1071/1126 [21:38<01:09,  1.27s/it]

Η σελίδα 'Kuniaki Utagawa' δεν βρέθηκε.

Fetching Wikipedia Data:  95%|█████████▌| 1072/1126 [21:38<00:59,  1.10s/it]

Wikipedia Data saved: ./artist_wiki_pages/Hiroshige.json

Fetching Wikipedia Data:  95%|█████████▌| 1073/1126 [21:40<00:58,  1.10s/it]

Wikipedia Data saved: ./artist_wiki_pages/Utagawa_Toyokuni_II.json

Fetching Wikipedia Data:  95%|█████████▌| 1074/1126 [21:41<00:57,  1.11s/it]

Η σελίδα 'Toyohiro Utagawa' δεν βρέθηκε.

Fetching Wikipedia Data:  95%|█████████▌| 1075/1126 [21:41<00:50,  1.02it/s]

Wikipedia Data saved: ./artist_wiki_pages/Okumura_Masanobu.json

Fetching Wikipedia Data:  96%|█████████▌| 1076/1126 [21:42<00:51,  1.02s/it]

Η σελίδα 'Ashiyuki Gigado' δεν βρέθηκε.

Fetching Wikipedia Data:  96%|█████████▌| 1077/1126 [21:43<00:45,  1.08it/s]

Η σελίδα 'Yoshikuni Toyokawa' δεν βρέθηκε.

Fetching Wikipedia Data:  96%|█████████▌| 1078/1126 [21:44<00:41,  1.16it/s]

Wikipedia Data saved: ./artist_wiki_pages/Choki_Eishosai.json

Fetching Wikipedia Data:  96%|█████████▌| 1079/1126 [21:45<00:43,  1.08it/s]

Η σελίδα 'Ii Kiyonobu Torii' δεν βρέθηκε.

Fetching Wikipedia Data:  96%|█████████▌| 1080/1126 [21:46<00:39,  1.15it/s]

Η σελίδα 'Gakutei Yashima' δεν βρέθηκε.

Fetching Wikipedia Data:  96%|█████████▌| 1081/1126 [21:46<00:36,  1.23it/s]

Wikipedia Data saved: ./artist_wiki_pages/Keisai_Eisen.json

Fetching Wikipedia Data:  96%|█████████▌| 1082/1126 [21:47<00:39,  1.11it/s]

Η σελίδα 'Kiyohiro Torii' δεν βρέθηκε.

Fetching Wikipedia Data:  96%|█████████▌| 1083/1126 [21:48<00:36,  1.19it/s]

Η σελίδα 'Shunzan Katsukawa' δεν βρέθηκε.

Fetching Wikipedia Data:  96%|█████████▋| 1084/1126 [21:49<00:33,  1.25it/s]

Η σελίδα 'Ii Hiroshige Utagawa' δεν βρέθηκε.

Fetching Wikipedia Data:  96%|█████████▋| 1085/1126 [21:50<00:31,  1.30it/s]

Η σελίδα 'Toyonobu Ishikawa' δεν βρέθηκε.

Fetching Wikipedia Data:  96%|█████████▋| 1086/1126 [21:50<00:29,  1.34it/s]

Wikipedia Data saved: ./artist_wiki_pages/Toyohara_Chikanobu.json

Fetching Wikipedia Data:  97%|█████████▋| 1087/1126 [21:51<00:32,  1.19it/s]

Η σελίδα 'Yasuji Inoue' δεν βρέθηκε.

Fetching Wikipedia Data:  97%|█████████▋| 1088/1126 [21:52<00:30,  1.25it/s]

Η σελίδα 'Sadatora Utagawa' δεν βρέθηκε.

Fetching Wikipedia Data:  97%|█████████▋| 1089/1126 [21:53<00:28,  1.29it/s]

Η σελίδα 'Ii Kiyomasu Torii' δεν βρέθηκε.

Fetching Wikipedia Data:  97%|█████████▋| 1090/1126 [21:53<00:27,  1.33it/s]

Η σελίδα 'Hanko Kajita' δεν βρέθηκε.

Fetching Wikipedia Data:  97%|█████████▋| 1091/1126 [21:54<00:25,  1.36it/s]

Η σελίδα 'Yoshitora Utagawa' δεν βρέθηκε.

Fetching Wikipedia Data:  97%|█████████▋| 1092/1126 [21:55<00:24,  1.38it/s]

Η σελίδα 'Ikkei' δεν βρέθηκε.

Fetching Wikipedia Data:  97%|█████████▋| 1093/1126 [21:56<00:23,  1.39it/s]

Η σελίδα 'Kyosai Kawanabe' δεν βρέθηκε.

Fetching Wikipedia Data:  97%|█████████▋| 1094/1126 [21:56<00:22,  1.40it/s]

Wikipedia Data saved: ./artist_wiki_pages/Kunisada.json

Fetching Wikipedia Data:  97%|█████████▋| 1095/1126 [21:57<00:26,  1.19it/s]

Η σελίδα 'Hirokage Utagawa' δεν βρέθηκε.

Fetching Wikipedia Data:  97%|█████████▋| 1096/1126 [21:58<00:24,  1.25it/s]

Wikipedia Data saved: ./artist_wiki_pages/Ogata_Gekko.json

Fetching Wikipedia Data:  97%|█████████▋| 1097/1126 [21:59<00:25,  1.13it/s]

Η σελίδα 'I Kiyonobu Torii' δεν βρέθηκε.

Fetching Wikipedia Data:  98%|█████████▊| 1098/1126 [22:00<00:23,  1.21it/s]

Η σελίδα 'Koryusai Isoda' δεν βρέθηκε.

Fetching Wikipedia Data:  98%|█████████▊| 1099/1126 [22:01<00:21,  1.27it/s]

Η σελίδα 'Toshinobu Okumura' δεν βρέθηκε.

Fetching Wikipedia Data:  98%|█████████▊| 1100/1126 [22:01<00:19,  1.31it/s]

Wikipedia Data saved: ./artist_wiki_pages/Shunei_Katsukawa.json

Fetching Wikipedia Data:  98%|█████████▊| 1101/1126 [22:02<00:21,  1.16it/s]

Η σελίδα 'Iii Hiroshige Utagawa' δεν βρέθηκε.

Fetching Wikipedia Data:  98%|█████████▊| 1102/1126 [22:03<00:19,  1.23it/s]

Η σελίδα 'Shuncho Katsukawa' δεν βρέθηκε.

Fetching Wikipedia Data:  98%|█████████▊| 1103/1126 [22:04<00:17,  1.29it/s]

Η σελίδα 'Bairei Kono' δεν βρέθηκε.

Fetching Wikipedia Data:  98%|█████████▊| 1104/1126 [22:04<00:16,  1.33it/s]

Wikipedia Data saved: ./artist_wiki_pages/Seiko.json

Fetching Wikipedia Data:  98%|█████████▊| 1105/1126 [22:06<00:20,  1.02it/s]

Η σελίδα 'Hokuju Shotei' δεν βρέθηκε.

Fetching Wikipedia Data:  98%|█████████▊| 1106/1126 [22:07<00:17,  1.12it/s]

Η σελίδα 'Hokuba Teisai' δεν βρέθηκε.

Fetching Wikipedia Data:  98%|█████████▊| 1107/1126 [22:07<00:15,  1.19it/s]

Η σελίδα 'Toyoshige Utagawa' δεν βρέθηκε.

Fetching Wikipedia Data:  98%|█████████▊| 1108/1126 [22:08<00:14,  1.26it/s]

Η σελίδα 'Shunman Kubo' δεν βρέθηκε.

Fetching Wikipedia Data:  98%|█████████▊| 1109/1126 [22:09<00:12,  1.31it/s]

Wikipedia Data saved: ./artist_wiki_pages/Shibata_Zeshin.json

Fetching Wikipedia Data:  99%|█████████▊| 1110/1126 [22:10<00:16,  1.06s/it]

Η σελίδα 'Eisho Chokosai' δεν βρέθηκε.

Fetching Wikipedia Data:  99%|█████████▊| 1111/1126 [22:11<00:14,  1.05it/s]

Η σελίδα 'Kunitoshi Utagawa' δεν βρέθηκε.

Fetching Wikipedia Data:  99%|█████████▉| 1112/1126 [22:12<00:12,  1.14it/s]

Η σελίδα 'Keinen Imao' δεν βρέθηκε.

Fetching Wikipedia Data:  99%|█████████▉| 1113/1126 [22:13<00:10,  1.22it/s]

Wikipedia Data saved: ./artist_wiki_pages/Yoshitoshi.json

Fetching Wikipedia Data:  99%|█████████▉| 1114/1126 [22:15<00:14,  1.25s/it]

Wikipedia Data saved: ./artist_wiki_pages/Kogyo_Tsukioka.json

Fetching Wikipedia Data:  99%|█████████▉| 1115/1126 [22:16<00:13,  1.20s/it]

Η σελίδα 'Keishu Takeuchi' δεν βρέθηκε.

Fetching Wikipedia Data:  99%|█████████▉| 1116/1126 [22:17<00:10,  1.05s/it]

Η σελίδα 'Kuniyasu Utagawa' δεν βρέθηκε.

Fetching Wikipedia Data:  99%|█████████▉| 1117/1126 [22:17<00:08,  1.05it/s]

Η σελίδα 'Kiyomine Torii' δεν βρέθηκε.

Fetching Wikipedia Data:  99%|█████████▉| 1118/1126 [22:18<00:06,  1.14it/s]

Wikipedia Data saved: ./artist_wiki_pages/Hiroshige.json

Fetching Wikipedia Data:  99%|█████████▉| 1119/1126 [22:19<00:06,  1.04it/s]

Η σελίδα 'Yoshitaki Utagawa' δεν βρέθηκε.

Fetching Wikipedia Data:  99%|█████████▉| 1120/1126 [22:20<00:05,  1.13it/s]

Η σελίδα 'Kunimasa Utagawa' δεν βρέθηκε.

Fetching Wikipedia Data: 100%|█████████▉| 1121/1126 [22:21<00:04,  1.21it/s]

Η σελίδα 'Yoshikazu Utagawa' δεν βρέθηκε.

Fetching Wikipedia Data: 100%|█████████▉| 1122/1126 [22:21<00:03,  1.27it/s]

Wikipedia Data saved: ./artist_wiki_pages/Utagawa_Kuniyoshi.json

Fetching Wikipedia Data: 100%|█████████▉| 1123/1126 [22:22<00:02,  1.15it/s]

Η σελίδα 'Eishi Hosoda' δεν βρέθηκε.

Fetching Wikipedia Data: 100%|█████████▉| 1124/1126 [22:23<00:01,  1.21it/s]

Wikipedia Data saved: ./artist_wiki_pages/Hokkei.json

Fetching Wikipedia Data: 100%|█████████▉| 1125/1126 [22:24<00:00,  1.10it/s]

Η σελίδα 'Shunsen Katsukawa' δεν βρέθηκε.

Fetching Wikipedia Data: 100%|██████████| 1126/1126 [22:25<00:00,  1.19s/it]

Task Complete. Successfully fetched 822 Wikipedia articles.

In [11]:
from SPARQLWrapper import SPARQLWrapper, JSON
import json

# Ρύθμιση του DBpedia Endpoint
sparql = SPARQLWrapper("http://dbpedia.org/sparql")

In [15]:
def fetch_artist_full_knowledge(artist_name):
    resource_slug = artist_name.replace(" ", "_")
    resource_url = f"http://dbpedia.org/resource/{resource_slug}"
    
    sparql = SPARQLWrapper("http://dbpedia.org/sparql")
    
    # Το query τώρα ψάχνει συγκεκριμένα για movement, influencedBy και subjects (categories)
    query = f"""
    PREFIX dbo: <http://dbpedia.org/ontology/>
    PREFIX dbp: <http://dbpedia.org/property/>
    PREFIX dct: <http://purl.org/dc/terms/>
    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

    SELECT ?rel ?val WHERE {{
      {{ <{resource_url}> dbo:artMovement ?val . BIND("movement" AS ?rel) }}
      UNION
      {{ <{resource_url}> dbp:movement ?val . BIND("movement" AS ?rel) }}
      UNION
      {{ <{resource_url}> dbo:influencedBy ?val . BIND("influencedBy" AS ?rel) }}
      UNION
      {{ <{resource_url}> dbp:knownFor ?val . BIND("knownFor" AS ?rel) }}
      UNION
      {{ <{resource_url}> dct:subject ?val . BIND("category" AS ?rel) }}
      UNION
      {{ <{resource_url}> dbo:wikiPageWikiLink ?val . BIND("connection" AS ?rel) }}
    }}
    """
    
    sparql.setQuery(query)
    sparql.setReturnFormat(JSON)
    
    try:
        results = sparql.query().convert()
        data = {"movement": [], "influencedBy": [], "categories": [], "connections": []}
        
        for res in results["results"]["bindings"]:
            rel = res["rel"]["value"]
            val = res["val"]["value"].split('/')[-1].replace('_', ' ')
            
            if rel == "movement" or rel == "knownFor": data["movement"].append(val)
            elif rel == "influencedBy": data["influencedBy"].append(val)
            elif rel == "category": data["categories"].append(val)
            elif rel == "connection": data["connections"].append(val)
            
        # Καθαρισμός διπλότυπων
        for k in data: data[k] = list(set(data[k]))
        return data
    except Exception as e:
        return None

# Test
frank_knowledge = fetch_artist_full_knowledge("Frank_O'Meara")
print(json.dumps(frank_knowledge, indent=2))

{
  "movement": [
    "Impressionism",
    "Impressionist painting"
  ],
  "influencedBy": [],
  "categories": [
    "Category:Artists from County Carlow",
    "Category:19th-century Irish male artists",
    "Category:19th-century Irish painters",
    "Category:Irish male painters",
    "Category:People educated at St Mary's Knockbeg College",
    "Category:1853 births",
    "Category:People from Carlow (town)",
    "Category:Irish Impressionist painters",
    "Category:1888 deaths"
  ],
  "connections": [
    "Carlow",
    "Category:19th-century Irish male artists",
    "Carolus Duran",
    "En plein air",
    "Ulster Museum",
    "County Carlow",
    "National Gallery of Ireland",
    "Royal Glasgow Institute of the Fine Arts",
    "Kathleen O'Meara (writer)",
    "Crawford Art Gallery",
    "William Stott (artist)",
    "Dublin City Gallery The Hugh Lane",
    "Category:1888 deaths",
    "Impressionism",
    "Grez-sur-Loing",
    "Carl Larsson",
    "Barbizon",
    "Napoleon",
    "Category:19th-century Irish painters",
    "Dublin",
    "Fanny Osbourne",
    "Category:People from County Carlow",
    "Boulevard du Montparnasse",
    "Barry Edward O'Meara",
    "St. Mary's Knockbeg College",
    "John Singer Sargent",
    "Robert Louis Stevenson",
    "John Lavery",
    "Belfast",
    "Category:Irish Impressionist painters",
    "Category:Irish male painters",
    "Category:1853 births",
    "St. Helena",
    "The Tablet",
    "Royal Hibernian Academy",
    "Diego Vel\u00e1zquez",
    "File:Omearaautumnal.jpg",
    "The Douglas Hyde Gallery",
    "Category:People educated at St Mary's Knockbeg College",
    "Hugh Lane Municipal Gallery",
    "Isobel Osbourne",
    "File:O'Meara Quays.jpg"
  ]
}

In [16]:
from SPARQLWrapper import SPARQLWrapper, JSON
import json

def fetch_artist_triples(artist_name):
    # Ensure name format is correct for DBpedia URL
    resource_slug = artist_name.replace(" ", "_")
    resource_url = f"http://dbpedia.org/resource/{resource_slug}"
    
    sparql = SPARQLWrapper("http://dbpedia.org/sparql")
    
    # We select EVERYTHING (?p = predicate, ?o = object)
    # We use <{resource_url}> to handle apostrophes safely
    query = f"""
    SELECT ?p ?o WHERE {{
      <{resource_url}> ?p ?o .
    }}
    """
    
    sparql.setQuery(query)
    sparql.setReturnFormat(JSON)
    
    try:
        results = sparql.query().convert()
        triples = []
        
        for res in results["results"]["bindings"]:
            predicate = res["p"]["value"]
            obj = res["o"]["value"]
            
            # We keep the full URIs for the KG, but you can 
            # also store a 'clean' version for display
            triples.append({
                "subject": resource_url,
                "predicate": predicate,
                "object": obj
            })
            
        return triples
    except Exception as e:
        print(f"Error for {artist_name}: {e}")
        return []

# Test for Frank O'Meara
frank_triples = fetch_artist_triples("Frank_O'Meara")

# Print the first 5 triples to see the structure
print(f"Total Triples Found: {len(frank_triples)}")
print(json.dumps(frank_triples[:5], indent=2))

Total Triples Found: 126
[
  {
    "subject": "http://dbpedia.org/resource/Frank_O'Meara",
    "predicate": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
    "object": "http://www.w3.org/2002/07/owl#Thing"
  },
  {
    "subject": "http://dbpedia.org/resource/Frank_O'Meara",
    "predicate": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
    "object": "http://xmlns.com/foaf/0.1/Person"
  },
  {
    "subject": "http://dbpedia.org/resource/Frank_O'Meara",
    "predicate": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
    "object": "http://dbpedia.org/ontology/Person"
  },
  {
    "subject": "http://dbpedia.org/resource/Frank_O'Meara",
    "predicate": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
    "object": "http://dbpedia.org/ontology/Person"
  },
  {
    "subject": "http://dbpedia.org/resource/Frank_O'Meara",
    "predicate": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
    "object": "http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#NaturalPerson"
  }
]

In [21]:
import pandas as pd
import json
import os

def save_artist_kg(artist_name, triples, folder="./"):
    if not os.path.exists(folder):
        os.makedirs(folder)
    
    # Create a DataFrame for the triples
    kg_df = pd.DataFrame(triples)
    
    # 1. Save the Raw Triples (Full URIs) - Best for Graph DBs
    raw_path = os.path.join(folder, f"{artist_name}_raw_kg.csv")
    kg_df.to_csv(raw_path, index=False)
    
    # 2. Save a "Clean" version for human reading and Bayesian Analysis
    # This removes the long http://dbpedia.org/... prefixes
    clean_df = kg_df.copy()
    clean_df['predicate'] = clean_df['predicate'].apply(lambda x: x.split('/')[-1].split('#')[-1])
    clean_df['object'] = clean_df['object'].apply(lambda x: x.split('/')[-1] if 'http' in str(x) else x)
    
    clean_path = os.path.join(folder, f"{artist_name}_clean_kg.csv")
    clean_df.to_csv(clean_path, index=False)
    
    print(f"Graph nodes saved for {artist_name}:")
    print(f" - Raw: {raw_path}")
    print(f" - Clean: {clean_path}")
    return clean_df

# --- EXECUTION ---
# 1. Fetch
frank_triples = fetch_artist_triples("Frank_O'Meara")

# 2. Save
if frank_triples:
    clean_kg = save_artist_kg("Frank_O'Meara", frank_triples)
    
    # Preview the clean triples
    print("\n--- Knowledge Graph Preview (Cleaned) ---")
    display(clean_kg.head(10))

Graph nodes saved for Frank_O'Meara:
 - Raw: ./Frank_O'Meara_raw_kg.csv
 - Clean: ./Frank_O'Meara_clean_kg.csv

--- Knowledge Graph Preview (Cleaned) ---

                                     subject predicate                 object
0  http://dbpedia.org/resource/Frank_O'Meara      type              owl#Thing
1  http://dbpedia.org/resource/Frank_O'Meara      type                 Person
2  http://dbpedia.org/resource/Frank_O'Meara      type                 Person
3  http://dbpedia.org/resource/Frank_O'Meara      type                 Person
4  http://dbpedia.org/resource/Frank_O'Meara      type  DUL.owl#NaturalPerson
5  http://dbpedia.org/resource/Frank_O'Meara      type                 Q19088
6  http://dbpedia.org/resource/Frank_O'Meara      type                Q215627
7  http://dbpedia.org/resource/Frank_O'Meara      type                Q483501
8  http://dbpedia.org/resource/Frank_O'Meara      type                     Q5
9  http://dbpedia.org/resource/Frank_O'Meara      type                   Q729

new dbpedia

In [17]:
import pandas as pd
import json
import os
import time
from tqdm import tqdm
from SPARQLWrapper import SPARQLWrapper, JSON
from urllib.parse import unquote

# --- CONFIGURATION ---
sparql = SPARQLWrapper("http://dbpedia.org/sparql")
sparql.setTimeout(30) # Increase timeout for large batches
OUTPUT_FOLDER = "./artist_knowledge_graphs"

# --- HELPER FUNCTIONS ---

def get_dbpedia_resource_name(wiki_field):
    """Extracts the identifier from the Wikipedia URL."""
    if not wiki_field or not isinstance(wiki_field, str):
        return None
    if "/wiki/" in wiki_field:
        # Some URLs in your JSON might not have https://, this split handles both
        resource_part = wiki_field.split("/wiki/")[-1]
        return unquote(resource_part)
    return None

def fetch_artist_triples(resource_name):
    """Queries DBpedia for all triples associated with the artist."""
    # We use <...> to handle names with special characters like apostrophes
    query = f"""
    SELECT ?predicate ?object
    WHERE {{
      <http://dbpedia.org/resource/{resource_name}> ?predicate ?object .
    }}
    """
    sparql.setQuery(query)
    sparql.setReturnFormat(JSON)
    
    try:
        results = sparql.query().convert()
        bindings = results["results"]["bindings"]
        return [{"subject": f"http://dbpedia.org/resource/{resource_name}", 
                 "predicate": b["predicate"]["value"], 
                 "object": b["object"]["value"]} for b in bindings]
    except Exception as e:
        # Return None to indicate a network or query failure
        return None

def save_artist_kg(artist_name, triples, folder):
    """Saves both raw and cleaned versions of the knowledge graph."""
    if not os.path.exists(folder):
        os.makedirs(folder)
    
    # Clean filename for the OS (removing characters that break file paths)
    safe_name = artist_name.replace("'", "").replace('"', "").replace("/", "_").replace(":", "_")
    
    df = pd.DataFrame(triples)
    
    # 1. Save RAW
    raw_path = os.path.join(folder, f"{safe_name}_raw.csv")
    df.to_csv(raw_path, index=False)
    
    # 2. Save CLEAN
    clean_df = df.copy()
    clean_df['predicate'] = clean_df['predicate'].apply(lambda x: x.split('/')[-1].split('#')[-1])
    clean_df['object'] = clean_df['object'].apply(lambda x: x.split('/')[-1] if 'http' in str(x) else x)
    clean_df['subject'] = artist_name
    
    clean_path = os.path.join(folder, f"{safe_name}_clean.csv")
    clean_df.to_csv(clean_path, index=False)

# --- MAIN EXECUTION ---

# 1. Load your full JSON file
with open('wikiart_artist_metadata1.json', 'r', encoding='utf-8') as f:
    artists_list = json.load(f)

print(f"Total artists to process: {len(artists_list)}")

# 2. Loop with error handling and rate limiting
for artist in tqdm(artists_list, desc="Scraping DBpedia"):
    wiki_link = artist.get("wikipedia")
    res_name = get_dbpedia_resource_name(wiki_link)
    
    if res_name:
        # Check if we already have this file (useful if the script crashes and you restart)
        safe_name = res_name.replace("'", "").replace('"', "").replace("/", "_").replace(":", "_")
        if os.path.exists(os.path.join(OUTPUT_FOLDER, f"{safe_name}_raw.csv")):
            continue 

        # Attempt to fetch data
        data = fetch_artist_triples(res_name)
        
        if data:
            save_artist_kg(res_name, data, OUTPUT_FOLDER)
        else:
            # If data is None, there was likely a timeout or a 404
            # We wait a bit longer before next try
            time.sleep(2) 
    
    # Respectful delay between requests
    time.sleep(0.4)

print(f"\nAll done! Data saved in: {OUTPUT_FOLDER}")

Total artists to process: 1126

Scraping DBpedia: 100%|██████████| 1126/1126 [15:58<00:00,  1.18it/s]

All done! Data saved in: ./artist_knowledge_graphs